### ISSUE TITLE
Document how to get the language server

### ISSUE THREAD

**Issue by mattiasb** [emacs-lsp/lsp-java#1]
Hi!

I wanted to try out `lsp-java` but I'm stuck trying to find a server download.

A little bit of documentation in the package header and / or README.md wouldn't hurt. :)

**Comment by mattiasb** [comment]
After some research I found the proper download link: http://download.eclipse.org/jdtls/snapshots/jdt-language-server-latest.tar.gz

**Comment by vibhavp** [comment]
Unfortunately, I don't use Java, so I don't know how to set this up.
@tutysara do you think you could add some instructions to the README?

**Comment by mattiasb** [comment]
In short unzip the above tarball into `~/.emacs.d/eclipse.jdt.ls/server/` and add a `(require lsp-java)` was enough to get going.
However, emacs hung for me soon after and was in general very unresponsive so I gave up.

**Comment by vibhavp** [comment]
Yeah, some language server are still being buggy. Could you add a new issue? I'll see what I can do

**Comment by tutysara** [comment]
@vibhavp sure, let me work on it.
@mattiasb glad you were able to find it, let me get the new code and see if it works smoothly

**Comment by naclander** [comment]
Can you explain what is different between all of the following language servers?

* http://download.eclipse.org/jdtls/snapshots/
* https://github.com/georgewfraser/vscode-javac
* https://github.com/eclipse/eclipse.jdt.ls
* https://github.com/redhat-developer/vscode-java

I think https://github.com/eclipse/eclipse.jdt.ls is the "supported" and "recommended" server to use, right?

Similar to waht @vibhavp said, I am having trouble getting the Java language server running as well. It seems unclear from lsp-java whether it is interacting with a server or not.

**Comment by tutysara** [comment]
yes,  https://github.com/eclipse/eclipse.jdt.ls  is the one used in vscode and http://download.eclipse.org/jdtls/snapshots/ is the place to download pre built binaries.

**Comment by yyoncho** [comment]
Closing since the latest documentation contains information how to obtain the server. Please reopen if you think that there is more work to do.
