### ISSUE TITLE
JDK path error and lsp-java did not download server JDT

### ISSUE THREAD

**Issue by testinggithub1222** [emacs-lsp/lsp-java#103]
Hello everyone! 
I have configure my lsp-java as the following and when i tried to open the project, I got some error about jdk. I am sure that i have set java-java-path pointing to my jdk folder  and also **export JAVA_HOME=/usr/lib/jvm/java-8-openjdk/bin/java** or **export JAVA_HOME=/usr/lib/jvm/java-8-openjdk** but i am not sure why it still point to oracle jdk for no reason. Furthermore, I have check in **~/.emacs.d/.appdata/.g_lsp_java_jtd** but i could not find this folder. And when i tried to run the project, it require me to install server and then if **~/.emacs.d/.appdata/.g_lsp_java_jtd/plugins** is not create manually, it also throw some error as below quote but if i manually create the folder, then i got another error as following **File mode specification error: (error Unable to find single point of entry nil)**
. 

```
Server is not installed. Do you want to install it? (y or n) y
Contacting host: raw.githubusercontent.com:443
Wrote /tmp/lsp-java-install/pom.xml
Contacting host: raw.githubusercontent.com:443
Wrote /tmp/lsp-java-install/mvnw
Wrote /tmp/lsp-java-install/.mvn/wrapper/MavenWrapperDownloader.java
Contacting host: raw.githubusercontent.com:443
Wrote /tmp/lsp-java-install/.mvn/wrapper/maven-wrapper.properties
Running sh mvnw -Djdt.js.server.root=/home/mypc/.emacs.d/.appdata/.g_lsp_java_jtd -Djunit.runner.root=/home/mypc/.emacs.d/.appdata/test-runner -Djunit.runner.fileName=junit-platform-console-standalone.jar -Djava.debug.root=/home/mypc/.emacs.d/.appdata/.g_lsp_java_jtd/bundles clean package
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/lib/jvm/java-8-oracle/bin/java
File mode specification error: (file-missing Opening directory No such file or directory /home/mypc/.emacs.d/.appdata/.g_lsp_java_jtd/plugins)
Followed link to /home/mypc/.emacs-repo/.emacs
Mark saved where search started
```

```

(use-package lsp-java
  :ensure t
  :after lsp-mode
  :config
  (add-hook 'java-mode-hook 'lsp)
  (progn
    (setq
     lsp-java-java-path "/usr/lib/jvm/java-8-openjdk/bin/java"
;; lsp-java-java-path "/usr/lib/jvm/java-8-openjdk" ;; still not working. Note, this directory is existed 
     lsp-java-workspace-dir "/home/mypc/test/javaapi/" 
     lsp-java-server-install-dir "~/.emacs.d/.appdata/.g_lsp_java_jtd"
     lsp-java-workspace-cache-dir t
     lsp-java-format-enabled t
     lsp-java-format-comments-enabled t
     lsp-java-save-action-organize-imports t
     lsp-java-save-action-organize-imports t
     lsp-java-import-gradle-enabled t
     lsp-java-import-maven-enabled t
     lsp-java-auto-build t
     lsp-print-io t
     lsp-java-progress-report t
     lsp-java-completion-guess-arguments t
     lsp-java-enable-file-watch t

     ;; Debug Server
     lsp-java-trace-server t
     lsp-java-progress-report t
     )
    )
  )
```

**Comment by yyoncho** [comment]
Did you try to run `sh mvnw -Djdt.js.server.root=/home/mypc/.emacs.d/.appdata/.g_lsp_java_jtd -Djunit.runner.root=/home/mypc/.emacs.d/.appdata/test-runner -Djunit.runner.fileName=junit-platform-console-standalone.jar -Djava.debug.root=/home/mypc/.emacs.d/.appdata/.g_lsp_java_jtd/bundles clean package` outside emacs? Also, make sure that the java that is in the path is the java you want to use? You could do that by executing `java -version`. I would recommend using the oracle java - it seems like the language server is working better using it.

**Comment by testinggithub1222** [comment]
At that time i wasn't but after you advice, i have tried it, tried the one i got from **message** buffer and yes it did run and everything is working. But after restart emacs, nothing is working. I have tried to invoke that command provided by **message** buffer no, it said that "sh: 0: Can't open mvnw" and i got no idea why.

Anyway, why should we manually do that? couldnt lsp automatically do that for us so we dont need to run that command manually? 

By the way, I am not sure how to use this mode properly and i am sure that many people cannot got this well too. Imagine if i have gradle or maven project, so how can i use this mode? Is that it's correct that i open any java file inside the project? or is that any correct way than this?  I think it'd be better if everything notes inside the doc so we confidently know if something we did correct.
Thank you,

**Comment by yyoncho** [comment]
> I have tried to invoke that command provided by message buffer no, it said that "sh: 0: Can't open mvnw" and i got no idea why.

You should do it from the same directory that lsp-java is using which - `/tmp/lsp-java-install/` .

> Anyway, why should we manually do that? couldnt lsp automatically do that for us so we dont need to run that command manually?

The only thing that lsp-java requires is to have properly configured java and it automatically downloads everything you need. 

> By the way, I am not sure how to use this mode properly and i am sure that many people cannot got this well too. Imagine if i have gradle or maven project, so how can i use this mode? Is that it's correct that i open any java file inside the project? or is that any correct way than this? I think it'd be better if everything notes inside the doc so we confidently know if something we did correct.

As per docs - you just open a file and follow the instructions.

**Comment by testinggithub1222** [comment]
I see why i cannot run the command the second time because the first time i was standing at the project root directory. Anyway, there is still some doubt i got:
1. Do i have to run the command you provide everytime or only the once, the first time i set up my environment, am i right? 
2. I am not sure what is going on after running the command but even it's succeed, there is no auto complete for me. Please kindly check the following output:

```

mypc@yourpc:/tmp/lsp-java-install$ sh mvnw -Djdt.js.server.root=/home/mypc/.emacs.d/.appdata/.g_lsp_java_jtd -Djunit.runner.root=/home/mypc/.emacs.d/.appdata/test-runner -Djunit.runner.fileName=junit-platform-console-standalone.jar -Djava.debug.root=/home/mypc/.emacs.d/.appdata/.g_lsp_java_jtd/bundles clean package

[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------------< lsp-java:lsp-java >--------------------------
[INFO] Building lsp-java 1.0.0-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ lsp-java ---
[INFO] Deleting /tmp/lsp-java-install/target
[INFO] 
[INFO] --- download-maven-plugin:1.3.0:wget (default) @ lsp-java ---
[INFO] Got from cache: /home/mypc/.m2/repository/.cache/download-maven-plugin/che-jdt-language-server-latest.tar.gz_227786bc5f7f4578c50b0ab3ac10b7fd
[INFO] 
[INFO] --- maven-antrun-plugin:1.6:run (prepare) @ lsp-java ---
[WARNING] Parameter tasks is deprecated, use target instead
[INFO] Executing tasks

main:
    [untar] Expanding: /tmp/lsp-java-install/target/che-jdt-language-server-latest.tar.gz into /home/mypc/.emacs.d/.appdata/.g_lsp_java_jtd
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:copy (copy) @ lsp-java ---
[INFO] Configured Artifact: com.microsoft.java:com.microsoft.java.debug.plugin:0.11.0:jar
[INFO] Configured Artifact: org.junit.platform:junit-platform-console-standalone:1.3.0-M1:jar
[INFO] com.microsoft.java:com.microsoft.java.debug.plugin:0.11.0:jar already exists in /home/mypc/.emacs.d/.appdata/.g_lsp_java_jtd/bundles
[INFO] org.junit.platform:junit-platform-console-standalone:1.3.0-M1:jar already exists in /home/mypc/.emacs.d/.appdata/test-runner
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.218 s
[INFO] Finished at: 2019-02-14T14:07:19+07:00
[INFO] ------------------------------------------------------------------------
```

**Comment by yyoncho** [comment]
> Do i have to run the command you provide everytime or only the once, the first time i set up my environment, am i right?

It will run only once.

> I am not sure what is going on after running the command but even it's succeed, there is no auto complete for me. Please kindly check the following output:

You havent imported the project. Also, make sure that you are using maven/gradle/eclipse project and you are selecting the proper root.

Please make sure that you are reproducing the issues using the configuration from getting started section. Note that there is **no** mention of `lsp-java-enable` function anywhere.

> 
> **Note**
> Before logging the bug please make sure that the issue is reproducible with latest melpa packages and it is reproducible with the clean config(the config from the getting started page).

**Comment by testinggithub1222** [comment]
I am not sure how to import project. Is that the first time you open project and prompt for import? if so what if i did not select it because it doesn't prompt me again to select the or import. And I think if those info is listed in the main page, would be be great so new user like me would be benefit. Anyway, thanks!

**Comment by yyoncho** [comment]
Here it is how the initial import looks like...

![selection_014](https://user-images.githubusercontent.com/13259670/52776201-c9544600-3049-11e9-8196-33889094d6f1.png)

... and you may trigger it by pretty much everything:

1. M-x lsp
2. Close and reopen file
3. Restart emacs

Please, let me know what is not clear in this dialog and what exactly do you think that the readme should have. IMO this is self describing but if you think that info in the dialog is not sufficient and it should be documented in the README feel free to provide a PR.

**Comment by testinggithub1222** [comment]
To me, I think Importing project is quite difficult especially, it shows only once after we select any of above setting. What if we select a wrong option, how can i undo or re-select? i figure out to delete **.lsp-session-v1** file in .emacs.d but it might not the best option because it might reset all the thing.

For the second point, I think if you put instruction how to use it, then it would be better because they know how to do it properly so we, the new user, don't need to figure out what is going on, why it work or why it doesn't work and what's should be the output after doing it so we can identify that this point is goes wrong. For example, first install lsp-mode, lsp-java... then lsp-java will download the file to .emacs.d dir so make sure that file exist (or we can alert if this file is not exist in the user dir) then open project any file in the project so lsp will prompt to import project. In short, step by step explanation is good.

**Comment by testinggithub1222** [comment]
By the way, I have tested it on my other computer and got some error after import the project. First, I download needed package and then it download all the jdt file by it self to the dir and i don't have to manually run sh mvnw....command and then i open the the project file and import the project and then i got some error as shown below:

```
LSP :: Connected to [jdtls:31607 status:starting].
File mode specification error: (void-function lsp-java-enable)
which-func-ff-hook error: (error "No workspace could handle textDocument/documentSymbol")
f-exists?: Wrong type argument: stringp, t
```

Not sure if something goes wrong.  I have tried to run sh mvnw... manually but still doesn't work.

**Comment by yyoncho** [comment]
Please make sure that you have read all of the documentation before complaining it has missing parts.

> If you open a file from the project for the first time you will be prompted the project. Once the project is imported project root is saved in lsp-session file and it will be loaded the next time you start Emacs so you no longer will be asked for a project root when you open a file from that project. Later if you want to change the project root you may use lsp-workspace-folder-remove to remove the project and call lsp-workspace-folder-add to add the root.


> Not sure if something goes wrong. I have tried to run sh mvnw... manually but still doesn't work.

Please read carefully the bug report template and populate **all** the sections. And although I have already told you to to make sure you are reproducing the bugs with the configuration from the getting started section you are still using your **wrong** **stale** configuration which uses `lsp-java-enable`  deprecated and deleted 4 months ago.

I am closing the bug, you may reopen it after providing the proper set of information needed in order to reproduce and fix the problem.

**Comment by testinggithub1222** [comment]
well i think it's too bad. if i know how to do it, then i would but i dont know what is going on too. Being a developer to develop something you should understand the difficulty the user use which is UX. Your can develop it, you can use it while other People may not able to use it.
