### ISSUE TITLE
Allow jumping into any class definition in the class path.

### ISSUE THREAD

**Issue by iocanel** [emacs-lsp/lsp-java#107]
Currently, one can visit the defintiion of class defined in a dependency, with the use of 
`lsp-goto-type-definition`. While this works very well, there are case when you want to visit class that is not currently referenced in the code, but is present in the class path.

It would be nice if there was a way to do that. Ideally, using completing read with fuzzy support on the fullyqualified name of the class or something like it.

IntelliJ users would recognize this feature is the functionality provided by `CTRL+N`.

**Comment by yyoncho** [comment]
you could use `xref-apropos` or https://github.com/emacs-lsp/helm-lsp if you want on the fly filtering.
