### ISSUE TITLE
lsp-java-server-update fails to download spring boot extension

### ISSUE THREAD

**Issue by mahinshaw** [emacs-lsp/lsp-java#108]
**Describe the bug**
When the maven script runs, and pulls the `{elided_for_brevity}Pivotal/vsextensions/vscode-spring-boot/1.3.0/vspackage`, which is outputed to `vscode-extension.zip`, the file fails to unzip. This is because the output file is a json response containing the following:

```json
{
    "eventId": 3000,
    "errorCode": 0,
    "typeKey": "RequestBlockedException",
    "typeName": "Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server",
    "message": "Anonymous usage from IP address 75.100.XXX.XXX has exceeded our rate limits and is being blocked. Anonymous access from this IP address will be unblocked within the next 1 minute. You can also consider logging in to get unblocked. Logged in users have higher limits. Learn more: https://go.microsoft.com/fwlink/?LinkId=823950.",
    "innerException": null,
    "$id": "1"
}
```

This issue is because i'm getting rate limited by MS. However, when I hit this endpoint directly via the browser, the download pulls the vsix file as expected. The anonymous usage message is somewhat concerning, and may be related to http headers that normally get propogated via a browser environment, but that conjecture is completely speculative.

I will continue to dig in as I can to see if I can get more information.

for completeness, here is the Maven install output:

```
--2019-02-28 09:07:00--  https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.4.0/maven-wrapper-0.4.0.jar
Resolving repo.maven.apache.org (repo.maven.apache.org)... 151.101.52.215
Connecting to repo.maven.apache.org (repo.maven.apache.org)|151.101.52.215|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48336 (47K) [application/java-archive]
Saving to: ‘/private/var/folders/0g/7d_x40456x910qs5lndrsvxh1wxnbm/T/lsp-java-install/.mvn/wrapper/maven-wrapper.jar’

     0K .......... .......... .......... .......... .......   100% 1.80M=0.03s

2019-02-28 09:07:00 (1.80 MB/s) - ‘/private/var/folders/0g/7d_x40456x910qs5lndrsvxh1wxnbm/T/lsp-java-install/.mvn/wrapper/maven-wrapper.jar’ saved [48336/48336]

[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------------< lsp-java:lsp-java >--------------------------
[INFO] Building lsp-java 1.0.0-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ lsp-java ---
[INFO] 
[INFO] --- download-maven-plugin:1.3.0:wget (download-che) @ lsp-java ---
[INFO] Got from cache: /Users/mhinshaw/.m2/repository/.cache/download-maven-plugin/che-jdt-language-server-latest.tar.gz_227786bc5f7f4578c50b0ab3ac10b7fd
[INFO] 
[INFO] --- download-maven-plugin:1.3.0:wget (download-vscode) @ lsp-java ---
[INFO] Got from cache: /Users/mhinshaw/.m2/repository/.cache/download-maven-plugin/vscode-extension.zip_3698842ee9745c613f2c386ba0429106
[INFO] 
[INFO] --- maven-antrun-plugin:1.6:run (prepare) @ lsp-java ---
[WARNING] Parameter tasks is deprecated, use target instead
[INFO] Executing tasks

main:
    [untar] Expanding: /private/var/folders/0g/7d_x40456x910qs5lndrsvxh1wxnbm/T/lsp-java-install/target/che-jdt-language-server-latest.tar.gz into /Users/mhinshaw/.emacs.d/var/lsp-java/server
    [unzip] Expanding: /private/var/folders/0g/7d_x40456x910qs5lndrsvxh1wxnbm/T/lsp-java-install/target/vscode-extension.zip into /private/var/folders/0g/7d_x40456x910qs5lndrsvxh1wxnbm/T/lsp-java-install/target/vscode-extension-extracted
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.219 s
[INFO] Finished at: 2019-02-28T09:07:05-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:run (prepare) on project lsp-java: An Ant BuildException has occured: Error while expanding /private/var/folders/0g/7d_x40456x910qs5lndrsvxh1wxnbm/T/lsp-java-install/target/vscode-extension.zip
[ERROR] java.io.IOException: Negative seek offset
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by yyoncho** [comment]
Hm, I guess we need to host it somewhere and avoid using marketplace. I asked spring boot team to provide a download location but unfortunately, this wasn't in their plans...

**Comment by mahinshaw** [comment]
Since it's pinned to a version, is it worth putting that version in the install directory in this repo?

**Comment by yyoncho** [comment]
I think this will cause melpa to download the binaries (it will slow it down). I read somewhere having binaries in the repo is not a good idea. We may use https://github.com/emacs-lsp/lsp-java/releases .

**Comment by mahinshaw** [comment]
Curious, there is already a jar in the the install directory for the maven wrapper, which is effectively a binary too.

**Comment by yyoncho** [comment]
@mahinshaw there is no jar - https://github.com/emacs-lsp/lsp-java/tree/master/install/.mvn/wrapper . It is downloaded by the mvnw.

**Comment by 007kevin** [comment]
@mahinshaw mentioned you can download the vsix file directly. Is there a workaround to continue with the build by manually downloading that file?

**Comment by mahinshaw** [comment]
@yyoncho Woops, turns out `.java` != `jar`, and I still have to learn how to read. Sounds like your idea of using releases is valid. Would you just add a separate asset to the list in that case?

**Comment by yyoncho** [comment]
> @mahinshaw mentioned you can download the vsix file directly. Is there a workaround to continue with the build by manually downloading that file?

Do you have the same problem? In general, you may comment on the vsix related sections in the pom.xml, download the vsix file manually and place the jars in the proper places.

**Comment by yyoncho** [comment]
Pushed https://github.com/emacs-lsp/lsp-java/commit/b3c4cc7a1903546be70e5e7893c044b91df76f59 @mahinshaw  can you retest?

**Comment by mahinshaw** [comment]
Works! Thanks @yyoncho

**Comment by yyoncho** [comment]
@mahinshaw you welcome. In case you are spring boot user we will be happy to receive feedback for its support before we do the 2.1 release.

**Comment by mahinshaw** [comment]
I'm not a spring boot user. I do have some code deployed with spring boot, but in most cases, I avoid spring. If I get back into that code base at any point though, I will let you know how the tooling works.

**Comment by 007kevin** [comment]
> > @mahinshaw mentioned you can download the vsix file directly. Is there a workaround to continue with the build by manually downloading that file?
> 
> Do you have the same problem? In general, you may comment on the vsix related sections in the pom.xml, download the vsix file manually and place the jars in the proper places.

Yes I had the same problem, but with the fix provided, I can build successfully. Perhaps because I was behind corporate proxies, the marketplace was denying my requests.

Thanks for the fix!
