### ISSUE TITLE
[Feature request] Add document popup support?

### ISSUE THREAD

**Issue by stardiviner** [emacs-lsp/lsp-java#109]
Can `lsp-java` add support for document popup like other languages? So that user can query doc when selecting around completion candidates.

Thanks for your work as always.

**Comment by yyoncho** [comment]
It should be present (if I had understood you correctly) - in bare company - press C-h

You may check out https://github.com/expez/company-quickhelp or https://github.com/sebastiencs/company-box too.

**Comment by stardiviner** [comment]
I found it. Thanks.

**Comment by yyoncho** [comment]
@stardiviner you may be interested https://github.com/tigersoldier/company-lsp/pull/91
