### ISSUE TITLE
Code actions without lsp-ui-sideline

### ISSUE THREAD

**Issue by skybert** [emacs-lsp/lsp-java#110]
**Describe the bug**
The code actions suggested through `lsp-ui-sideline-mode` are great. However, I don't use the sideline mode as IMHO it clutters up the interface and doesn't work well when having vertically split window with two or more buffers next to eachother.

I would therefore be great if code action suggestions would be available in an additional place, e.g. the auto complete menu (`emacs-eclim` has this, a short cut brings up a popup/auto complete menu with the code actions).

**Expected behavior**
Possible to view and apply code actions without the sideline mode and using only the keyboard.

**Comment by yyoncho** [comment]
`lsp-execute-code-action` ?

**Comment by skybert** [comment]
Awesome, thanks @yyoncho. 

I don't get the same options as `lsp-ui-sideline-mode` gives me, though. 

e.g. if my pointer is on `pTransaction` in the argument list to `create(...)` below, `lsp-ui-sideline-mode` gives me `Extract to method` whereas `lsp-execute-code-action` gives me:
`Extract to local variable` and `Extract to local variable (replace all occurrences)`
```
      long id = create(
          pTransaction,
          INSERT_SQL,
          pFoo,
          new FooMapper());
      reference.set(getFooByInternalId(pTransaction, id));
    });
```

**Comment by yyoncho** [comment]
the default behavior of lsp-ui is buggy, refer to lsp-java faq.

**Comment by yyoncho** [comment]
> lsp-ui does not display all of the actions on the current point(e. g "Extract constant")? LSP UI by default sends current line bounds for action region which breaks forces JDT server to return only "Extract method action."
> 
> (setq lsp-ui-sideline-update-mode 'point)
