### ISSUE TITLE
Is smart completion support built in?

### ISSUE THREAD

**Issue by xqliu** [emacs-lsp/lsp-java#112]
Dear,

Is smart completion which only pop up candidates which valid on current point(based on current context) supported?

like the follow code

```
String str = "origin";
int intVal = 2;
String intStr = "smile"
str.replace(i ---> here it would be better to only popup intStr rather than intVal
```

Above is a simple example regarding smart completion, 

Generally I found that's quite handy and useful when writing code, is it possible on lsp-java?

Thanks.

**Comment by yyoncho** [comment]
@xqliu it is not supported by jdt language server. You may file a feature request in its [REPO](https://github.com/eclipse/eclipse.jdt.ls).

**Comment by xqliu** [comment]
Found this ticket which is related

https://github.com/eclipse/eclipse.jdt.ls/issues/232

Will continue to keep an eye on that, thanks @yyoncho
