### ISSUE TITLE
Request ability to read  source code of library and go to source

### ISSUE THREAD

**Issue by fetatefog** [emacs-lsp/lsp-java#120]
After testing lsp-java for a little while, found that i could not go to library class file or view source code of the library that I put in my gradle or pom file. More importantly, i saw that in eclipse and as well as vsCode, we could debug through this source file too. I think this feature is really important to java developer.

**Comment by yyoncho** [comment]
This functionality is present(xref-find-definition) so please describe what are the exact steps that you are trying to do, what commands you are calling, minimal reproducer, logs from client-server communication and so on(refer to the bug template). Reopen after providing the needed info.

**Comment by fetatefog** [comment]
Actually this is what i need, xref-find-definition. But you should also mention this on github main page too because not all people know this feature existed yet.

**Comment by yyoncho** [comment]
It **is** mentioned in the README:

![Selection_122](https://user-images.githubusercontent.com/13259670/55666493-59e42100-5858-11e9-820c-093eb893fd02.png)
