### ISSUE TITLE
Modules that are only available in maven profiles are not recognized.

### ISSUE THREAD

**Issue by iocanel** [emacs-lsp/lsp-java#125]
**Describe the bug**
I have a multi-module maven project.
Some of the modules are not build by default, but are only build if you explicitly enable some profiles (e.g. -Pwith-examples). These modules don't seem to be recognized by lsp-java (are treated like java files not belonging to a workspace).

**Note**
Before logging the bug please make sure that the issue is reproducible with latest melpa packages and it is reproducible with the clean config(the config from the getting started page.

**To Reproduce**
Clone https://github.com/ap4k/ap4k and open any of the examples.

**Expected behavior**
These modules should be treated like regular modules, or it should be possible to select if I want them included or excluded from the workspace.

**Comment by yyoncho** [comment]
Sound like JDT LS issue (cc @gorkem @fbricon). Before digging into the issue, did you try to add explicitly add the module root with lsp-workspace-folders-add?

**Comment by iocanel** [comment]
@yyoncho no I haven't. I will try it out and let you know.

**Comment by iocanel** [comment]
@yyoncho: I am closing the issue for now as I can no longer reproduce it.
