### ISSUE TITLE
Can "lsp-java-autobuild-enabled" be quiet?

### ISSUE THREAD

**Issue by mrbig033** [emacs-lsp/lsp-java#126]
- Manjaro Stable
- GNU Emacs 27.0.50
- lsp-java 20190421.1928

It keeps saying it's building or refreshing the workspace at every keystroke, even with `(setq lsp-inhibit-message t)`

**Comment by yyoncho** [comment]
Try using lsp-java-progress-reports-enabled. If it does not work `(setq global-mode-string (-remove-item (list '(t lsp-java-progress-string)) global-mode-string ))` will do.

**Comment by mrbig033** [comment]
Second option did it, thanks?
