### ISSUE TITLE
Working with modules inside a project

### ISSUE THREAD

**Issue by Nollo** [emacs-lsp/lsp-java#127]
Hello,

I have a project `back` composed of three modules:
- `api`
- `batch`
- `core`

`api` and `batch` can be launched separately but use packages from `core`.

For example, when I open a file in `api`, it doesn't recognize imports from `core`. Moreover **projectile** set `api` as project root, so it might be an issue with **projectile** more than **lsp**

Currently I use Intellij IDEA for this project and it works perfectly.

**Comment by yyoncho** [comment]
Are these maven modules?

**Comment by Nollo** [comment]
Yes, they all have a `pom.xml`

**Comment by yyoncho** [comment]
Hm, do they have a parent pom located in back?

**Comment by yyoncho** [comment]
> Moreover projectile set api as project root, so it might be an issue with projectile more than lsp

Actually, I just got what your issue is. 

1. Start clean - do lsp-workspace-folder-remove and delete the api root.
2. Reopen the java file and from the menu select the option about interactive root selection
3. Select `back` root.

**Comment by Nollo** [comment]
All modules have `pom.xml`, and I think intellij idea adds `.classpath`, `.factorypath`, `.project` files into modules.

In `back` root, I have a `pom.xml`.

I cleaned workspaces folder but when I reopen the java file, I don't have a prompt to select a root

**Comment by yyoncho** [comment]
Is it possible that you have set lsp-auto-guess-root  to t?

**Comment by Nollo** [comment]
You were right! it was set to auto-guess.

I set it to `nil`, and I added `back` as root of the project.

It works like a charm! Thanks for your support :D
