### ISSUE TITLE
test-runner path is incorrect in Spacemacs

### ISSUE THREAD

**Issue by Habens** [emacs-lsp/lsp-java#130]
**Describe the bug**
`dap-java-run-test-method` run the JUnit test with wrong `test-runner` path

**To Reproduce**
1. add `lsp`, `dap` layers and `(java :variables java-backend 'lsp)` in `.spacemacs.d/init.el`
2. open a java test file
3. run `dap-java-run-test-method`

**Screenshots**
![image](https://user-images.githubusercontent.com/6989183/57502736-a28f6e00-731f-11e9-8020-4c4993769598.png)

**Logs**
> Error: Unable to access jarfile /path/to/.emacs.d/eclipse.jdt.ls/test-runner/junit-platform-console-standalone.jar

**Others**
I checked the .emacs.d folder. There is not
> /path/to/.emacs.d/eclipse.jdt.ls/test-runner

but  
> /path/to/.emacs.d/eclipse.jdt.ls/**_`server`_**/test-runner

The `dap-java-run-test-method` works fine if copyed `test-runner` from `eclipse.jdt.ls/server/` to `eclipes.jdt.ls/`,

**Comment by yyoncho** [comment]
Can you try updating to the latest versions of lsp-java/dap-mode/lsp-mode, and then call lsp-java-update-server?

**Comment by Habens** [comment]
On Mac and Linux, call lsp-java-update-server with the latest version of lsp-mode fixing this issue.

But below error haapened on Windows 10, run emacs as Administrator got the same result:
> helm-M-x: Removing old name: Permission denied, /path/to/.emacs.d/eclipse.jdt.ls/server/bundles/java.debug.plugin.jar

**Comment by yyoncho** [comment]
> But below error haapened on Windows 10, run emacs as Administrator got the same result:

It is local permission related problem on your PR and you could delete it manually.

**Comment by Habens** [comment]
I'm not a senior emacs user, maybe this permission is not related lsp-java.

if the permission problem is a generalized problem, not my  `local` problem, `delete it manually` might not be a good practice.
