### ISSUE TITLE
Some publishDiagnostics notifications aren't rendered

### ISSUE THREAD

**Issue by lmmarsano** [emacs-lsp/lsp-java#133]
**Describe the bug**
Despite the client logging notifications from the server, null analysis diagnostics aren't rendering.
The same diagnostics render in VS Code.

**To Reproduce**
Clone [lmmarsano/java-test][test] and [follow instructions on the readme.md][test].

**Expected behavior**
Diagnostics rendering as buffer annotations like other warnings/errors

**Logs**
In [readme.md][test], the `*lsp-log: jdtls:`n`*` shows

```
[Trace - 03:35:12 PM]
Received notification 'textDocument/publishDiagnostics'.

Params: 
{
  "diagnostics": [
    {
      "message": "Null type safety (type annotations): The expression of type 'String' needs unchecked conversion to conform to '@NonNull String'",
      "source": "Java",
      "code": "536871867",
      "severity": 2,
      "range": {
        "end": {
          "character": 31,
          "line": 11
        },
        "start": {
          "character": 15,
          "line": 11
        }
      }
    },
    {
      "message": "Null type mismatch: required '@NonNull String' but the provided value is null",
      "source": "Java",
      "code": "16778126",
      "severity": 1,
      "range": {
        "end": {
          "character": 39,
          "line": 15
        },
        "start": {
          "character": 35,
          "line": 15
        }
      }
    }
  ],
  "uri": "file:///mnt/c/Users/luism/source/repos/java-demo/src/main/java/demo/App.java"
}
```

though the `*lsp-log*` buffer doesn't show an expected line for `textDocument/publishDiagnostics`.

I try to fix this myself by instrumenting `lsp--parser-on-message` for edebug, but can't get very far: Emacs breaks into edebug, which then breaks into an additional debug I didn't ask for, messages stack up, and I can't get back into edebug to follow the right message. Any message breaks into edebug despite setting edebug to stop only at breakpoints and setting a conditional breakpoint on the message.
Could you suggest a better approach?

[test]: /lmmarsano/java-test

**Comment by yyoncho** [comment]
What do you use? Flymake or flycheck? (I would say that flycheck is more reliable)

**Comment by yyoncho** [comment]
![emacs-27 0 50@kyoncho-H87-D3H_137](https://user-images.githubusercontent.com/13259670/57645468-fd96be80-75c6-11e9-9f9f-905b367cbdae.png)


It works fine on my machine. Do you have flycheck installed? Or if you want to use flymake you should be using emacs > 26.0

**Comment by lmmarsano** [comment]
Thanks.
Definitely appears under flycheck: I was using flymake with emacs 26.1, though I have flycheck installed. Since emacs is new enough, is there more to setting up flymake?

From the [configuration guide][vanilla], I understand `lsp-ui` integrates with `flycheck` and "lsp-mode will automatically detect and configure lsp-ui and company-lsp".
I must have misunderstood that: I still have to configure flycheck?

[vanilla]: https://github.com/emacs-lsp/lsp-mode#vanilla-emacs

**Comment by yyoncho** [comment]
You should have lsp-prefer-flymake equal to t and that should be enough. You could inspect the configured flymake configured backends via flymake-running-backends. Also you could check the whether there are reported diagnostics via flymake-show-diagnostics-buffer.

**Comment by yyoncho** [comment]
I tested the minimal  configuration:

https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el (you have to add lsp-java to the list of the packages to install).

and then:

```
emacs26  -q -l ~/Sources/lsp/lsp-mode/scripts/lsp-start-plain.el  ~/.temp/java-test/src/main/java/test/App.java
```

and everything works fine after calling `lsp` (ignoring the initial flymake errors).

**Comment by lmmarsano** [comment]
That clears it up: the default value for `lsp-prefer-flymake` is `t`, so I wasn't getting flycheck.

I tried loading the minimal configuration, ignoring the error, and invoking `lsp`.
However, the annotations still don't appear.
Upgrading from built-in `flymake` (v0.3) to the one on ELPA (v1.0.6) doesn't help.

However, flycheck works well.
Though I don't need flymake, we can continue looking into this if it matters.
Otherwise, I'm fine with closing the issue.

**Comment by yyoncho** [comment]
Imo based on the fact that it works with clean setup on my machine and it is no longer blocker for you we are safe to close it. There is plenty of work that we have to do in lsp-mode / lsp-java regarding better java support so it seems to me that investing more time in this issue won't pay off.
