### ISSUE TITLE
Question: How to handle 3rd party applications editing configuration files (e.g. pom.xml, build.gradle etc)

### ISSUE THREAD

**Issue by iocanel** [emacs-lsp/lsp-java#135]
I have a case where an external plguin performs changes to the my pom.xml.
In this cases, it seems that lsp doesn't see the changes right away and I need to manually refresh lsp. What's the suggested way of forcing lsp to reread those files?

Can it be done automatically?

**Comment by yyoncho** [comment]
@iocanel this should work out of the box with latest lsp-mode and lsp-java via file notifications. It may be forced with `M-x` `lsp-java-update-project-configuration`

**Comment by iocanel** [comment]
I'll pull the latest of both and try again.

Using `lsp-java-update-project-configuration` is a viable option when editing the pom.xml by hand (as it needs to be called from the pom buffer. But when external tools perform the change is a little bit trickier, as I first need to find and open the pom.

**Comment by yyoncho** [comment]
Seems like there is nothing to do on this one. Reopen if you disagree.
