### ISSUE TITLE
Internal server error during initialization

### ISSUE THREAD

**Issue by sriramkswamy** [emacs-lsp/lsp-java#14]
I have the following java file -

```java
public class UnionFind {
    public static void main(String[] args) {
        System.out.println("Hello world");
    }
}
```
When I try to open it after setting up `lsp-mode` and `lsp-java` according to the readme, I get the following message -

```
using config for config_mac
Nov 26, 2017 1:26:34 AM >> initialize
Nov 26, 2017 1:26:34 AM Initializing Java Language Server 0.9.0.201711260243
Error from the Language Server: Internal error. (Internal Error)
File mode specification error: (lsp-empty-response-error initialize)
```

The `*lsp-java stderr*` buffer is blank. Using Emacs version 27.0.5 on Mac OS X Sierra via Homebrew.  Problem occurs with both latest server and the 201710161512 version installed in the default path.

**Comment by yyoncho** [comment]
Can you try with the latest jdt/lsp-java/lsp-mode?

**Comment by yyoncho** [comment]
Marking as closed due to inactivity. Please reopen if you are able to reproduce the issue.
