### ISSUE TITLE
Question: How to enable lsp-java over tramp?

### ISSUE THREAD

**Issue by 007kevin** [emacs-lsp/lsp-java#149]
The example on [lsp-mode](https://github.com/emacs-lsp/lsp-mode#how-does-it-work-1) gives the following example for enabling lsp over tramp:

```
(lsp-register-client
 (make-lsp-client :new-connection (lsp-tramp-connection "binary-or-full-path")
                  :major-modes '(python-mode)
                  :remote? t
                  :server-id 'pyls-remote))
```
Is there a working example with a remotely installed java eclipse.jdt.ls server?

Btw, great job! Much appreciated.

**Comment by arichiardi** [comment]
@007kevin Did you succeed with the above command? I think it works for me for python.

**Comment by yyoncho** [comment]
making lsp-java to work over tramp is a big task - there are a lot of paths that have to be translated to be remote. Also, there is a lot of code that assumes that there is only one instance of 'jdtls server. One should start with lsp-register-client call and gradually migrate each of the local paths to be remote.

**Comment by arichiardi** [comment]
I see, thank you, I somehow assumed that most of the path translation would be handled by Emacs. Can you give me an example of local path?

**Comment by yyoncho** [comment]
@arichiardi lsp-mode will perform the path translation when you do normal lsp stuff like go to definition, find references, etc. But on top of what lsp protocol has jdt-ls server has some requirements - for example, there is custom initialization setting lsp-java-workspace-dir. There is no way lsp-mode to know that it shoul translate that. Also, when you go to reference which is in jar lsp-java calls the server and then stores the file in lsp-java-workspace-cache - this should be also fixed to work with tramp.

**Comment by arichiardi** [comment]
So she first is a defcustom, which is nice, the latter I will have to check. I will report my progress here.

**Comment by arichiardi** [comment]
Nope it cannot work with the `defcustom`s set to `/ssh:....` because they are passed directly to the `mvnw`, like:

```
mvnw -Djdt.js.server.root=/ssh:my-box/....
```
And of course Maven does not know what `/ssh:` is.

**Comment by arichiardi** [comment]
So what basically need to be executed remotely is `mvnw`, the paths will be at that point valid against the remote machine.

@yyoncho does this makes sense? Any hint if I wanted to attempt that?

**Comment by yyoncho** [comment]
@arichiardi I suggest not spending effort on implementing the automatic download over tramp in the initial implementation. After all, once you have them locally you could copy the installation on the remote server.

**Comment by arichiardi** [comment]
Yes that was the plan I had in mind as well.

**Comment by Ailrun** [comment]
Does it work now, or is there a workaround?

**Comment by jablub** [comment]
Did anyone ever get lsp-java working over tramp?

**Comment by thkoch2001** [comment]
I was about to open an issue that lsp-java does not work for me over tramp when I found this one. So as of today it apparently still does not work.

I see that this issue is closed and I don't have the permission to reopen it. Thus I'll open a new one and point it to this thread.
