### ISSUE TITLE
Unable to make lsp--send-request-async return data in callback

### ISSUE THREAD

**Issue by bizzyman** [emacs-lsp/lsp-java#15]
With the following function:
```
(defun simple-lsp-hover-req-async ()
  (lsp--send-request-async (lsp--make-request
                           "textDocument/hover"
                           `(:textDocument (:uri "file:///usr/lib/erlang/lib/jinterface-1.8/java_src/com/ericsson/otp/erlang/AbstractConnection.java")
                                           :position
                                           (:line
                                            147
                                            :character 30)))
                           (lambda (x) (message "HELLO"))
                          ))
```
I am unable to get the lambda callback to fire and show "HELLO" into the echo are or Messages buffer. 
I have tried same function in a python-lsp project and the callback does fire and I am able to see "HELLO" message. The sync version of this function works as expected.

When lsp-print-io is set to t, I see that the server is generating this:
`Output from language server: {"jsonrpc":"2.0","id":"5","result":{"contents":[{"language":"java","value":"void java.io.PrintStream.println(char[] x)"}]}}`
However i get nothing back in the callback, and when lsp-print-io is set to nil I get nothing back.

**Comment by vibhavp** [comment]
Is `inhibit-message` or `lsp-inhibit-message` set to `t`, by any chance? Also, you should probably shift this issue to the `lsp-mode` tracker.

**Comment by bizzyman** [comment]
This issue was moved to emacs-lsp/lsp-mode#263
