### ISSUE TITLE
Unable to disable file watches via .dir-locals

### ISSUE THREAD

**Issue by scjung** [emacs-lsp/lsp-java#157]
I have a workspace containing a lot files. To avoid performance issues, I setted `lsp-enable-file-watchers` to `nil` in `.dir-locals.el` like the below.

```elisp
((nil . ((lsp-enable-file-watchers . nil))))
```

I checked that `lsp-enable-file-watchers` has been setted to `nil` properly after visiting a file in the workspace.

But whenever visiting a file, `lsp-mode` still warns me that there are too many files like the below.

```
There are 1289 files in folder ...WORKSPACE... and watching the repo which may slow Emacs down. To configure:
1. Use `lsp-enable-file-watchers' to disable file watchers globally or for the project(via .dir-local).
2. Increase/set to nil `lsp-file-watch-threshold' to remove the warning.
```

For debugging, I inserted the simple logging statement into `lsp-watch-root-folder` of `lsp-mode`.

```elisp
(defun lsp-watch-root-folder (dir callback &optional watch warn-big-repo?)
  "Create recursive file notificaton watch in DIR...."
(lsp-log "!!!!! %s : %s" (buffer-file-name) lsp-enable-file-watchers)   ;;; <--- debug
  (let* ((dir (if (f-symlink? dir)
                  (file-truename dir)
                dir))
```

Then I encountered log messages like the below.

```
Sep 15, 2019, 5:18:13 PM >> registerFeature 'workspace/didChangeWatchedFiles'
!!!!! nil : t
Creating watch for ...WORKSPACE...
```

It looks like that `:initialized-fn` callback of `lsp-java` is called outside the visiting file. Is this a real bug? is there any workaround for this situation (without disabling file watches globally)?

I'm using lsp-mode-20190914.1642 and lsp-java-20190912.450.

**Comment by yyoncho** [comment]
I did a change that disables the filewatches in client capabilities instead of skipping the watch file requests when the server requests them.

**Comment by bb4242** [comment]
I think that change (https://github.com/emacs-lsp/lsp-mode/commit/67745ab4abd28fb077cd51eae311d13c08028463) is causing some trouble with ccls (see 
https://github.com/MaskRay/ccls/issues/482).  I'm not sure whether it's better to fix this in lsp-mode or in ccls, though.

**Comment by yyoncho** [comment]
@bb4242 fixed with https://github.com/emacs-lsp/lsp-mode/commit/7c757cfac4aeede44773bfd65c5cd27ab8444ca9

**Comment by bb4242** [comment]
Thanks @yyoncho !
