### ISSUE TITLE
Feature request: find a class in a classpath

### ISSUE THREAD

**Issue by yauhen-l** [emacs-lsp/lsp-java#160]
During development I use a lot Eclipse's function "Open Type" (`Ctrl + Shift + T`), so I am able to search classes defined not only in a project but also in all dependencies.

**Comment by yyoncho** [comment]
Use xref-find-apropos or https://github.com/emacs-lsp/helm-lsp or https://github.com/emacs-lsp/lsp-ivy

**Comment by yauhen-l** [comment]
@yyoncho thank you, my bad. I obviously need to investigate documentation better.
There is also `lsp-ui-find-workspace-symbol`.
`helm-lsp` is not quite responsive for me, will try to tune it, maybe I need more memory for the JDT server.

**Comment by yyoncho** [comment]
@yauhen-l which version of emacs do you use? The json responses are very big and if you are not on emacs 27 compiled with native json support it will be slow on Emacs side.

**Comment by yauhen-l** [comment]
@yyoncho 
```
GNU Emacs 26.1 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.23.2) of 2018-08-13
```
This is a very nice insight!
