### ISSUE TITLE
Feature request: create a new class in a package

### ISSUE THREAD

**Issue by yauhen-l** [emacs-lsp/lsp-java#161]
If I need to create a new class, I usually do:
1. `C-x C-f` then specify new file location and name, i.e. `src/main/foo/bar/Foo.java`
1. Write in a header of the file `package foo.bar;`
1. Define a class with `public class Foo { }`

I find steps 2 and 3 very annoying since I need to remember and type package and class name properly.

Maybe I miss some already existing functionality that can speed up the process of creating new classes?

**Comment by yyoncho** [comment]
Open the new file type `class` and select the snippet from the company menu.
