### ISSUE TITLE
Importing irrelevant projects

### ISSUE THREAD

**Issue by iocanel** [emacs-lsp/lsp-java#162]
**Describe the bug**

With emacs and language server **not running**, I completely delete `lsp-java-workspace-dir` and `lsp-java-workspace-cache-dir`.

Then I start emacs and open a java project.

In the *lsp-log* I see that it imports every single java project I'ever opened with emacs.

**Expected behavior**
I would expect that since the workspace is wiped I should only see it importing the current project. It seems like these projects are also referenced from elsewhere too.

**Logs**

    69% Starting Java Language Server - Importing Maven project(s) - project quarkus- build-parent[Starting]
    69% Starting Java Language Server - Importing Maven project(s) - project quarkus-keycloak-deployment[Starting]
    69% Starting Java Language Server - Importing Maven project(s) - project quarkus-smallrye-opentracing-deployment[Starting]
    69% Starting Java Language Server - Importing Maven project(s) - project quarkus-artemis-core-deployment[Starting]
    69% Starting Java Language Server - Importing Maven project(s) - project quarkus-elytron-security-deployment[Starting]
    69% Starting Java Language Server - Importing Maven project(s) - project quarkus-integration-test-kotlin[Starting]

    83% Starting Java Language Server - Importing Maven project(s) - project openshift-client[Starting]
    83% Starting Java Language Server - Importing Maven project(s) - project openshift-server-mock[Starting]
    83% Starting Java Language Server - Importing Maven project(s) - project kubernetes-test[Starting]
    83% Starting Java Language Server - Importing Maven project(s) - project kubernetes-itests[Starting]
    83% Starting Java Language Server - Importing Maven project(s) - project servicecatalog-server-mock[Starting]
    83% Starting Java Language Server - Importing Maven project(s) - project servicecatalog-tests[Starting]

**Comment by yyoncho** [comment]
The only file that you have to delete is `lsp-session-file`.
