### ISSUE TITLE
Is there any way to set additional formatting options?

### ISSUE THREAD

**Issue by rrudakov** [emacs-lsp/lsp-java#163]
When I run `lsp-format-buffer` command client send next request to server:
```
[Trace - 02:47:33 PM] Sending request 'textDocument/formatting - (821)'.
Params: {
  "textDocument": {
    "uri": "file:///home/.../FileName.java"
  },
  "options": {
    "tabSize": 8,
    "insertSpaces": true
  }
}
```
As a result all code is indented with 8 spaces ignoring settings in `lsp-java-format-settings-url` file.

If I get it right in vscode we can customize this values and [lsp-server should support](https://github.com/eclipse/eclipse.jdt.ls/pull/640) it.

**Comment by yyoncho** [comment]
Tab size comes from `tab-width`, this is how jdtls works.

**Comment by rrudakov** [comment]
It wasn't obvious for me :) Thank you for help!

**Comment by yyoncho** [comment]
No worries,  you are not the first one asking that question. It is not that obvious.
