### ISSUE TITLE
`lsp-java--get-root` not used by `lsp--find-root-interactively`

### ISSUE THREAD

**Issue by joaocortes** [emacs-lsp/lsp-java#166]
I am using the configurations suggested in the README file.
When I first open a `java` file from some project not already on the workspace, `lsp-java--get-root` isn't used to find a candidate root for the project. Instead, `lsp--suggest-project-root` is called.
This seems sub ideal, given that `lsp-java--get-root` looks for a `pom.xml, .project, etc` and `lsp--suggest-project-root` only rely on feedback from `projectile` and `project`.

**Comment by yyoncho** [comment]
`lsp-java--get-root`  is a leftover from the legacy lsp implementation and it is not used at all. Note that lsp-java--get-root is not that "good" and does not offer the customization that projectile has. E. g. if you have multi-module project it will pick the child module (first pom.xml) while projectile will pick the correct one(the root pom.xml). If you want to use it for root suggestion you may configure it in `projectile-project-root-files-functions`.

**Comment by joaocortes** [comment]
Thanks again. I wasn't aware of the `projectile` abilities
