### ISSUE TITLE
Support for sbt builds

### ISSUE THREAD

**Issue by eikek** [emacs-lsp/lsp-java#172]
Hello,

we have a lot of projects using the playframework. We are using it with Java, but the build is defined in SBT. Would it be possible to support sbt next to maven and gradle? Or does it mean to use metals? Sorry if this is all obvious… I just started checking out lsp and lsp-java.

Thanks for `lsp-java`!

**Comment by yyoncho** [comment]
1. Check whether sbt could generate eclipse java project(.project).
2. Report it upstream in jdt-ls repo. lsp-java is only a frontend, the import logic is in the server.

I am closing based on 2.

**Comment by yyoncho** [comment]
See https://github.com/sbt/sbteclipse

**Comment by eikek** [comment]
@yyoncho  Thank you!
