### ISSUE TITLE
failed to call lsp-java-add-unimplemented-methods

### ISSUE THREAD

**Issue by thinkiny** [emacs-lsp/lsp-java#173]
*Backstrace*

Debugger entered--Lisp error: (void-function seq-first)
  seq-first([#<hash-table equal 2/65 0x55bbe501>])
  lsp-java--apply-workspace-edit(#<hash-table equal 3/65 0x55bbe4e1>)
  lsp--execute-command(#<hash-table equal 3/65 0x55bbe4e1>)
  lsp-execute-code-action(#<hash-table equal 4/65 0x55bbcaad>)
  lsp-java-execute-matching-action("Add unimplemented methods")
  lsp-java-add-unimplemented-methods()
  funcall-interactively(lsp-java-add-unimplemented-methods)
  call-interactively(lsp-java-add-unimplemented-methods nil nil)
  command-execute(lsp-java-add-unimplemented-methods)

;;missing func
(defun seq-first (sequence)
  "Return the first element of SEQUENCE."
  (seq-elt sequence 0))

**Comment by yyoncho** [comment]
It was renamed to `lsp-seq-first`. Unless you want to provide a PR I will fix it when I am on my dev PC.

**Comment by thinkiny** [comment]
not a big issue for now

**Comment by yyoncho** [comment]
fixed with 3a9890e5e4ff80cee508d99170297225a2e95d69
