### ISSUE TITLE
Java: The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files

### ISSUE THREAD

**Issue by skybert** [emacs-lsp/lsp-java#180]
**Describe the bug**
```
Java: The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files [16777540]
```
Similar errors for `java.util.Iterator` and `Override`, but funnily enough no other JDK classes. I've tried to remove:

```
~/.emacs.d/workspace 
~/.emacs.d/.lsp-session-v1 
~/.emacs.d/.dap-breakpoints 
~/.emacs.d/eclipse.jdt.ls/server
```
but the problem persists.

**To Reproduce**
I can reproduce it at will on my machine, but am pretty certain it's not something is evident everywhere.

**Versions**
- lsp-mode-20191127.2044
- lsp-ui-20191125.2102
- lsp-java-20191115.1712
- lsp-treemacs-20191121.1951
- company-lsp-20190612.1553
- GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-10-17

```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Debian-1deb10u1, mixed mode, sharing)
```

**Expected behavior**
No errors.

**Comment by yyoncho** [comment]
Can you provide the client-server logs? If there are no clues in it I don't think that we will be able to do anything on our side.

**Comment by skybert** [comment]
I believe I'm the one to blame. I accidentally, changed `lsp-java-java-path` to `lsp-java-path` when trying out OpenJDK again (https://gitlab.com/skybert/my-little-friends/commit/a000656dd6a67f98cc9cd12c79afd192d59830ad). 

I then hunted down the error and fixed it locally but never pushed my fix so that my other computers got the change. One of my computers therefore got inconsistent behaviour: whatever `java` was first in `PATH` when `emacs` was started, got precedence. :man_facepalming:  

Not to excuse my error, but it would benefit the user experience if there was a status page showing the runtime configuration like:
- JDK
- Maven version
- Workspace path
- Eclipse version?
Elpy has something like this and it makes it easier to sort out these problems IMHO.

**Comment by bitorhugo** [comment]
Just had a similar problem with lsp,
The problem was with lsp-workspaces. I had a bunch of old projects, some that were not on my local computer and for some reason the lsp-server was having a hard time differentiating from different work-spaces.

**Comment by skybert** [comment]
Thanks for sharing, @bitorhugo
