### ISSUE TITLE
M-x  lsp-java-spring-initializr   can't download zip file from https://start.spring.io/

### ISSUE THREAD

**Issue by rmbxz** [emacs-lsp/lsp-java#181]
**Describe the bug**
M-x lsp-java-spring-initializr can't download the zip file (project files) from https://start.spring.io/ 

**To Reproduce**
using  M-x lsp-java-spring-initializr many times will produce an empty downloaded zip files

**Expected behavior**
  (url-copy-file download-url temp-file t)  not works as  expected. 

**Logs**
Messages buffer :- 
the output error messages from  *Messages* buffer :-
Requesting spring initializr data...
Downloading template from https://start.spring.io/starter.zip?type=maven-project&language=java&groupId=com.example&artifactId=demo&packaging=jar&bootVersion=2.2.2.BUILD-SNAPSHOT&baseDir=demo&dependencies=web
Contacting host: start.spring.io:443
Wrote /tmp/spring-projectGkTmJA.zip
Archive:  /tmp/spring-projectGkTmJA.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/spring-projectGkTmJA.zip or
        /tmp/spring-projectGkTmJA.zip.zip, and cannot find /tmp/spring-projectGkTmJA.zip.ZIP, period.
Do you want to import the project? (y or n) y

**Logs**
 the temp-file  /tmp/spring-projectGkTmJA.zip have this error message :- 
`<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>cloudflare</center>
</body>
</html>
`

**system**
Linux Debian
Emacs GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11) 
lsp-java  Version: 2.0             20191115.1712 

**solution**
my solution is to substitute  url-copy-file function  by wget or curl shell command 
 
;;   (url-copy-file download-url temp-file t)

 (if (executable-find "wget")
 	(shell-command (format "wget     -O    %s     '%s'    " temp-file download-url))
    (if (executable-find "curl")
 	   (shell-command (format "curl     -o     %s       '%s'    " temp-file download-url))))

**Comment by yyoncho** [comment]
I am unable to reproduce using emacs27. I think it is an issue with https support in emacs on your side but I am not familiar with what should be checked. IMO using wget/curl if they are present is acceptable solution. Willing to open a PR?

**Comment by rmbxz** [comment]
;; i am trying this function at emacs versions  26.1, 26.2, 26.3 
(url-copy-file "https://start.spring.io/starter.zip?type=maven-project&language=java&groupId=com.example.hi&artifactId=demo&packaging=jar&bootVersion=2.2.2.BUILD-SNAPSHOT&baseDir=demo&dependencies=web"  "file01.zip" t) ;; C-x C-e

the result :
 (url-copy-file) not work     at GNU Emacs 26.1
 (url-copy-file) is  working  at GNU Emacs 26.2
 (url-copy-file) is  working  at GNU Emacs 26.3



;; (url-copy-file) not work
;; Emacs 26.1
(defun url-copy-file (url newname &optional ok-if-already-exists
			  _keep-time _preserve-uid-gid)



;; (url-copy-file) is working
;; Emacs 26.2
(defun url-copy-file (url newname &optional ok-if-already-exists
                          _keep-time _preserve-uid-gid _preserve-permissions)


;; (url-copy-file) is working
;; Emacs 26.3
(defun url-copy-file (url newname &optional ok-if-already-exists
                          _keep-time _preserve-uid-gid _preserve-permissions)

**Comment by rmbxz** [comment]
@yyoncho 
 thanks for your great works.
