### ISSUE TITLE
Code Completion inserting return type.

### ISSUE THREAD

**Issue by laep** [emacs-lsp/lsp-java#184]
When I' auto completing variables instead of adding: 
> **randomVariable**

It will add: 

> **randomVariable : int**

This happens for anything I try to auto complete.

For example if i try to auto complete the method: 

> **getClass()**

I will get:

> **getClass() : Class<?>**

Im doing this on a fresh installation using the config on the lsp-java readme

**Comment by yyoncho** [comment]
My guess is that yasnippet is not loaded, can you eval `(require 'yasnippet)` and check whether this will fix your issue?

**Comment by laep** [comment]
> My guess is that yasnippet is not loaded, can you eval `(require 'yasnippet)` and check whether this will fix your issue?

Tried that, i also have yas-global-mode 1, the error still occurs

**Comment by yyoncho** [comment]
@laep I tested the configuration from the readme in the https://github.com/emacs-lsp/lsp-docker/ and in works fine.

1. can you check Messages buffer for errors? 
2. Can you delete ~/.emacs.d/elpa and try again with the configuration from readme?
3. Which version of emacs do you use?

**Comment by laep** [comment]
> @laep I tested the configuration from the readme in the https://github.com/emacs-lsp/lsp-docker/ and in works fine.
> 
>     1. can you check Messages buffer for errors?
> 
>     2. Can you delete ~/.emacs.d/elpa and try again with the configuration from readme?
> 
>     3. Which version of emacs do you use?

I did several testing with my configurations and seems like evil-collection where having a problem. I was able to solve it by adding:

> :custom (evil-collection-company-use-tng nil)

**Comment by yyoncho** [comment]
company-tng is incompatible with company-lsp 

see https://github.com/company-mode/company-mode/issues/891

**Comment by laep** [comment]
Now its working properly.

Maybe you can help me with a separate issue.
Is it possible to have code actions as a drop down menu?
also `generate tostrings` and `generate constructors` only allow me to select one parameter

**Comment by yyoncho** [comment]
> Is it possible to have code actions as a drop down menu?

Dropdown like right click menu or like helm/ivy?

> also generate tostrings and generate constructors only allow me to select one parameter

It depends on what you are using(e. g. helm/ivy/vanilla), but you could select multiple elements.

E. g. in help you could use C-SPC to mark multiple entries M-M to mark all.

**Comment by laep** [comment]
> > Is it possible to have code actions as a drop down menu?
> 
> Dropdown like right click menu or like helm/ivy?

Right now i have to type `:lsp-execute-code-action` in evil mode o `M-x lsp-execute-code-action`
After typing that i have to type the code action i want to run.

By drop down i meant a simple dropdown menu like the completion one with all the code actions i can take. Maybe some keys that let me select the code actions on the sideline without using the mouse.

I also wouldn't mind if it was an helm like menu in the minibuffer

> 
> > also generate tostrings and generate constructors only allow me to select one parameter
> 
> It depends on what you are using(e. g. helm/ivy/vanilla), but you could select multiple elements.
> 
> E. g. in help you could use C-SPC to mark multiple entries M-M to mark all.

I am using Helm-lsp. Most code actions were complainning they couldnt find helm-map when i tried to use code actions. I assume helm is enforced even if documentation doesnt says anything about it.

I didn't know about C-SPC, seems now i can mark the arguments i want, its just annoying being forced to use the arrow keys. Is there any way to use evil keys? e.g: C-j and C-k to chose and v to mark them?

**Comment by yyoncho** [comment]
> Right now i have to type :lsp-execute-code-action in evil mode o M-x lsp-execute-code-action
After typing that i have to type the code action i want to run.

Enabling helm-mode will fix that.


> I didn't know about C-SPC, seems now i can mark the arguments i want, its just annoying being forced to use the arrow keys. Is there any way to use evil keys? e.g: C-j and C-k to chose and v to mark them?

```
(define-key helm-map (kbd "C-k") 'helm-previous-line)
(define-key helm-map (kbd "C-j") 'helm-next-line)
(define-key map (kbd "v")      'helm-toggle-visible-mark) ;; this will steal v key. 
```

**Comment by mangkoran** [comment]
> Now its working properly.
> 
> Maybe you can help me with a separate issue.
> Is it possible to have code actions as a drop down menu?
> also `generate tostrings` and `generate constructors` only allow me to select one parameter

I have the same problem. I dont know if I should open new issue or not. I am using `ivy`, and i want to use `lsp-code-action`'s `generate constructor`. But it only allows me to select one paramater. `C-SPC` not working with `ivy`

**Comment by dakra** [comment]
Ivy has multi-select too but probably way less used than in helm.
You can press C-o and then m to mark all the candidates
you want. Or if you want all candidates selected you can
press C-o t.

**Comment by mangkoran** [comment]
Thank you. I can confirm this. What should I do is calling `hydra-ivy/body` (as you said `C-o` in vanilla, in my Doom it is `M-o`).

**Comment by Ma-Nu-El** [comment]
>  in vanilla, in my Doom it is `M-o`).

Yes! Thank you very much!
