### ISSUE TITLE
Rename doesn't work

### ISSUE THREAD

**Issue by rrudakov** [emacs-lsp/lsp-java#185]
**Describe the bug**
When I execute `lsp-rename` and type new name I got next message:
```
lsp-rename: Capability not supported by the language server: "renameProvider"
```

**Logs**
There is nothing in logs when I try to execute this command.

Edit:
I use latest lsp-mode and lsp-java from MELPA. 
eclipse.jdt.ls - latest shapshot. 
emacs-version: GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.3, Xaw3d scroll bars) of 2019-12-13

**Comment by yyoncho** [comment]
probably you havent executed M-x lsp in this buffer. Use M-x lsp-describe-session to verify that.

**Comment by rrudakov** [comment]
Hm.. It's really weird. LSP session was active I've set `lsp-log-io` to `t` and run `lsp-workspace-restart` there was a lot of logs, but when I run `lsp-rename` there wasn't new entires in the log. But when I restart emacs the issue is gone. So I'll close this issue then.
