### ISSUE TITLE
Code jump not working in decompiled source or library source

### ISSUE THREAD

**Issue by xqliu** [emacs-lsp/lsp-java#186]
After decompile a java class file, then command like go to definition, find references etc will stop works in the auto generated buffer.

If there's source code attached, it works, but if there's no source code attached, it does not work.

I am not sure whether this is kind of a bug or a new feature.

I would like to help on this if you could help to guide me on the direction which part of the code I might need to look into.

Thanks :)

**Comment by yyoncho** [comment]
See https://github.com/dgileadi/vscode-java-decompiler/issues/8
