### ISSUE TITLE
No jdtls in list of servers when execute `lsp-java-update-server`

### ISSUE THREAD

**Issue by rrudakov** [emacs-lsp/lsp-java#187]
**Describe the bug**
When I run command `lsp-java-update-server` i get list of servers as on image:
![2020-01-07_11-44](https://user-images.githubusercontent.com/6093590/71889831-49dcd300-3143-11ea-9af1-27758d9cfe42.png)

**Comment by rrudakov** [comment]
Now I can't neither install nor update server.
```
LSP :: Download jdtls started.
Contacting host: raw.githubusercontent.com:443
Wrote /tmp/lsp-java-install8Ejkvh/pom.xml
LSP :: Server jdtls downloaded, auto-starting in 0 buffers.
```
After downloading I got another one suggestion to download and install server and fall into loop.

**Comment by yyoncho** [comment]
what do you have in \*lsp-install\* buffer?

**Comment by yyoncho** [comment]
I tested on a clean machine and it works fine. It probably fails to download the server but the code does not detect the failure and tries to download it again.

**Comment by rrudakov** [comment]
After cleaning `lsp-java-server-install-dir` the problem is gone. Server has been installed and started.
