### ISSUE TITLE
Cannot install server on non-Windows with no maven installed

### ISSUE THREAD

**Issue by rudi** [emacs-lsp/lsp-java#188]
**Describe the bug**

On a non-Windows system that does not have maven installed, the function `lsp-java--prepare-mvnw` returns the string `"sh mvnw"`, which is passed by `lsp-java--ensure-server` as the command name for `lsp-async-start-process`.  Since there is no executable named `sh mvnw`, `lsp-async-start-process` fails.

I implemented a local hack where `lsp-java--prepare-mvnw` returns a one- or two-element list (either `("mvnw.cmd")` or `("sh" "mvnw")`) instead of a single string and `lsp-java--ensure-server` appends the other arguments to that list; with that change I could successfully install the language server.  If you want, I could clean that up and submit a pull request.

**To Reproduce**

Try to install or reinstall the jdtls server on a non-Windows system without maven installed.

**Comment by yyoncho** [comment]
Thank you for reporting this. It would be great if you can provide a PR.

**Comment by rudi** [comment]
Ok, will do.  Are there any style guidelines wrt line length, commit message etc.?

**Comment by yyoncho** [comment]
Nothing particular.
