### ISSUE TITLE
Buffer name become lowercase when opened by going to definition

### ISSUE THREAD

**Issue by zijianyue** [emacs-lsp/lsp-java#190]
![image](https://user-images.githubusercontent.com/6119928/72789088-fbb0ef00-3c6d-11ea-8a6c-60d1b161de16.png)
The real buffer name is BusinessTypeUtil.java

**Comment by zijianyue** [comment]
Yes , on windows 10,  how can I avoid this? I've tested it on Eglot, no such issue.

**Comment by yyoncho** [comment]
AFAIK Eglot does not support flycheck. I will take a look and eventually provide a path. You do not use flycheck you may eval the following function and it will probably solve it on your side:

```
(defun lsp--fix-path-casing (path)
  ""
  path)
```

**Comment by zijianyue** [comment]
> AFAIK Eglot does not support flycheck. I will take a look and eventually provide a path. You do not use flycheck you may eval the following function and it will probably solve it on your side:
> 
> ```
> (defun lsp--fix-path-casing (path)
>   ""
>   path)
> ```

tested ok

**Comment by zijianyue** [comment]
The below method will cause flycheck can't display errors

> (defun lsp--fix-path-casing (path)
>   ""
>   path)
> 
![Uploading image.png…]()
