### ISSUE TITLE
Why is treemacs required by lsp-java?

### ISSUE THREAD

**Issue by ianpan870102** [emacs-lsp/lsp-java#193]
Is there a specific reason why lsp-java is requiring treemacs as a dependency? I personally don't use treemacs at all, so I'd prefer to not have it installed as a package.

**Comment by yyoncho** [comment]
Yes, we use it as a tree renderer for test browser and the tests result view: 
![jt-browser](https://user-images.githubusercontent.com/13259670/73118344-a3bf0480-3f5b-11ea-9be0-a712d4358ad1.gif)
