### ISSUE TITLE
Auto generating java docs

### ISSUE THREAD

**Issue by timur-han** [emacs-lsp/lsp-java#198]
Hi,

Thank you for the great contribution! 

Is there a way to generate java docs for methods, variables, and classes automatically?

**Comment by yyoncho** [comment]
Yes, type `/** | */` and invoke M-x company-complete with cursor at |.

**Comment by SreenivasVRao** [comment]
hi, I'm wondering if there's a way to automate this? also, I can't get this to work for classes, constructors or variables. It works only for methods... I get no-completions found for the rest.

**Comment by SreenivasVRao** [comment]
Hi @yyoncho, the indentation seems broken when I try this. I get something like: 

``` 
   /**
*
* @param
* @return
*/
```
Only the first line is correctly indented. Any ideas how to fix?

**Comment by yyoncho** [comment]
@SreenivasVRao someone should investigate how that works in vscode.
