### ISSUE TITLE
LSP :: Classpath is incomplete. Only syntax errors will be reported

### ISSUE THREAD

**Issue by Zoxic** [emacs-lsp/lsp-java#199]
Hello, i am newbie in Emacs also in Java programming and trying to set up the environment. Can you please tell me how i am supposed to set the classpath to make it complete?

**Comment by yyoncho** [comment]
The easies way is to generate a simple java project and then when asked to import the root select the directory that contains the pom.xml file https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html .

I have in my todo list a task to provide emacs command for creating simple java project.

I am closing the issue but you may use it for further questions.

**Comment by Zoxic** [comment]
Great thanks!

**Comment by francesco-cadei** [comment]
> I have in my todo list a task to provide emacs command for creating simple java project.

Is it in development?
Because i read the "maven in five minutes" but I'm not able to add gurobi.jar to my project.
What can I do?
