### ISSUE TITLE
Elisp error on trying java debug "wrong number of arguments"

### ISSUE THREAD

**Issue by miker2049** [emacs-lsp/lsp-java#202]
**Describe the bug**
Dap mode is unable to be attached or initiated from a fresh gradle init.  lsp-log doesnt show anything with regard to an attempt to debug, it just seems to get caught up at `cquery--execute-command-locally-advice`.  I am using the default spacemacs [config](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/java/packages.el) for lsp and dap, but based on the backtrace this really seems to be an lsp/dap issue.  I get no similar errors trying to do `dap-debug` on a c++ project.     

#### Reproduction guide :beetle:
- Create a new java project with gradle. e.g. `gradle init -> application -> java ->` (all defaults)
- run `./gradlew run --debug-jvm`
- `M-x dap-debug -> attach -> ` enter port gradle spits out

*Observed behaviour:* :eyes: :broken_heart:
```
Debugger entered--Lisp error: (wrong-number-of-arguments (3 . 3) 2)
  cquery--execute-command-locally-advice(#f(compiled-function (command &optional args) "Create and send a 'workspace/executeCommand' message having command COMMAND and optional ARGS." #<bytecode 0x1584b38b88d5>) "vscode.java.startDebugSession")
  apply(cquery--execute-command-locally-advice #f(compiled-function (command &optional args) "Create and send a 'workspace/executeCommand' message having command COMMAND and optional ARGS." #<bytecode 0x1584b38b88d5>) "vscode.java.startDebugSession")
  lsp-send-execute-command("vscode.java.startDebugSession")
  (let ((lsp--cur-workspace (lsp-find-workspace 'jdtls))) (lsp-send-execute-command "vscode.java.startDebugSession"))
  (plist-put conf :debugServer (let ((lsp--cur-workspace (lsp-find-workspace 'jdtls))) (lsp-send-execute-command "vscode.java.startDebugSession")))
  dap-java--populate-default-args((:type "java" :request "attach" :hostName "localhost" :port 5005 :host "localhost" :name "localhost(5005)"))
  dap-debug((:type "java" :request "attach" :hostName "localhost" :port 5005 :host "localhost" :name "localhost(5005)"))
  funcall-interactively(dap-debug (:type "java" :request "attach" :hostName "localhost" :port 5005 :host "localhost" :name "localhost(5005)"))
  call-interactively(dap-debug nil nil)
  command-execute(dap-debug)
```

*Expected behaviour:* :heart: :smile:
dap-mode will connect to the port gradle sets up for debugging and be functional.  

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.90
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d17c6e1e9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(typescript python rust yaml html systemd csv markdown myCustomFunctions
            (javascript :variables javascript-backend 'lsp javascript-repl 'skewer node-add-modules-path t)
            dap react tern lua auto-completion better-defaults emacs-lisp git helm gtags gpu
            (java :variables java-backend 'lsp)
            (c-c++ :variables c-c++-adopt-subprojects t c-c++-backend 'lsp-ccls c-c++-lsp-enable-semantic-highlight 'rainbow)
            supercollider multiple-cursors org
            (shell :variables shell-default-height 30 shell-default-shell 'vterm shell-default-position 'bottom)
            spell-checking syntax-checking treemacs emoji eww lsp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by yyoncho** [comment]
This is cquery bug, which I have reported but nobody is fixing it since it is dead project. The solution is to add cquery to the list of disabled packages in your .spacemacs file.
