### ISSUE TITLE
Question : server says "non-project file"

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-java#204]
When I open a java file, the server loads correctly but it warns constantly that the given file is not part of a project so that only syntax errors are reported.

Sorry if this is obvious for you, I am a newbie with java projects, may you tell me how to do ?

Regards

**Comment by yyoncho** [comment]
do M-x lsp-describe-session and check if the project root is the correct one(the folder that contains pom.xml/gradle file). Note that JDT LS server cannot handle all gradle project structures(e. g. android) and we might need to report it upstream.
