### ISSUE TITLE
Possible to add support for OpenBSD?

### ISSUE THREAD

**Issue by jpprime** [emacs-lsp/lsp-java#205]
Is it possible to add support for OpenBSD? I know it is currently not possible to install Eclipse on OpenBSD, and that is likely not going to change any time soon. But in my diminished understanding of Java, it seems to me that the Eclipse JDT Language Server doesn't need Eclipse to be installed, it needs only a working Java version, which OpenBSD has. So I was wondering what type of modifications would need to be made in order for it to work under the hardened puffer fish. I would be more than willing to contribute if that's a possibility.

**Comment by yyoncho** [comment]
What error do you get? Probably we miss an entry in a switch statement.

**Comment by jpprime** [comment]
I am so sorry about the delay on my response. It appears that the problem was not with the package but with my Java installation... It all works fine. Thank you for your contribution to Emacs and thank you for allowing me to use Emacs instead of a bloated IDE with none of my config!
