### ISSUE TITLE
lsp-organize-imports fails with Unable to find workspace

### ISSUE THREAD

**Issue by jcpetkovich** [emacs-lsp/lsp-java#206]
When trying to organize imports, I get the following message:

```sh
lsp-java--current-workspace-or-lose: Unable to find workspace
```

And my imports do not get organized. All other functionality of lsp-java appears to work, e.g., completion and navigation.

The versions of lsp that I'm using are as follows:

```sh
company-lsp-20190612.1553
helm-lsp-20200103.1659
lsp-java-20200114.2313
lsp-mode-20200311.612
lsp-treemacs-20200220.534
lsp-ui-20200308.1212
```

Interestingly, `(lsp-find-workspace 'jdtls)` seems to work just fine, but `(lsp-find-workspace 'jdtls (buffer-file-name))` seems to return `nil`.

**Comment by yyoncho** [comment]
which os do you use?

**Comment by jcpetkovich** [comment]
I'm using linux (gentoo).

**Comment by jcpetkovich** [comment]
Let me know if I can produce any logs for you or similar. It seems to happen with relatively simple projects, so I think I should be able to reproduce it on more or less anything.

**Comment by yyoncho** [comment]
I am unable to reproduce. if you do not pass buffer-file-name it will look for global jdt-ls. Can you check if buffer-file-name is under the workspace folder by evaluating buffer file name and then doing M-x lsp-describe-session and checking the workspace root. As a side note, the lsp-mode version of the function which is lsp-organize-imports will probably work.

**Comment by jcpetkovich** [comment]
I noticed that it didn't occur on a fresh new repository. I nuked `~/.emacs.d/lsp-session-v1` and re imported the roots of each project I saw this in. Seems to have been resolved, I'm not sure what caused it.

**Comment by yyoncho** [comment]
@jcpetkovich a few months ago we enforced the workspace folders to be with consistent ending regarding "/" so if you have old session fine that might have caused the issue.

**Comment by CsBigDataHub** [comment]
@yyoncho I have this exact issue now. I am running MacOS. I have deleted `~/.emacs.d/.lsp-session-v1` file and restarted emacs. None of the code actions are working.
