### ISSUE TITLE
Opening .java files results in error

### ISSUE THREAD

**Issue by uqix** [emacs-lsp/lsp-java#209]
**Describe the bug**
Opening .java files results in error

**Note**
1. Emacs version: Emacs-2020-03-06_01-40-17-...-universal from https://emacsformacosx.com/
2. lsp-mode and lsp-java versions: latest
2. To workaround this, I have to `M-x electric-pair-mode`, then reopen them
3. I tried putting `(electric-pair-mode)` in my `init.el`, no lucks

**To Reproduce**
1. create a simple maven project
2. open the Main.java
3. error

**Expected behavior**
.java files opened with lsp-mode working

**Logs**
```
Debugger entered--Lisp error: (wrong-type-argument stringp (require . info))
  string-match("\\(\\`\\|/\\)elec-pair\\(\\.elc\\|\\.el\\|\\.dylib\\|\\.so\\)?\\..." (require . info))
  load-history-filename-element("\\(\\`\\|/\\)elec-pair\\(\\.elc\\|\\.el\\|\\.dylib\\|\\.so\\)?\\...")
  eval-after-load("elec-pair" #f(compiled-function () #<bytecode -0x2244f017e819e5b>))
  c-initialize-cc-mode(t)
  java-mode()
  set-auto-mode-0(java-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil nil t nil nil)
  revert-buffer--default(t nil)
  revert-buffer(t)
  funcall-interactively(revert-buffer t)
  call-interactively(revert-buffer nil nil)
  command-execute(revert-buffer)
```

**Comment by yyoncho** [comment]
I don't see anything lsp-mode related in the callstack.

**Comment by uqix** [comment]
Yes, this problem has nothing to do with lsp-java, it happens even in an freshly installed Emacs.
Sorry about bothering, @yyoncho
