### ISSUE TITLE
[Feature Request/Enhancement] Add JDEE mode as known major mode

### ISSUE THREAD

**Issue by CobaltSpace** [emacs-lsp/lsp-java#210]

**Comment by yyoncho** [comment]
Can you list which exactly is that mode?

**Comment by CobaltSpace** [comment]
It is the from Java Development Environment for Emacs.

Melpa: http://melpa.org/#/jdee
Github: https://github.com/jdee-emacs/jdee

**Comment by GMTSE** [comment]
Yes would be great, otherwise I get multiple warnings like:
```
Warning (lsp-mode): Unable to calculate the languageId for buffer ‘test.java’. Take a look at ‘lsp-language-id-configuration’. The ‘major-mode’ is jdee-mode
```
everytime I open a `.java` file :{
Thanks for the GREAT tools!

**Comment by GMTSE** [comment]
The patch from @yyoncho does not seems to solve the problem for me.

In my `.emacs.d/config.org` I have:
```(add-hook 'java-mode-hook #'lsp)```
Plus a few variable configurations for JDEE.

When I open a `.java` file from command line, I still get an error buffer that is opened together with the Java file with the same error message as cited above.

If I enter "M-x lsp"  in the Java file buffer, then I get an error buffer with the error repeated tens of times (see attached picture).
![screenshot_2021-05-06-11 05](https://user-images.githubusercontent.com/44055506/117272671-b3661200-ae5b-11eb-8d67-d258960a1200.png)

**Comment by yyoncho** [comment]
https://github.com/emacs-lsp/lsp-mode/commit/c7c29adb4457c3169ccceddad0fd8c01089b02fd
