### ISSUE TITLE
jdt ls doesn't use the gradle version of the project

### ISSUE THREAD

**Issue by nwsummit** [emacs-lsp/lsp-java#221]
jdt ls seems to always use the latest gradle version (currently 6.3) to build the project, not the gradle version of the project itself. In most cases, it's fine. But when some features from older version is removed in the newer version of gradle, then jdt ls will fail to build the project, thus lsp-java can't serve its purpose.

The error I encountered is related to gradle's DefaultSourceDirectorySet being removed in gradle 6, thus jdt ls fails to build any projects still using an older version of gradle and using DefaultSourceDirectorySet.

Not sure if this is the right repo to file this issue, but thought I would start here.

**Comment by yyoncho** [comment]
Report it here: https://github.com/eclipse/eclipse.jdt.ls (it may be still a lsp-java missing setting, but server guys will be able to help).

**Comment by ThatHai** [comment]
@yyoncho I need help to understand whether there's anything lsp-java can do with respect to this issue. This is the instructions from the jdt language server folks:
https://github.com/eclipse/eclipse.jdt.ls/issues/1431#issuecomment-629813698

**Comment by yyoncho** [comment]
@ThatHai here it is how we expose the server settings as defcustoms - https://github.com/emacs-lsp/lsp-java/blob/master/lsp-java.el#L308 . Those properties are currently missing.

**Comment by arichiardi** [comment]
@yyoncho and @ThatHai 

Sorry to reply here but I think I am running into the same issue, how do I solve?

Do I need to add `defcustoms` to `lsp-java`?

**Comment by yyoncho** [comment]
> @yyoncho and @ThatHai
> 
> Sorry to reply here but I think I am running into the same issue, how do I solve?
> 
> Do I need to add `defcustoms` to `lsp-java`?

Yes, I am waiting for someone to confirm that this fixes the issue and eventually provide a PR.

**Comment by arichiardi** [comment]
@yyoncho I added this to my `.dir-locals.el`

```elisp
(lsp-java-vmargs . ("-Djava.import.gradle.version=6.2.2"))
```
I am not sure though that it is solving things here, as I don't see gradle in my `ps aux | grep java` so I cannot quite confirm it works.

**Comment by arichiardi** [comment]
@yyoncho I cannot quite seem to understand how they pass the property from `vscode-java` down to the JVM, the `-D` does not work for me, do you know more?

**Comment by arichiardi** [comment]
So this works here, however I guess it is not ideal:

```
$ cd my-project
$ ./gradlew wrapper --gradle-version 6.0.1
$ rm -rf gradle/wrapper 
```

I thought we would be able to set a property with `-D` and have the language server download the right version for us.
Man

**Comment by ThatHai** [comment]
@yyoncho I added  `-Djava.import.gradle.version=5.4.1` for `lsp-java--ls-command` but that doesn't work. The only way to get it to work seamlessly is having the `gradle-wrapper.properties` file at its default location.
I do have a PR (almost ready) as a workaround using the below properties
```
"java.import.gradle.version": "5.4.1",
"java.import.gradle.wrapper.enabled": false
```
 by passing them to `lsp-register-custom-settings` per your earlier pointer https://github.com/emacs-lsp/lsp-java/blob/master/lsp-java.el#L308

The workaround is not as seamless when switching between projects that use different gradle version, as it requires restarting the jdt ls. But I'll submit the PR soon and you can decide whether you want to accept it.
