### ISSUE TITLE
How to use lsp-java-test?

### ISSUE THREAD

**Issue by jsravn** [emacs-lsp/lsp-java#222]
**Describe the bug**
I'm struggling to use lsp-jt-mode. Is there a doc/example of how to use it?

- I execute `lsp-jt-lens-mode`. That gives me some options above each test to debug it/run it/or view results. Is there a keybinding or do I have to click these links? I could not find another way to run tests, other than using the `lsp-jt-browser` which shows all tests in the whole project.

- If I click run test, it does seem to run the test successfully, but it's not clear how to view the results. The only message I see is: "Debug session process ended with status: exited" in the eldoc line - which initially made me think something broke. In addition I get several graphic glitches:
  - There is a 5 line buffer that is opened at the bottom of the screen that is switched to automatically. It is completely empty though - is it supposed to show something?
  - The modeline is turned orange when I switch back to the buffer with the test class. What's the point of that? And can it be disabled?

- I found if I click on the green tick next to "run test", it shows the test result however they are truncated and I can't see anything useful. Is there a way to expand the size of this?

**Screenshots**

![image](https://user-images.githubusercontent.com/522123/81062965-dec3c300-8ece-11ea-9ac2-0f82fda43adf.png)

**What I expect to happen**

Ideally it behaved similar to other test modes where the tests are executed in a minibuffer and you can click the failures and go to them. Also, I could use a key binding to execute a test under point. Is such a thing possible or do I have to use the pseudo test result browser and code lens? Is that the expected approach? If so that's fine - I will have to figure out how to set up my own approach.

Thanks for any help in advance!

**Comment by yyoncho** [comment]
> I'm struggling to use lsp-jt-mode. Is there a doc/example of how to use it?

It is unfinished - when I started working on it, the upstream was about to change the way it runs the tests so I decided to wait that refactoring to finish before finishing the package. I never had the time to fix it after that that is why it is not listed in the README at all.

> I execute lsp-jt-lens-mode. That gives me some options above each test to debug it/run it/or view results. Is there a keybinding or do I have to click these links? I could not find another way to run tests, other than using the lsp-jt-browser which shows all tests in the whole project.

Use `lsp-avy-lens` (you will have to install avy as well).

> If I click run test, it does seem to run the test successfully, but it's not clear how to view the results. The only message I see is: "Debug session process ended with status: exited" in the eldoc line - which initially made me think something broke. In addition I get several graphic glitches:

> There is a 5 line buffer that is opened at the bottom of the screen that is switched to automatically. It is completely empty though - is it supposed to show something?

This is dap-mode issue, dap-auto-show-output should be removed and the output should be displayed when it is used for the first time. 

> The modeline is turned orange when I switch back to the buffer with the test class. What's the point of that? And can it be disabled?

I think that this is doom modeline issue. I see it too - haven't had the time to investigate/report it.

> I found if I click on the green tick next to "run test", it shows the test result however they are truncated and I can't see anything useful. Is there a way to expand the size of this?

probably you have treemacs-lock-width set to t?


> What I expect to happen

> Ideally it behaved similar to other test modes where the tests are executed in a minibuffer and you can click the failures and go to them.

For the navigation I think that in the end the browser should be used. The missing output buffer is a bug.

> Also, I could use a key binding to execute a test under point.

For this one there is dap-java-debug-test-method(which is my add-hoc test implementation).

**Comment by yyoncho** [comment]
> The missing output buffer is a bug.

To clarify - the buffer is there but it is not displayed.

**Comment by jsravn** [comment]
@yyoncho thank you for the helpful answers.

**Comment by ericdallo** [comment]
About the dap orange on modeline bug, this should have fixed: https://github.com/seagle0128/doom-modeline/pull/344

**Comment by yyoncho** [comment]
lsp-jt is now finished(at least most of the functionality is there) and documented. closing.
