### ISSUE TITLE
Run|Debug on main method

### ISSUE THREAD

**Issue by ericdallo** [emacs-lsp/lsp-java#224]
I think we can achieve the same behavior as VSCode `Run|Debug` overlays on `main` methods:

![](https://code.visualstudio.com/assets/docs/java/java-debugging/java-codelens.gif)

One idea is to follow the implementation of `lsp-dart` run|debug on tests:

![](https://github.com/emacs-lsp/lsp-dart/raw/master/images/run-test.gif)

Is that makes sense?

**Comment by yyoncho** [comment]
lsp-java-lens-mode?

**Comment by ericdallo** [comment]
Oh sorry, I didn't find that :sweat_smile:
