### ISSUE TITLE
lsp-java tries to watch user's home

### ISSUE THREAD

**Issue by aconchillo** [emacs-lsp/lsp-java#225]
**Describe the bug**

The first time I open a Java file (after starting emacs), jdts server is trying to start but blocks for a few seconds and finally it asks me if I want to watch all files in my home.

I'm running:

macOS Catalina 10.15.4

Emacs inside terminal (from homebrew): 26.3
lsp-mode: 20200512.505
lsp-java: 20200430.1659

**To Reproduce**

Create a an empty java file:

```
$ mkdir lsp-java-test
$ cd lsp-java-test
$ touch test.java
```

Start emacs and open lsp-java-test/test.java.

This is my emacs configuration.

```
(require 'lsp-java)

(defun my-java-mode-hook ()
  (setq c-basic-offset 4)
  (setq lsp-java-save-actions-organize-imports t))

(add-hook 'java-mode-hook 'my-java-mode-hook)
(add-hook 'java-mode-hook #'lsp)

;; This is so Lombok works, otherwise java can't find definitions.
(setq path-to-lombok (expand-file-name "~/.emacs.d/java/lombok-1.18.12.jar"))

(add-to-list 'lsp-java-vmargs
             (concat "-javaagent:" path-to-lombok))
(add-to-list 'lsp-java-vmargs
             (concat "-Xbootclasspath/a:" path-to-lombok))
```

**Expected behavior**

jdts LSP server loads quick and doesn't block.

**Screenshots**

![Screen Shot 2020-05-12 at 9 31 47 PM](https://user-images.githubusercontent.com/951761/81771995-727e2c00-9499-11ea-94af-d7f21163f61e.png)

**Logs**

I don't really have any logs.

**Comment by yyoncho** [comment]
You have accidentally added the root folder to the list of workspaces. Use `lsp-workspace-folders-remove` and the next time you see the import project dialogue make sure you pick the project root.

**Comment by aconchillo** [comment]
That's what I thought, but I forgot to mention that I have also checked tried that but the folder is not one of the options when I do `lsp-workspace-folders-remove`.

Where are the workspace folders saved?

**Comment by yyoncho** [comment]
That is odd - try deleting lsp-sessions-file, lsp-java-workspace-folder and restarting emacs.

**Comment by yyoncho** [comment]
It is lsp-java-workspace-dir not lsp-java-workspace-folder.

**Comment by aconchillo** [comment]
That fixed it. Thank you! I guess I added it by mistake and things got into a bad state at some point. First time I delete ` lsp-sessions-file` or `lsp-java-workspace-folder`.

Closing.

**Comment by yyoncho** [comment]
Yes, eclipse workspace tend to corrupt from time to time, even vscode has a command to delete it.
