### ISSUE TITLE
Dependencies Removed from Classpath on Git Operation

### ISSUE THREAD

**Issue by jsuskalo** [emacs-lsp/lsp-java#227]
When working in a large gradle project with multiple sub-projects and the user switches branches, performs a rebase, or otherwise affects the status of files on disk by way of git and not conventional editing through emacs, all external project dependencies appear to vanish from the classpath, causing packages not to resolve.

**To Reproduce**
Unfortunately the main codebase that this problem appears in is closed source, and I haven't been able to reproduce it in a smaller repository, but maybe the symptoms on their own will be enough to track down the cause.

- Import the project on a clean install of lsp-java
- Perform a git operation like switching branches or rebasing
- Packages fail to resolve
- Call `lsp-restart-workspace`
- Behavior persists
- Call `lsp-java-update-project-configuration` from either the root gradle file or the gradle file for the individual subproject
- Behavior persists

**Expected behavior**
When a git operation is performed, the project is re-imported and all dependencies resolve correctly.

**Logs**
Example element of the logs for one of the failed dependencies:
```json
  {
    "command": {
      "arguments": [
        {
          "context": {
            "diagnostics": [
              {
                "message": "The import org.springframework cannot be resolved",
                "source": "Java",
                "code": "268435846",
                "severity": 1,
                "range": {
                  "end": {
                    "character": 26,
                    "line": 5
                  },
                  "start": {
                    "character": 7,
                    "line": 5
                  }
                }
              }
            ]
          },
          "range": {
            "end": {
              "character": 49,
              "line": 5
            },
            "start": {
              "character": 49,
              "line": 5
            }
          },
          "textDocument": {
            "uri": "file:///<redacted>.java"
          }
        }
      ],
      "command": "java.action.organizeImports",
      "title": "Organize imports"
    },
    "diagnostics": [],
    "kind": "source.organizeImports",
    "title": "Organize imports"
  },
```
There's also one of these for each subproject in the jdtls output. We use OpenApi for some items, but I'm unsure how that would be related.
```
May 18, 2020 7:34:23 PM Failed to publish diagnostics for file:///<redacted>/src/openApiGen/java/<redacted>/ControllerConfig.java
src/openApiGen/java/<redacted>.account [in <redacted>] is not on its project's build path
Java Model Exception: Java Model Status [src/openApiGen/java/<redacted>.account [in <redacted>] is not on its project's build path]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:583)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:256)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:530)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:250)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:530)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1236)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:250)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:596)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:326)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:312)
	at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:298)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.publishDiagnostics(WorkspaceDiagnosticsHandler.java:264)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.publishDiagnostics(WorkspaceDiagnosticsHandler.java:208)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$1.run(JDTLanguageServer.java:282)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by yyoncho** [comment]
Does it fix after lsp-workspace-folder-remove? Did you try a clean build from lsp-java-build-project ? Can you track if the operations that you perform delete the .classpath/.project or .settings?

**Comment by yyoncho** [comment]
Also, do you have the watches enabled?

**Comment by jsuskalo** [comment]
Watches are enabled; .classpath, .project, and .settings are all in the .gitignore so none are affected by git actions; it works correctly after lsp-workspace-folder-remove; and clean build from lsp-java-build-project fails with a message like the following:
```
May 18, 2020 8:30:20 PM Error occured while building workspace. Details: 
 message: SqlSessionFactoryBean cannot be resolved to a type; code: 16777218; resource: /<redacted>/AccountConfig.java; line: 31
 message: The import org.springframework cannot be resolved; code: 268435846; resource: /<redacted>.java; line: 5
```
plus an additional 5417 lines with additional errors of that sort, indicating that types or packages cannot be resolved.

**Comment by yyoncho** [comment]
Sounds like the jdtls workspace is corrupted, can you delete it and restart emacs?

**Comment by jsuskalo** [comment]
What do you mean delete the workspace? Do you mean call `lsp-shutdown-workspace`? Or is there a folder I need to delete somewhere? I couldn't find reference to one.
This problem persists across restarts of emacs.

**Comment by yyoncho** [comment]
Delete lsp-java-workspace-dir . I guess server was in the middle of something when you did the revert and it ended up in corrupted state - I haven't seen that, although I am performing that exact steps very often which makes me think that you were not lucky.

**Comment by jsuskalo** [comment]
This seems to have moved me on to a different error, and I think this might actually be part of the root cause. I note that it's using gradle 6.3, and not the local gradle wrapper, which is using an older version. I've got the following in my dir locals, but I suspect that lsp-java uses different variables to determine if the gradle wrapper is used:
```lisp
((nil . ((gradle-use-gradlew . t)
         (eval . (progn (require 'projectile)
                        (setq-local gradle-gradlew-executable (concat (projectile-project-root) "gradlew")))))))
```

**Comment by jsuskalo** [comment]
Since it seems like the real issue here is the gradle thing, I'm going to close this issue and make a new one for that.
