### ISSUE TITLE
xref-find-references shows up doesn't work with java+lombok

### ISSUE THREAD

**Issue by bharad1988** [emacs-lsp/lsp-java#229]
**Describe the bug**
The xref-find-references, shows up methods from lombok getters and setters. But when selected , doesn't lead to references. 
 The lsp-ui-peek find-references doesn't show the getter and setter methods if lombok is used. Although , the autocomplete works fine 

**To Reproduce**
Just use lombok to generate getters and setters, use jvm args to ensure lombok is detected 
-javaagent:/home/<username>/.m2/repository/org/projectlombok/lombok/1.18.6/lombok-1.18.6.jar" in lsp-java-vmargs
**Logs**

20 May, 2020 4:12:28 PM >> document/hover
20 May, 2020 4:12:38 PM >> document/references

**Comment by bharad1988** [comment]
https://github.com/bharad1988/SampleProject 
Adding sample project

**Comment by bharad1988** [comment]
Adding some snapshots 
![Screenshot from 2020-05-20 20-24-43](https://user-images.githubusercontent.com/19284613/82464276-83ebb780-9adb-11ea-9292-62781f42f313.png)
![Screenshot from 2020-05-20 20-24-53](https://user-images.githubusercontent.com/19284613/82464281-864e1180-9adb-11ea-976f-d82f6445bdd5.png)

**Comment by yyoncho** [comment]
Hi @fbricon, when using lombok jdtls seems to be failing to find the references when they are requested for the field for which lombok will generate getters/setters. Is this a bug or limitation?

**Comment by yyoncho** [comment]
Closing, please report in the upstream.
