### ISSUE TITLE
How to change the toolbox's template?

### ISSUE THREAD

**Issue by vanniuner** [emacs-lsp/lsp-java#230]
Frist of all, thanks for this respositories author @yyoncho.This project is asm!! 
My question is, the company's selection content is too long ,and mostly were repeated. I rearched the document about company company-lsp and lsp-java, but get nothing.

##### Currently an example selection content in below.
> error(String format, Object arg) : void Logger.error(String format, Object arg)  : void (Method)
> error(String format, Throwable t) : void Logger.error(String format, Throwable t)  : void (Method)
>...
or
> List - javax.validation.constrains.Max  javax.validation.constrains.Max (Interface)
> List - javax.validation.constrains.Min  javax.validation.constrains.Min  (Interface)
>...

##### What we want.
> error(String format, Object arg) : void      (Method)
> error(String format, Throwable t) : void   (Method)
>...
or
> List - javax.validation.constrains.Max (Interface)
> List - javax.validation.constrains.Min  (Interface)
>...

##### Even just make the type shotter.
> error(String format, Object arg) : void      M
> error(String format, Throwable t) : void   M
>...
or
> List - javax.validation.constrains.Max I
> List - javax.validation.constrains.Min  I
>...

**Comment by yyoncho** [comment]
1. Switch from company-lsp to company-capf. company-lsp is no longer supported.
2. (setq lsp-completion-enable-additional-text-edit nil)

**Comment by vanniuner** [comment]
How to do the 1th step?witch from company-lsp to company-capf.

**Comment by yyoncho** [comment]
delete company-lsp or set lsp-prefer-capf to t

**Comment by vanniuner** [comment]
![Screenshot from 2020-05-24 21-45-17](https://user-images.githubusercontent.com/7248023/82755697-e7415680-9e07-11ea-85e9-50d37f761ad4.png)

**Comment by yyoncho** [comment]
Make sure you are using the latest version of all components. Also, use M-x company-diag to verify that you are using company-capf.

**Comment by vanniuner** [comment]
Firstly M-x company-diag output below.

> Emacs 26.3 (x86_64-pc-linux-gnu) of 2019-09-17 on lcy01-amd64-030
> Company 0.9.12
> 
> company-backends: (company-capf company-yasnippet)
> ...

Now the update program done.The is no change about the company mode, I reopened emacs too.

Check something :
M-x list-package  U ,out put no packages to upgrade.
M-x company-diag output again outout below

> Emacs 26.3 (x86_64-pc-linux-gnu) of 2019-09-17 on lcy01-amd64-030
> Company 0.9.12
> 
> company-backends: (company-capf company-yasnippet)
> 
> Used backend: company-capf
> Major mode: java-mode
> Prefix: ("err" . t)

**Comment by yyoncho** [comment]
It works with the getting started snippet and clean config:

```
(require 'cc-mode)

(condition-case nil
    (require 'use-package)
  (file-error
   (require 'package)
   (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
   (package-initialize)
   (package-refresh-contents)
   (package-install 'use-package)
   (require 'use-package)))

(setq use-package-always-ensure t)

(use-package projectile)
(use-package flycheck)
(use-package yasnippet :config (yas-global-mode))
(use-package lsp-mode :hook ((lsp-mode . lsp-enable-which-key-integration))
  :config (setq lsp-completion-enable-additional-text-edit nil))
(use-package hydra)
(use-package company)
(use-package lsp-ui)
(use-package which-key :config (which-key-mode))
(use-package lsp-java :config (add-hook 'java-mode-hook 'lsp))
(use-package dap-mode :after lsp-mode :config (dap-mode t) (dap-ui-mode t))
(use-package dap-java :ensure nil)
(use-package helm-lsp)
(use-package lsp-treemacs)
```

And then:
```
HOME=/tmp emacs -q -l lsp-java-quick.el /home/kyoncho/Sources/lsp/dap-mode/features/fixtures/test-project/src/main/java/temp/App.java
```

**Comment by vanniuner** [comment]
I use doom emacs, maybe I need a deep research. 
Thanks for your Helping : ) .
