### ISSUE TITLE
Gradle Wrapper Support

### ISSUE THREAD

**Issue by jsuskalo** [emacs-lsp/lsp-java#231]
I have a project that I work with on a daily basis that uses an older version of Gradle by way of using a gradle wrapper. I've gotten other emacs modes like gradle-mode to use the wrapper, but it seems like the LSP server is only using the latest version of gradle, regardless of what's installed on my system or what the wrapper is.

Is there a way to customize the gradle command being used?

**Comment by yyoncho** [comment]
see https://github.com/emacs-lsp/lsp-java/pull/228

**Comment by yyoncho** [comment]
And if you have more questions please cc @ThatHai which implemented the feature. I use maven and I can offer little help.

**Comment by jsuskalo** [comment]
Thanks!
