### ISSUE TITLE
Is there a way to automatically return null values from functions?

### ISSUE THREAD

**Issue by SreenivasVRao** [emacs-lsp/lsp-java#235]
Hi,

I want lsp-java to populate an initial function definition with a return type null.

for example if I have:

`public <non-void-return> functionName() {<point here>} `
can lsp auto update the function as
```
public <non-void-return> functionName() {<point here>
return null; } 
```
or alternatives without lsp would be helpful too :)

**Comment by yyoncho** [comment]
Closing since it seems like the question was answered.
