### ISSUE TITLE
Automatic server installation doesn't work

### ISSUE THREAD

**Issue by rrudakov** [emacs-lsp/lsp-java#236]
**Describe the bug**
When I open the buffer with java source file, I get prompt to install jdtls server. After confirming installation I get next error:

```
LSP :: Download jdtls started.
Contacting host: raw.githubusercontent.com:443
Wrote /tmp/lsp-java-install5r2fYN/pom.xml
LSP :: Server jdtls install process failed with the following error message: Keyword argument :stdout not one of (:name :buffer :command :coding :noquery :stop :connection-type :filter :sentinel :stderr :file-handler).
Check `*lsp-install*' and `*lsp-log*' buffer.
```

`*lsp-install*` and `*lsp-log*` buffers are not created. `toggle-debug-on-error` doesn't work in this case. All I have is few lines in `*Messages*` buffer.

**Note**
Emacs version: 27.0.91
lsp-mode: latest from MELPA
lsp-java: latest from MELPA

**Comment by rrudakov** [comment]
I've removed line `:stdout " *lsp-install*"` from `lsp-mode.el`, removed all `*.elc` files and issue is gone. Not sure how does it affect the rest of LSP functionality.

**Comment by io12** [comment]
Thanks for looking into this! I can reproduce the bug and this fix works.
