### ISSUE TITLE
Support for Java 9+ arguments does not seem to work

### ISSUE THREAD

**Issue by mpsq** [emacs-lsp/lsp-java#237]
The code in my project relies on some classes from `jdk.internal`. To make it compile without issues, `maven` passes `--add-exports java.base/jdk.internal.math=ALL-UNNAMED` to `javac`. `lsp-java` uses `jdt.ls` so I tried to replicate the same behaviour:

```lsip
(setq lsp-java-vmargs '("-noverify"
                             "-Xmx1G"
                             "-XX:+UseG1GC"
                             "-XX:+UseStringDeduplication"
                             "--add-exports"
                             "java.base/jdk.internal.math=ALL-UNNAMED"))
(setq lsp-java-9-args '("--add-modules=ALL-SYSTEM"
                             "--add-opens java.base/java.util=ALL-UNNAMED"
                             "--add-opens java.base/java.lang=ALL-UNNAMED"
                             "--add-exports"
                             "java.base/jdk.internal.math=ALL-UNNAMED"))
```

However compiling (`lsp-java-build-project`) the project still fails:

```
Error occured while building workspace. Details: \n message: The type jdk.internal.math.FDBigInteger is not accessible; ...
```

**To Reproduce**
Try to compile the project https://github.com/questdb/questdb with lsp-java/jdt.ls.

**Expected behavior**
Compiling should be successful (like it is when running from Maven)

**Logs**
I could not find anything helpful with `lsp-print-io`, let me know if I missed something.

Thank you :)

**Comment by yyoncho** [comment]
Can you ensure that those are passed to the server by checking in process explorer and if yes, can you ask in the server repo about what is the correct way to pass those arguments to the JDTLS? I am not familiar in details with server internals.

**Comment by mpsq** [comment]
I get the following:

```
/usr/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dlog.protocol=true -Dlog.level=ALL --add-exports java.base/jdk.internal.math=ALL-UNNAMED -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar /home/mpsq
/.emacs.d/.cache/lsp/eclipse.jdt.ls/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar -configuration /home/mpsq/.emacs.d/.cache/lsp/eclipse.jdt.ls/config_linux -data /home/mpsq/.emacs.d/workspace/ --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED
`

**Comment by yyoncho** [comment]
So it is fine? Can you ask in jdtls repo? I really dont know what is the correct what to do what you are trying to do. I guess that the correct place to change is .project file but not sure about that.

**Comment by mpsq** [comment]
Thanks for your help, I will ask on the jdtls repo :)
