### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-java#238]
Hello,

I set up the `lsp-java-format-settings-url` variable with a valid path toward a xml file, like this :
```
use-package(lsp-java
   : init
   (setq lsp-java-format-settings-url "~/.emacs.d/lsp/formatter.xml")
  ...
```
But when I apply formatting it obviously does not follow the rules contained in the xml file.

I checked with `C-h v` that the previous variable is correctly set, am I missing something ?

Regards

**Comment by yyoncho** [comment]
You should set also lsp-java-format-settings-profile and the also settings-url must not be relative path but `uri`, e. g. `file://<fullpath>`

**Comment by deb75** [comment]
Thanks !

This solved my issue.
