### ISSUE TITLE
Run maven ?

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-java#241]
Hello,

My project is  of `maven` type, how can I build the jar file with `lsp-java` ?

**Comment by yyoncho** [comment]
You may use https://github.com/apg/mvn-el or `M-x projectile-compile`

**Comment by deb75** [comment]
Thanks,

`mvn-el` seems a bit outdated, but `projectile-compile` works well.

By the way, what `lsp-java-build-project` is supposed to do ? I assumed at first it was for executing the `install` or `package` target of `maven` (when using it)
