### ISSUE TITLE
Unable to find installed server supporting this file.

### ISSUE THREAD

**Issue by haswell4u** [emacs-lsp/lsp-java#244]
Hello,

I followed the installation section to setup lsp-java on my emacs. (version 26.3, windows 10)
However, whenever I open the .java file, the following message is displayed.

> "Unable to find installed server supporting this file. The following servers could be installed automatically: "

I also tried installing it on my MacBook (macOS catalina) but I get the same message.

Did I miss something?

**Comment by yyoncho** [comment]
Press TAB. For a better experience as the sample config in the readme suggest consider using helm.

**Comment by haswell4u** [comment]
The jdtls seems to be installed.

After that, I ran several commands, including `lsp-java-generate-to-string`, to check if everything was working correctly.
But, the following message was displayed. (I expected the toString method to be generated automatically.)

> lsp--send-request-async: The connected server(s) does not support method textDocument/codeAction
To find out what capabilities support your server use ‘M-x lsp-describe-session’ and expand the capabilities section.

I checked the lsp-describe-session, but nothing.
Is the server installation wrong?

**Comment by yyoncho** [comment]
Did you do M-x lsp?

**Comment by haswell4u** [comment]
Yes, I did.

It returns message which is,

> using config for config_win
Searching for program: No such file or directory, java

It seems that the java file is not recognized.
Please tell me if I need to provide something (e.g., file tree, init.el ...) for your advice.

**Comment by yyoncho** [comment]
java is not on path

**Comment by yyoncho** [comment]
you may customize lsp-java-java-path

**Comment by haswell4u** [comment]
Great!

I added the following line to my init.el file, and it works fine.

`(setq lsp-java-java-path (substitute-in-file-name "$JAVA_HOME/java"))`

Thanks, Ivan.

**Comment by haswell4u** [comment]
Before I close this issue, I have one more question.
I sometimes get the following error message when installing jdtls on other computers (Windows 7, macOS).

> LSP :: Server jdtls install process failed with the following error message: Searching for program: No such file or directory, mvnw.cmd.

Why am I getting this message, and what is the solution?

**Comment by satyanash** [comment]
> Press TAB. For a better experience as the sample config in the readme suggest consider using helm.
If you `RET` (to auto-select a default?) without entering anything, it will fail with the below error:

```
File mode specification error: (wrong-type-argument lsp--client nil)
```

Maybe, there ought to be better error messages to tell the user that they should enter a sane value?
