### ISSUE TITLE
In favor of `lsp-install-server` for initialization?

### ISSUE THREAD

**Issue by breakds** [emacs-lsp/lsp-java#251]
I am a newbie to both Java and `lsp-java`, and my opinion might be wrong (and that is why I am asking the question here). Thanks in adavance!

I recently installed `lsp-java` in my emacs configuration. Unlike what is described in the docs, jdt language server was not automatically installed. After some tinkering I found that I can do that with `lsp-install-server`.

I can't help search the code base and found the following line

https://github.com/emacs-lsp/lsp-java/blob/17450c5e17dc246316b1d41e91ad92e5ed323b49/features/support/env.el#L31

It seems to me that the automatic download and install jdt language server part is still using the deprecated `lsp-java-update-server`, which is supposed to do nothing at this moment. I guess it is fine for people who already had jdt language server installed as this line will never be executed (and maybe this is why it gets slipped in tests), but might need to be adapted to use the recommended `lsp-install-server`?

It would be very helpful if someone can help confirm. Appreciate your great work!

**Comment by yyoncho** [comment]
Break Yang writes:

> After some tinkering I found that I can do that with `lsp-install-server`.

Yes. But the automatic install should happen when you open java file.

>
> I can't help search the code base and found the following line
>
> https://github.com/emacs-lsp/lsp-java/blob/17450c5e17dc246316b1d41e91ad92e5ed323b49/features/support/env.el#L31

This is some left-over code, you may ignore it, we have to delete it at
some point.

**Comment by breakds** [comment]
Thanks for the confirmation, @yyoncho!
I guess then I need to find out why the automatic installation of jdtls does not happen. When I open a `.java` file, it just complains cannot find the server, and ask me to select from candidate. However, the candidate list seems to be empty.

**Comment by yyoncho** [comment]
> OTH, maybe we should update the `README.md` so that the new user knows to type `jdtls`?

You could press TAB as well - this is how emacs default completion-read works. I recommend you to install helm/ivy which provide much better interface for that matter.

**Comment by yyoncho** [comment]
FTR most likely we should provide default entry when there is only one candidate, in this way it will be a bit clearer for this case. 

As a side note, I am working on minimalistic configuration which will target someone just starting with lsp-mode/emacs which will remove those traps.
