### ISSUE TITLE
Question : flycheck or flymake ?

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-java#253]
In the latest upgrade or `lsp-mode`, it seems `flycheck` has been removed and replaced by `flymake`.

Also, I cannot find it anymore in the emacs package manager. Does `lsp-java` still needs `flycheck` ?

Regards

**Comment by jcs090218** [comment]
Try setting `lsp-prefer-flymake` to `t`.

**Comment by yyoncho** [comment]
> Try setting `lsp-prefer-flymake` to `t`.

Yes. If you don't do that and if you have flycheck lsp-mode will pick it by default.
