### ISSUE TITLE
Code jump not working in decompiled source or library source

### ISSUE THREAD

**Issue by vanniuner** [emacs-lsp/lsp-java#256]
About issues：
[https://github.com/emacs-lsp/lsp-java/issues/186#issue-542793366](url)
How to fix it？ If there have an solution why not put them into this respostory? plea........se.

**Comment by ericdallo** [comment]
@yyoncho ?

**Comment by yyoncho** [comment]
So, this is not supported by the server. I generally suggest adding the sources for better experience. E. g. 
```mvn dependency:sources```  or `sudo apt-get install openjdk-11-doc openjdk-11-source`

**Comment by vanniuner** [comment]
it works
