### ISSUE TITLE
Doesn't seem to work with Lombok

### ISSUE THREAD

**Issue by david** [emacs-lsp/lsp-java#26]
I'm using [Lombok](https://projectlombok.org/) to generate getters and setters for my DTOs, but it seems those generated methods aren't being detected. For example, I see 

![image](https://user-images.githubusercontent.com/293/39867532-3d50e394-544d-11e8-9f9d-eb0d704b1b67.png)

I have everything up-to-date, including the Eclipse server. I tried lsp-intellij yesterday and there are no complains there (although I did have to install the Lombok plugin on Intellij for it to work).

Apparently one has to add [a few flags to the java command](https://github.com/redhat-developer/vscode-java/wiki/Lombok-support), but I'm not sure how to do that with lsp-java, or even if it is possible.

**Comment by yyoncho** [comment]
You can set jvm params using  `lsp-java-vmargs`

**Comment by david** [comment]
Unfortunately, that still doesn't seem to be working. I changed `lsp-java-vmargs` to `"-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -javaagent:/Users/david/.m2/repository/org/projectlombok/lombok/1.16.20/lombok-1.16.20.jar -Xbootclasspath/a:/Users/david/.m2/repository/org/projectlombok/lombok/1.16.20/lombok-1.16.20.jar"`.

In any case, it doesn't seem to be a problem with lsp-java, so I'll just close the issue. Thanks for taking the time to reply.

**Comment by david** [comment]
@yyoncho thanks for looking into this. It's working fine now.

**Comment by skybert** [comment]
Thanks for fixing this @yyoncho!

**Comment by yyoncho** [comment]
@skybert you welcome.

**Comment by didibus** [comment]
Could it be this no longer works? I get error saying imports for lombok don't resolve even though I have:

```
(setq lsp-java-vmargs
            `("-noverify"
              "-Xmx1G"
              "-XX:+UseG1GC"
              "-XX:+UseStringDeduplication"
              ,(concat "-javaagent:" path-to-lombok)
              ,(concat "-Xbootclasspath/a:" path-to-lombok)))
```

It used to work before.

**Comment by yyoncho** [comment]
I havent seen anything on the server-side that might break it. If you can provide me with a minimal reproducer I could test it and eventually report upstream.

**Comment by didibus** [comment]
Hum, okay I'll experiment more, just to be sure its not something weird in my setup, and try to see if I can do a minimal repro.

**Comment by CodeSwimBikeRunner** [comment]
I'm also not seeing this work. Let me do some digging.

**Comment by dakra** [comment]
I recently had to work on a project that uses lombok as well and if I set this

``` emacs-lisp
(setq lsp-java-vmargs '("-noverify" "-Xmx1G" "-XX:+UseG1GC" "-XX:+UseStringDeduplication" "-javaagent:/home/daniel/.m2/repository/org/projectlombok/lombok/1.18.12/lombok-1.18.12.jar" "-Xbootclasspath/a:/home/daniel/.m2/repository/org/projectlombok/lombok/1.18.12/lombok-1.18.12.jar"))
```

and then do `lsp-workspace-restart` it works for me.

**Comment by CodeSwimBikeRunner** [comment]
I downloaded the lombok jar and referenced its location like dakra.

My issue was patience, it takes a while for the jdtls to download, once I saw a buffer that showed it downloading and how long it was taking, just sitting and waiting for it to finish was the key.

**Comment by lazyskulptor** [comment]
Thanks to @dakra . I tried to merge with pre exist list.

(setq lsp-java-vmargs (append '("-noverify" "-XX:+UseStringDeduplication" "-javaagent:/Users/josh/.m2/repository/org/projectlombok/lombok/1.18.20/lombok-1.18.20.jar" "-Xbootclasspath/a:/Users/josh/.m2/repository/org/projectlombok/lombok/1.18.20/lombok-1.18.20.jar") lsp-java-vmargs))

**Comment by igoracmelo** [comment]
@dakra sorry my noobness, but does it matter where i put this line on?

**Comment by dakra** [comment]
No, anywhere in your init.el should be good.
It makes sense to group the config setting together of course just from an organization point of view.
E.g. you can check my config which uses `use-package`: https://github.com/dakra/dmacs/blob/master/init.org#java

You can try the setting in your running Emacs before saving it in your config by evaluating it in e.g. the scratch buffer
or type `M-:` and then `(setq lsp-java-vmargs '(........))` and then `M-x lsp-workspace-restart`.

**Comment by koptan** [comment]
I am using this config to download and set the path :

```
;; Java Configuration
(after! lsp-java

  (setq lombok-library-path (concat doom-data-dir "lombok.jar"))

  (unless (file-exists-p lombok-library-path)
    (url-copy-file "https://projectlombok.org/downloads/lombok.jar" lombok-library-path))

  (setq lsp-java-vmargs '("-XX:+UseParallelGC" "-XX:GCTimeRatio=4" "-XX:AdaptiveSizePolicyWeight=90" "-Dsun.zip.disableMemoryMapping=true" "-Xmx4G" "-Xms100m"))

  (push (concat "-javaagent:"
                  (expand-file-name lombok-library-path))
          lsp-java-vmargs)
)

```

**Comment by saulotoledo** [comment]
I developed this package to automate the injection of java agents (including lombok): https://github.com/saulotoledo/java-agent-loader
It works with lsp-java and is available on MELPA.
