### ISSUE TITLE
dap-java.el "missing" with fresh install from melpa-stable

### ISSUE THREAD

**Issue by ThatHai** [emacs-lsp/lsp-java#260]
Latest versions available on melpa-stable as of 25-Aug-2020:
* dap-mode v0.6 where dap-java.el is removed
* lsp-java v3.0 where dap-java.el hasn't been move there yet

This causes dap-java not being available if packages are installed from melpa-stable.
NOTE that's not the case for packages on melpa.

Workaround: Manually download lsp-java/dap-java.el

**Comment by yyoncho** [comment]
I tagged 3.1, it should fix this issue.

**Comment by ThatHai** [comment]
Verified fix with v3.1
