### ISSUE TITLE
Introduce local variable

### ISSUE THREAD

**Issue by fnzen** [emacs-lsp/lsp-java#265]
Is it possible to introduce a variable in lsp-java like in IntelliJ IDEA?

For example when I have the code:
```java
StringBuffer sb = new StringBuffer();
sb.append("abc");
sb.toString();
```

When the cursor is now at the beginning of the line `sb.toString();`, in IntelliJ IDEA introduce variable would generate `String s = sb.toString();`.

**Comment by ericdallo** [comment]
I think this a code action, the eclipse jdtls should return this code action, @yyoncho do you know if this code action exists?

**Comment by yyoncho** [comment]
Use `lsp-java-extract-to-local-variable` from with cursor at `;`.

**Comment by fnzen** [comment]
Thanks @yyoncho and @ericdallo for the quick answer! It works :). Introduce variable is a feature I use very often.

The code action would recommend `string` as variable name. Is it possible that no such recommendation is provided, but the input field for the name is always empty so that I can directly type a name? Otherwise I always have to delete `string` first and then provide my desired variable name.

**Comment by fnzen** [comment]
In certain cases the default naming is of course good/helpful, e.g. when I call the method `getMyList` and then the variable is named `myList`.
