### ISSUE TITLE
Emacs freezing with maven multi-module + npm project when auto build enabled

### ISSUE THREAD

**Issue by huangfeiyu** [emacs-lsp/lsp-java#267]
Hi, my maven multi-module java project includes more than 20k files, also it uses the maven plugin **frontend-maven-plugin** for **npm**, **gulp** and **webpack**. Emacs freezes when I save changes to a java source file. I tried Ctrl+G, it doesn't help, so doesn't with three ESC. During the frozen, I found the npm gulp processes are running and they consume 30 ~ 40 percent cpu. After I disable the auto build function by set **lsp-java-autobuild-enabled** to nil, the issue disappear. However, I really like the auto build function, so I am here asking you if there is a better way to solve my issue. From https://github.com/eirslett/frontend-maven-plugin, we can purposefully disable **npm** **gulp** and **webpack** during maven build by add maven command line arguments _-Dskip.npm_, but I don't find a way to specify maven command line arguments in lsp-java. I tried **lsp-java-vmargs**, it doesn't work. Any suggestion would be appreciated! 
By the way, lsp-java is great, I've already use it in my everyday's work.

**Comment by yyoncho** [comment]
I don't think that jdtls is running maven builds but it is using maven to calculate the source folders and deps. Most likely this is happening during the import of the project but generally, that should not block emacs. 

1. Can you confirm that you are able to reproduce with https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el ?
2. In case it does, can you provide a sample project to reproduce the issue with?

**Comment by huangfeiyu** [comment]
@yyoncho Thank you for replying me so quickly. I tried start emacs with the lsp-start-plain.el, I have trouble to download the packages due to the bad network condition. I'll try latter. When I encounter the problem I almost use the same emacs configuration as the Quick Start in readme.md, would you mind check out my emacs configuration? Here's my configuration:
``` lisp
(tool-bar-mode -1)
(package-initialize)
(add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))
(add-to-list 'package-archives '("melpa-stable" . "http://melpa-stable.milkbox.net/packages/"))
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
(projectile-mode +1)
(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)

(require 'helm)
(require 'helm-config)
(global-set-key (kbd "C-c h") 'helm-command-prefix)
(global-unset-key (kbd "C-x c"))
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "C-x b") 'helm-mini)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(setq helm-M-x-fuzzy-match t) ;; optional fuzzy matching for helm-M-x
(setq helm-autoresize-max-height 0)
(setq helm-autoresize-min-height 20)
(setq helm-buffers-fuzzy-matching t
      helm-recentf-fuzzy-match    t)
(helm-autoresize-mode 1)
(helm-mode 1)
(projectile-global-mode)
(setq projectile-completion-system 'helm)
(require 'helm-projectile)
(helm-projectile-on)
(require 'lsp-java)
(add-hook 'java-mode-hook #'lsp)
(require 'cc-mode)

(condition-case nil
    (require 'use-package)
  (file-error
   (require 'package)
   (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
   (package-initialize)
   (package-refresh-contents)
   (package-install 'use-package)
   (require 'use-package)))

(setq use-package-always-ensure t)

(use-package projectile)
(use-package flycheck)
(use-package yasnippet :config (yas-global-mode))
(use-package lsp-mode :hook ((lsp-mode . lsp-enable-which-key-integration))
  :config (setq lsp-completion-enable-additional-text-edit nil))
(use-package hydra)
(use-package ag)
(use-package company)
(add-hook 'after-init-hook 'global-company-mode)

(push 'company-lsp company-backends)
(use-package lsp-ui)
(use-package which-key :config (which-key-mode))
(use-package lsp-java :config (add-hook 'java-mode-hook 'lsp))
(use-package dap-mode :after lsp-mode :config (dap-mode t) (dap-ui-mode t))
(use-package dap-java :ensure nil)
(add-hook 'dap-stopped-hook
          (lambda (arg) (call-interactively #'dap-hydra)))
;;(use-package helm-lsp)
(use-package helm
  :config (helm-mode))
(use-package lsp-treemacs)
(with-eval-after-load 'lsp-mode
  ;; don't scan 3rd party javascript libraries
  (push "[/\\\\][^/\\\\]*\\.\\(json\\|html\\|jade\\)$" lsp-file-watch-ignored) ; json
  (push "/target/.*" lsp-file-watch-ignored) ; target
  (push "/node/.*" lsp-file-watch-ignored) ; node
  (push "/node_modules/.*" lsp-file-watch-ignored) ; node
  )
(setq lsp-java-vmargs '("-noverify" "-Xmx1G" "-XX:+UseG1GC" "-XX:+UseStringDeduplication" "-Dskip.npm" "-Dskip.gulp" "-Dskip.webpack"))
(setq lsp-java-autobuild-enabled nil)
(add-hook 'java-mode-hook 'display-line-numbers-mode)

(setq-default tab-width 4)
(setq-default cursor-type 'bar)

(global-set-key (kbd "s-d d") 'dap-debug)
(global-set-key (kbd "s-d l") 'dap-debug-last)
(global-set-key (kbd "C-x C-b") 'ibuffer)
(put 'downcase-region 'disabled nil)
(put 'upcase-region 'disabled nil)
```

**Comment by huangfeiyu** [comment]
It seems this is an issue of **eclipse** **m2e** and **frontend-maven-plugin**, there is a open issue https://github.com/eirslett/frontend-maven-plugin/issues/164

**Comment by huangfeiyu** [comment]
fixed the issue by configure the variable `lsp-file-watch-ignored` to ignore the directories which store the files generated by npm, webpack, but directories in src.
