### ISSUE TITLE
lsp-java is not automatically installing the Eclipse JDT Language Server, with the emacs command: M-x lsp-install-server

### ISSUE THREAD

**Issue by zeta-00** [emacs-lsp/lsp-java#273]
it's throwing this error:
user-error: There are no servers with automatic installation, and it shows LSP[Disconnect] in emacs, how would you recommend that i troubleshoot this ?

note: i'm using emacs 27.1, and my $JAVA_HOME and $PATH environment variables are set for my openjdk installation, so i don't know what else i could be missing ?

**Comment by yyoncho** [comment]
Most likely lsp-java is not installed or you don't use latest version of everything. Please, try to verify it with the quick start script.

**Comment by yyoncho** [comment]
I am marking it as closed, but you can use it for further questions.
