### ISSUE TITLE
Feature request : improve system portability to mswindows

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-java#274]
Hello,

I had this issue emacs-lsp/dap-mode#321 when running test.

I found out it was `dap-java` function : 
```elisp
(defvar dap-java--var-format (if (string= system-type "windows-nt")
                                  "%%%s%%"
                                "$%s"))
``` 
returning an incorrect value for my particular system.

The variable `system-type` returns  `windows-nt` for me. However, I run `emacs` from within `mingw64`, so that the
command issued by emacs to run test is run under `mingw64` shell which behaves as linux, not ms-dos. Then, the command fails because `%JUNIT_CLASS_PATH%` is not understood.

If I manually change the upper function so that it returns $JUNIT_CLASS_PATH, the test succeeds as usual.

Then, I would recommend to improve the test within the upper function to better match all possibilities, here is
what I did : 
```elips
(defvar dap-java--var-format (if (string= system-type "windows-nt")
                                     (if (string-match-p "mingw32" system-configuration)
                                           "$%s"
                                 "%%%s%%")
                               "$%s"))
``` 

I think it can be useful for other persons which may run emacs on windows 10 under its linux subsystem, I do not know how this latter works, but it could be an issue for this one as well.

Regards

**Comment by yyoncho** [comment]
Sorry, I don't use windows. If you think that this will improve lsp-java you may open PR and hopefully, someone using windows can verify it.

**Comment by deb75** [comment]
Hi,

In my case, `dap-java` will not work without the above change on emacs/msys2/windows10.

But I think windows10 users will not have this issue if they use emacs 27.1 for windows, independently of msys2.

**Comment by deb75** [comment]
Closing. Fixed by launching emacs outside of `msys2`
