### ISSUE TITLE
Question : how to blacklist some directories within a project

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-java#275]
I have a project with some java and python source files in separate directories like : 
```
src/main/java/...
src/main/python/...
```

Furthermore, the lsp python language server creates some `.mypy_cache` directories inside the python directories.

When the java server language starts, I notice it creates some watches for python source directories and  `.mypy_cache` ones.

Is it possible to tell the java server language not to watch into some directories, like those `"*/python/*"` and  `"*/.mypy_cache/*"` ?

Regards

**Comment by yyoncho** [comment]
use `lsp-file-watch-ignored`

**Comment by deb75** [comment]
Thanks !
