### ISSUE TITLE
modeline breaks sometimes

### ISSUE THREAD

**Issue by aconchillo** [emacs-lsp/lsp-java#276]
I'm not sure if this is lsp-java or lsp-mode, but since I'm working with Java I'm reporting here.

**Describe the bug**

- Emacs 27.1 (from Homebrew) in iTerm2/tmux.
- lsp-mode 20200915.1507
- lsp-java 20200911.522
- lsp-ui 20200916.1208

Sometimes my modeline breaks, see screenshot. This is usually after some completion or may be some javadoc hover I'm not really sure yet.

It looks like the light bulb character has something to do with it. When this happens I have more than one emacs window open.

**To Reproduce**

Note sure how yet.

**Expected behavior**

Modeline doesn't break.

**Screenshots**

![Screen Shot 2020-09-17 at 1 02 54 PM](https://user-images.githubusercontent.com/951761/93522674-b3260000-f8e6-11ea-9175-1ab432500e99.png)

**Comment by ericdallo** [comment]
I didn't know about this lightbulb image :thinking: only the modeling code action: https://emacs-lsp.github.io/lsp-mode/page/main-features/#code-actions-on-modeline

**Comment by yyoncho** [comment]
can you provide a bit bigger picture? Is this lightbulb in the buffer?

**Comment by aconchillo** [comment]
A little bit more info to reproduce.

- Load a java file (in this case an interface), lsp-mode connects to the LSP server. Only one emacs window for now.
- At the left I see a 0% that becomes:

![Screen Shot 2020-09-17 at 1 19 33 PM](https://user-images.githubusercontent.com/951761/93524070-ce920a80-f8e8-11ea-8d7b-193b425b9d27.png)

- Then, I create another window and it might be (depending on the window size) that the following happens:

![Screen Shot 2020-09-17 at 1 18 35 PM](https://user-images.githubusercontent.com/951761/93524244-1022b580-f8e9-11ea-85c1-b2018346f3e5.png)

After that I'm not sure yet.

**Comment by aconchillo** [comment]
> can you provide a bit bigger picture? Is this lightbulb in the buffer?

no, it's in the modeline. since it's a terminal i can't really hover over with the mouse. i'm not sure what the numbers 3858/34/42 are, but it seems related because both the light bulb and those numbers show up. Looks like LSP server is doing some code analysis because numbers start from low and keep increasing until done.

**Comment by yyoncho** [comment]
I am a bit confused... I am looking at the last two pictures and I am struggling to see anything "broken" on them. If there is no enough place on your modeline emacs will cut some of the info on it. This is the expected behavior.

**Comment by yyoncho** [comment]
check this for a brief description on lsp-mode UI elements https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/

**Comment by aconchillo** [comment]
I believe it's related with treemacs. Because I'm trying to reproduce without it and I can't:

![Screen Shot 2020-09-17 at 1 32 19 PM](https://user-images.githubusercontent.com/951761/93525005-3a28a780-f8ea-11ea-9278-07e1261f62c8.png)

Let me make sure and I'll close the issue in a bit.

**Comment by yyoncho** [comment]
I think I can see what is the issue on the last screenshot. I would say that this is emacs bug - there shouldn't be a way to put a char there, no matter what we do in the modeline.

**Comment by aconchillo** [comment]
> check this for a brief description on lsp-mode UI elements https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/

I'll try that. I just remembered you tweeted about this new tutorial. Thanks!

**Comment by yyoncho** [comment]
I think that if you remove 'icon from lsp-modeline-code-actions-segments it will go away.

**Comment by aconchillo** [comment]
So far this fixes the issue:

```
(setq lsp-modeline-code-actions-enable nil)
(setq lsp-modeline-diagnostics-enable nil)
```

And you suggestion did too:

```
(setq lsp-modeline-code-actions-segments '(count))
```

Thank you!

So do you think is an issue with high unicode code points?

**Comment by yyoncho** [comment]
> So do you think is an issue with high unicode code points?

Yes(or with all-the-icons which we use opportunistically). In combination with TUI. I guess it is either a bug or a limitation.

**Comment by aconchillo** [comment]
OK, closing this. Thank you for the help!
