### ISSUE TITLE
Annoying ^M in dap-debug output

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-java#279]
Hello,

When I launch `dap-debug` on a main java method, the lines of the output buffers are terminated with ^M character.

It is not preventing me for using `dap-java` but I would prefer not to see them.

Currently, what I do is to set the buffer writable and apply the function : 
```lisp
(defun dos2unix ()
  "Replace DOS eolns CR LF with Unix eolns CR"
  (interactive)
  (goto-char (point-min))
  (while (search-forward "\r" nil t) (replace-match "")))
```

Would it be possible to make this automatic when `dap-debug` opens a buffer ? But there may be nicer ways to get rid of ^M's than this one (?)

Regards

**Comment by yyoncho** [comment]
check this: https://stackoverflow.com/questions/730751/hiding-m-in-emacs

**Comment by deb75** [comment]
This is precisely where I picked up the `dos2unix` function :-)

**Comment by yyoncho** [comment]
> Would it be possible to make this automatic when dap-debug opens a buffer ? 

It is possible but it is not something that the package should do.

**Comment by deb75** [comment]
No more relevant, closing.
