### ISSUE TITLE
File watch functionality renders Emacs unusable

### ISSUE THREAD

**Issue by david** [emacs-lsp/lsp-java#28]
After updating to the most recent lsp-java, I am unable to open any java files because when I try it, Emacs immediately complains about an excessive number of files being open. I can't then do anything to debug because Emacs doesn't let me.

Setting `lsp-java-enable-file-watch` to `nil` fixes the problem.

**Comment by yyoncho** [comment]
Which OS do you use? Also, can you tell the count of the files in that must be watched (files in `src` folder) and files in folders that must not be watched (e. g. `target`)?

**Comment by david** [comment]
@yyoncho I'm using OSX. I have 66 java files inside `src/` and 186 files in `target/`.

**Comment by yyoncho** [comment]
@david  sorry for being unclear, can you tell me the number of files that are anywhere but in src (e. g. `.node_modules` , `.git`). I want to determine what is the number of files/directories that was watched. I am trying to understand whether limiting the watches only to `src` folder will fix the issue. If ~200 files are causing "excessive number of files being open" I cannot provide other solution but disable file watch functionality.

**Comment by david** [comment]
@yyoncho oh, sorry, my fault, I misread your question. There are 4242 files outside the `src/` dirs currently (this is a multi-module project).

**Comment by yyoncho** [comment]
Thanks for the reply. I will have to extend the support in `lsp-mode` to provide an option to skip non-source folders.

**Comment by yyoncho** [comment]
If you edit a file outside of emacs it will notify language server and you will be able to see the errors in the flycheck buffer. Also, if you change a build file it will trigger an update of your configuration.

**Comment by david** [comment]
Understood. That does more than auto-revert-mode indeed. Thanks for enlightening me.

**Comment by Alexander-Miller** [comment]
Are you watching directories or single files? If it's the latter putting the watch on directories instead should help reduce the amount of watches started (unless it's doing the same thing under the hood).

When watching a directory you can also watch for changes in all the files in the directory (non-recursively). It's the method treemacs uses in its filewatch mode.

**Comment by yyoncho** [comment]
@Alexander-Miller I am creating recursive watches for all of the directories since lsp watch functionality is passing a glob pattern, e. g. `root-folder/**/*.java` . I am planning to add `ignore-paths` so paths like `.git` could be ignored.

**Comment by yyoncho** [comment]
Fixed with https://github.com/emacs-lsp/lsp-mode/commit/496607c4e577876dd4ec84e9c68376ce22ae6608 . There is ignore directories setting which you can use to skip the files that you are not interested in(the big one).
