### ISSUE TITLE
Wrong type argument: plistp

### ISSUE THREAD

**Issue by gnumonk** [emacs-lsp/lsp-java#280]
**Describe the bug**
Using springboot project, lsp-java show plistp warning when document show via lsp-ui.

**Note**
Before logging the bug please make sure that the issue is reproducible with latest melpa packages and it is reproducible with the clean config(the config from the getting started page.

**To Reproduce**
Create demo project with spring initialiser. 

**Expected behavior**
There should not be any warning while seeing the document (Alt+m h h)

**Screenshots**
<img width="1786" alt="Screenshot 2020-09-23 at 5 30 42 PM" src="https://user-images.githubusercontent.com/1131808/94009843-a875da00-fdc2-11ea-8409-37dd09205afc.png">

**Logs**
Debugger entered--Lisp error: (wrong-type-argument plistp (#<hash-table equal 2/2 0x1ffe31e3ac09> . []))
plist-member((#<hash-table equal 2/2 0x1ffe31e3ac09> . []) :kind)
(closure ((object #<hash-table equal 2/2 0x1ffe31e3ac09> . []) t) (prop) (plist-member object prop))(:kind)
funcall((closure ((object #<hash-table equal 2/2 0x1ffe31e3ac09> . []) t) (prop) (plist-member object prop)) :kind)
(setq all (funcall pred it))
(if (not all) (setq continue nil) (setq all (funcall pred it)))
(let ((it (car list))) (if (not all) (setq continue nil) (setq all (funcall pred it))))
(while (and list continue) (let ((it (car list))) (if (not all) (setq continue nil) (setq all (funcall pred it)))) (setq it-index (1+ it-index)) (setq list (cdr list)))
(let ((list list) (continue t) (it-index 0)) (while (and list continue) (let ((it (car list))) (if (not all) (setq continue nil) (setq all (funcall pred it)))) (setq it-index (1+ it-index)) (setq list (cdr list))))
(let ((all t)) (let ((list list) (continue t) (it-index 0)) (while (and list continue) (let ((it (car list))) (if (not all) (setq continue nil) (setq all (funcall pred it)))) (setq it-index (1+ it-index)) (setq list (cdr list)))) (---truthy\? all))
-all\?((closure ((object #<hash-table equal 2/2 0x1ffe31e3ac09> . []) t) (prop) (plist-member object prop)) (:kind :value))
(cond ((ht\? object) (-all\? (let ((keys (ht-keys object))) #'(lambda (prop) (member prop keys))) '("kind" "value"))) ((listp object) (-all\? #'(lambda (prop) (plist-member object prop)) '(:kind :value))))
lsp-markup-content\?((#<hash-table equal 2/2 0x1ffe31e3ac09> . []))
(cond ((lsp-markup-content\? contents) (if render-all (lsp--render-element contents) (lsp--handle-rendered-for-echo-area contents))) ((and (stringp contents) (not (string-match-p "\n" contents))) (lsp--render-element contents)) (t (if (or (lsp-marked-string\? contents) (stringp contents)) (progn (setq contents (list contents)))) (string-join (seq-map #'lsp--render-element (if render-all contents (seq-filter (-andfn #'lsp-marked-string\? (-compose ... ...)) contents))) (if (and (boundp 'page-break-lines-mode) page-break-lines-mode) "\n\f\n" "\n"))))
lsp--render-on-hover-content((#<hash-table equal 2/2 0x1ffe31e3ac09> . []) nil)
(and contents (lsp--render-on-hover-content contents lsp-eldoc-render-all))
(lsp--eldoc-message (and contents (lsp--render-on-hover-content contents lsp-eldoc-render-all)))
(progn (if range\? (progn (setq lsp--hover-saved-bounds (lsp--range-to-region range\?)))) (lsp--eldoc-message (and contents (lsp--render-on-hover-content contents lsp-eldoc-render-all))))
(if hover (progn (if range\? (progn (setq lsp--hover-saved-bounds (lsp--range-to-region range\?)))) (lsp--eldoc-message (and contents (lsp--render-on-hover-content contents lsp-eldoc-render-all)))))
(let ((hover input0) (range\? (if (ht\? hover) (progn (gethash "range" hover)))) (contents (if (ht\? hover) (progn (gethash "contents" hover))))) (if hover (progn (if range\? (progn (setq lsp--hover-saved-bounds (lsp--range-to-region range\?)))) (lsp--eldoc-message (and contents (lsp--render-on-hover-content contents lsp-eldoc-render-all))))))
(closure (cl-struct-lsp--log-entry-tags cl-struct-lsp-session-tags cl-struct-lsp--workspace-tags cl-struct-lsp--registered-capability-tags lsp-mode-menu cl-struct-lsp--folding-range-tags cl-struct-lsp-watch-tags cl-struct-lsp--client-tags lsp--log-lines dap-ui-menu-items company-backends t) (input0) (let ((hover input0) (range\? (if (ht\? hover) (progn (gethash "range" hover)))) (contents (if (ht\? hover) (progn (gethash "contents" hover))))) (if hover (progn (if range\? (progn (setq lsp--hover-saved-bounds ...))) (lsp--eldoc-message (and contents (lsp--render-on-hover-content contents lsp-eldoc-render-all)))))))(#<hash-table equal 1/1 0x1ffe31e36ddd>)
apply((closure (cl-struct-lsp--log-entry-tags cl-struct-lsp-session-tags cl-struct-lsp--workspace-tags cl-struct-lsp--registered-capability-tags lsp-mode-menu cl-struct-lsp--folding-range-tags cl-struct-lsp-watch-tags cl-struct-lsp--client-tag

**lsp-version**
20200922
[demo.zip](https://github.com/emacs-lsp/lsp-java/files/5267966/demo.zip)

**Comment by zeronone** [comment]
I am seeing same error. For turning `lsp-java-boot` fixed it.

It seems `lsp-markup-content?` throws an error when a `MarkedString = string` is passed in.

Upon `hover` the following response is sent.
```
// HoverResponse
export interface Hover {
	contents: MarkedString | MarkedString[] | MarkupContent;
    range?: Range;
}
// MarkedString
type MarkedString = string | { language: string; value: string };
```

According to the logs below, the `HoverResponse` returned from Java Language Server includes both types of `MarkedString` (a plain string and a `{ language: string; value: string }`. However when the plain string is send to `lsp-markup-content?`, it doesn't soft-fail but throws an error. I don't know why the type of the string is `hash-table` and also why it goes to `listp object` branch?

```
`(defun ,(intern (format "lsp-%s?" (s-dashed-words (symbol-name interface)))) (object)
   (cond
    ((ht? object)
     (-all? (let ((keys (ht-keys object)))
              (lambda (prop)
                (member prop keys)))
            ',(-map (lambda (field-name)
                      (substring (symbol-name field-name) 1))
                    required)))
    ((listp object) (-all? (lambda (prop)
                             (plist-member object prop))
                           ',required))))
```

<detail>
<summary>Logs </summary>

```
Debugger entered--Lisp error: (wrong-type-argument plistp (#<hash-table equal 2/2 0x1582bd9a0cb9> "Class that can be used to bootstrap and launch a S..." . []))
  plist-member((#<hash-table equal 2/2 0x1582bd9a0cb9> "Class that can be used to bootstrap and launch a S..." . []) :kind)
  #f(compiled-function (prop) #<bytecode -0x1b966241133d6359>)(:kind)
  -all\?(#f(compiled-function (prop) #<bytecode -0x1b966241133d6359>) (:kind :value))
  lsp-markup-content\?((#<hash-table equal 2/2 0x1582bd9a0cb9> "Class that can be used to bootstrap and launch a S..." . []))
  lsp--render-on-hover-content((#<hash-table equal 2/2 0x1582bd9a0cb9> "Class that can be used to bootstrap and launch a Spring application from a Java main method. By defa..." . []) nil)
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_218>(#<hash-table equal 1/1 0x1582bed0f547>)
  apply(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_218> #<hash-table equal 1/1 0x1582bed0f547>)
  #f(compiled-function (&rest args) #<bytecode 0x57ffe4109e3b155>)(#<hash-table equal 1/1 0x1582bed0f547>)
  #f(compiled-function (result) #<bytecode -0xd80afabf6c46962>)(#<hash-table equal 1/1 0x1582bd9a0c8d>)
  #f(compiled-function (result) #<bytecode -0x6420543da19ebd1>)(#<hash-table equal 1/1 0x1582bd9a0c8d>)
  lsp--parser-on-message(#<hash-table equal 3/3 0x1582bd9a0c37> #s(lsp--workspace :ewoc #s(ewoc :buffer #<buffer *lsp-log: jdtls:212974*> :pretty-printer lsp--log-entry-pp :header [[[... #5 "" #<marker at 28776 in *lsp-log: jdtls:212974*>] #4 DL-LIST #<marker at 28776 in *lsp-log: jdtls:212974*>] [#4 [#5 ... ... #<marker at 396 in *lsp-log: jdtls:212974*>] #s(lsp--log-entry :timestamp "05:36:31 PM" :process-time nil :type outgoing-req :method "textDocument/codeAction" :id 120 :body ...) #<marker at 1 in *lsp-log: jdtls:212974*>] "" #<marker at 1 in *lsp-log: jdtls:212974*>] :footer [[[... #5 ... #<marker at 15969 in *lsp-log: jdtls:212974*>] #4 #s(lsp--log-entry :timestamp "05:36:38 PM" :process-time 313 :type incoming-resp :method "textDocument/hover" :id 125 :body #<hash-table equal 1/1 0x1582bd9a0c8d>) #<marker at 21773 in *lsp-log: jdtls:212974*>] [#4 [#5 ... "" #<marker at 1 in *lsp-log: jdtls:212974*>] DL-LIST #<marker at 28776 in *lsp-log: jdtls:212974*>] "" #<marker at 28776 in *lsp-log: jdtls:212974*>] :dll [[[... #5 ... #<marker at 21773 in *lsp-log: jdtls:212974*>] #4 "" #<marker at 28776 in *lsp-log: jdtls:212974*>] [#4 [#5 ... ... #<marker at 1 in *lsp-log: jdtls:212974*>] "" #<marker at 1 in *lsp-log: jdtls:212974*>] DL-LIST #<marker at 28776 in *lsp-log: jdtls:212974*>] :last-node nil :hf-pp insert) :server-capabilities #<hash-table equal 18/18 0x1582be4b244d> :registered-server-capabilities (#s(lsp--registered-capability :id "5e442dc1-3bfd-40ef-818c-823ed8a5da75" :method "textDocument/rename" :options #<hash-table equal 1/1 0x1582bec5b3e9>) #s(lsp--registered-capability :id "75ccebd9-c06f-4094-aead-0586c098ffaa" :method "textDocument/rangeFormatting" :options nil) #s(lsp--registered-capability :id "54c230f0-9696-4457-9895-ac0e1fc64eac" :method "textDocument/formatting" :options nil) #s(lsp--registered-capability :id "1deaff7b-1bf6-49d4-a309-4c0072d05744" :method "workspace/didChangeWorkspaceFolders" :options nil) #s(lsp--registered-capability :id "edc77978-b29f-4e51-8418-292f6e5db2c1" :method "textDocument/codeAction" :options #<hash-table equal 1/1 0x1582c0d5ba0d>) #s(lsp--registered-capability :id "test-id" :method "workspace/didChangeWatchedFiles" :options #<hash-table equal 1/65 0x1582bf30fd3d>)) :root "/home/arif/projects/readinglist" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x8b1be6f6cac4dd4>) :test\? lsp-java--locate-server-jar) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 5/65 0x1582be4ba26f> :request-handlers #<hash-table equal 1/65 0x1582be4ba395> :response-handlers #<hash-table eql 41/65 0x1582bdc38e35> :prefix-function nil :uri-handlers #<hash-table equal 1/65 0x1582bdb2d60d> :action-handlers #<hash-table equal 11/65 0x1582bdaba8ab> :major-modes (java-mode) :activation-fn nil :priority 0 :server-id jdtls :multi-root t :initialization-options #f(compiled-function () #<bytecode -0x81121764cfee0cc>) :custom-capabilities nil :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x62221989a99c376>) :before-file-open-fn #f(compiled-function (workspace) #<bytecode 0x13030a49bf9ffd20>) :initialized-fn #f(compiled-function (workspace) #<bytecode 0x79b80deb03d02c9>) :remote? nil :completion-in-comments? t :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x1582bdc86601> :download-server-fn lsp-java--ensure-server :download-in-progress? nil :buffers nil) :host-root nil :proc #<process jdtls> :cmd-proc #<process jdtls> :buffers (#<buffer DemoApplication.java> #<buffer ReadingListController.java>) :semantic-highlighting-faces nil :semantic-highlighting-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x1582bdd6d9b1> :watches #<hash-table equal 0/65 0x1582c1530707> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x1582c1530727> :work-done-tokens #<hash-table equal 0/65 0x1582c1267bfb>))
  #f(compiled-function (proc input) #<bytecode -0x12fe8c3f48ce0e96>)(#<process jdtls> "Content-Length: 7145\15\n\15\n{\"jsonrpc\":\"2.0\",\"id\":125,...")
  apply(#f(compiled-function (proc input) #<bytecode -0x12fe8c3f48ce0e96>) (#<process jdtls> "Content-Length: 7145\15\n\15\n{\"jsonrpc\":\"2.0\",\"id\":125,..."))
  explain-pause--wrap-callback(#s(explain-pause-command-record :command process-filter :native nil :parent #s(explain-pause-command-record :command "jdtls" :native nil :parent #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 7005 :entry-snap (24500 56598 225964 131000) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 1) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 2) #f(compiled-function (proc input) #<bytecode -0x12fe8c3f48ce0e96>) #<process jdtls> "Content-Length: 7145\15\n\15\n{\"jsonrpc\":\"2.0\",\"id\":125,...")
  apply(explain-pause--wrap-callback #s(explain-pause-command-record :command process-filter :native nil :parent #s(explain-pause-command-record :command "jdtls" :native nil :parent #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 7005 :entry-snap (24500 56598 225964 131000) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 1) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 2) #f(compiled-function (proc input) #<bytecode -0x12fe8c3f48ce0e96>) (#<process jdtls> "Content-Length: 7145\15\n\15\n{\"jsonrpc\":\"2.0\",\"id\":125,..."))
  #f(compiled-function (&rest callback-args) #<bytecode 0x1c8189137dad3a90>)(#<process jdtls> "Content-Length: 7145\15\n\15\n{\"jsonrpc\":\"2.0\",\"id\":125,\"result\":{\"contents\":[{\"language\":\"java\",\"value\":\"org.springframework.boot.SpringApplication\"},\"Class that can be used to bootstrap and launch a Spring application from a Java main method. By default class will perform the following steps to bootstrap your application:\\n\\n *  Create an appropriate [ApplicationContext](jdt://contents/spring-context-5.3.1.jar/org.springframework.context/ApplicationC...")
```

</detail>

**Comment by yyoncho** [comment]
It will be great if you can provide the responses of both jdtls and bootls

**Comment by zeronone** [comment]
- jdtls
```
[Trace - 11:06:15 PM] Received response 'textDocument/hover - (54)' in 62ms.
Result: {
  "contents": [
    {
      "language": "java",
      "value": "javax.persistence.Entity"
    },
    "Specifies that the class is an entity. This annotation is applied to the entity class.\n\n *  **Since:**\n    \n     *  1.0"
  ]
}
```

- bootls
```
[Trace - 11:06:15 PM] Received response 'textDocument/hover - (54)' in 2ms.
Result: {
  "contents": []
}
```

- Using single language server (jdtls without bootls) fixes the issue, however the jdtls `textDocument/hover` response is the same.

**Comment by yyoncho** [comment]
proposed fix at https://github.com/yyoncho/lsp-mode/tree/hover-java

**Comment by zeronone** [comment]
I just checked the new changes, and it works well :+1:

**Comment by yyoncho** [comment]
fixed in latest
