### ISSUE TITLE
Decompile garbled!

### ISSUE THREAD

**Issue by vanniuner** [emacs-lsp/lsp-java#281]
**Describe the bug**
I use M-x lsp-goto-implementation , and the code which decompile is garbled!

**Note**
garbled code like this:
@ApiModel(
   value = "\u91d1\u670d\u597d\u517b\u5b9d\u3001\u597d\u79bd\u5b9d\u6388\u4fe1\u54cd\u5e94",
   description = "\u91d1\u670d\u597d\u517b\u5b9d\u3001\u597d\u79bd\u5b9d\u6388\u4fe1\u7533\u8bf7\u54cd\u5e94"
)
The decompile buffer show that  LF UTF-8. Garbled characters are all Chinese.

Is there any configuration to solve this problem?

**Comment by LittleBlackTong** [comment]
你解决这个问题了吗？ 我也遇到了

**Comment by MekaYangyi** [comment]
我也遇到了，怎么解决呢
