### ISSUE TITLE
Symbol’s value as variable is void: lsp-lens-backends

### ISSUE THREAD

**Issue by vanniuner** [emacs-lsp/lsp-java#282]
(require 'lsp-java-boot)
;; to enable the lenses
(add-hook 'lsp-mode-hook #'lsp-lens-mode)
(add-hook 'java-mode-hook #'lsp-java-boot-lens-mode)

output:
funcall-interactively: Symbol’s value as variable is void: lsp-lens-backends

**Comment by yyoncho** [comment]
Should be fixed in latest
