### ISSUE TITLE
want sort the company output

### ISSUE THREAD

**Issue by vanniuner** [emacs-lsp/lsp-java#284]
![截屏2020-10-12 上午11 08 05](https://user-images.githubusercontent.com/7248023/95701176-71853c80-0c7b-11eb-97f2-a9d5ce4142af.png)

The Objec.wait():void is repeated. how to disable it?

**Comment by yyoncho** [comment]
AFAIK there is no such option on the server-side.  Technically, you can filter them out on the client-side.

**Comment by yyoncho** [comment]
check `company-transformers`

**Comment by vanniuner** [comment]
(setq lsp-completion-sort-initial-results t)
(setq lsp-completion-show-detail nil)
