### ISSUE TITLE
Timeout by using `lsp-find-implementation` when the implementation class is  inner class

### ISSUE THREAD

**Issue by ascrutae** [emacs-lsp/lsp-java#288]
AS the title

**Screenshots**
<img width="612" alt="screenshots" src="https://user-images.githubusercontent.com/12436447/97087172-92299b00-165a-11eb-8293-4f2a009ddd90.png">

**Comment by yyoncho** [comment]
1. Increase timeout via lsp-response-timeout
2. Use lsp-treemacs-implementations which is async and does not timeout.
