### ISSUE TITLE
Completes without auto import statement

### ISSUE THREAD

**Issue by uqix** [emacs-lsp/lsp-java#292]
**Describe the bug**
Completes without auto import statement.

**To Reproduce**
1. Emacs v27.1
2. lsp-java latest
3. Use config from quick start of this package
4. Edit some .java file, type `LocalDateT`, select `LocalDateTime`, no `import` generated

**Expected behavior**
Auto import the selected class

**Screenshots**
![image](https://user-images.githubusercontent.com/10142314/98633860-431f7d80-235d-11eb-83ab-233afe328c6f.png)

**Comment by uqix** [comment]
BTW, sometimes I need to manually exe `lsp-completion-mode` after opening some files

**Comment by rrudakov** [comment]
Can confirm this. After creating new java class completion doesn't work until I explicitly run `M-x lsp`, but the rest of functionality works fine (diagnostics, refactoring etc.)

**Comment by rrudakov** [comment]
Looks like the issue with lsp-mode itself. I can reproduce it with java and rust projects with `lsp-start-plain.el`.

Steps to reproduce:
1. Open first file in the project - completion works
2. Open second or create new file in the same project - completion doesn't work until run `M-x lsp` manually

**Comment by rrudakov** [comment]
I've found bad commit. I've reverted https://github.com/emacs-lsp/lsp-mode/commit/bd5c782cbecddde88c9e054b53a3db745fb6d8d7 locally and issue is gone. @yyoncho

**Comment by uqix** [comment]
![image](https://user-images.githubusercontent.com/10142314/102003147-7f6c4200-3d3e-11eb-85a0-7c0e490e7f53.png)

With versions above, the problem still exists for me

**Comment by uqix** [comment]
Just figured it out: I literally copied the demo configuration which disables the auto-import, commenting out `:config (setq lsp-completion-enable-additional-text-edit nil)` will make it work.

```lisp
(use-package lsp-mode :hook ((lsp-mode . lsp-enable-which-key-integration))
  :config (setq lsp-completion-enable-additional-text-edit nil))
```

**Comment by kipcd** [comment]
Just stumbled upon this too. @rrudakov Maybe makes sense to remove this setting from Quick start configuration example in Readme? Why would this important feature be disabled from start?

**Comment by rrudakov** [comment]
I'm not the maintainer :) but I believe anybody can open PR with updated README.
