### ISSUE TITLE
Classpath not found when running dap-java-run-test-method

### ISSUE THREAD

**Issue by vicky08** [emacs-lsp/lsp-java#300]
**Describe the bug**
I have a huge project that I am working and it has more than 40000 files. I have set up watchers and removed the file limits via `lsp-file-watch-threshold`. 
After I see "ServiceReady" in the *lsp-log*, I open a test file and run `dap-java-run-test-method`. This shows the following message:

```
LSP :: Please open an issue in lsp-mode for implementing `vscode.java.resolveClasspath'.

(error "Failed to resolve classpath: example-package does not exist")
dap-java-run-test-method: Wrong type argument: listp, #("LSP :: Please open an issue in lsp-mode for implementing `vscode.java.resolveClasspath'.

(error \"Failed to resolve classpath: example-package does not exist\")" 0 3 (face error))

```
After I open the pom.xml of the particular package example-package for which it is complaining and run `lsp-java-update-project-configuration`, the error goes away for this particular module goes away and I get a new error for example-package2. I had to keep doing this for many such packages until I finally gave up because the codebase is huge. 

I am running

-  spacemacs 0.300(develop branch) 

- on emacs 26.3

- lsp-java-20201105.1758/

**Comment by yyoncho** [comment]
can you try running `,cc` to compile the project?

**Comment by vicky08** [comment]
Error occured while building workspace. Details: 
 message: The project cannot be built until build path errors are resolved; code: 0; resource: ****
 message: The container 'Maven Dependencies' references non existing library '***'; code: 964; resource: ***
 message: Failed to read artifact descriptor for ***

and many more errors..

**Comment by yyoncho** [comment]
What do you see in lsp-treemacs-errors-list? If there are issues with building the project they should be fixed first.

**Comment by vicky08** [comment]
The project builds fine with maven on the command line. It is Emacs and lsp mode which complain and show errors.

**Comment by yyoncho** [comment]
Emacs is just a frontend. It passes the project to the language server and then the language server tries to compile it. There are multiple reasons that might cause failure to build in the language server but successful build via command line.

**Comment by vicky08** [comment]
Should this be a bug in the language server then?

**Comment by yyoncho** [comment]
First, check the lsp-treemacs-errors-list, it will give you pointers on what is wrong.

**Comment by yyoncho** [comment]
I mean, in the end, it might be something on your side - e. g. wrong project root select, language server using different m2 settings, etc.

**Comment by vicky08** [comment]
I can confirm that the root selection is fine. I also ran lsp-java-workspace-remove-folder and re-selected the project root properly. The whole thing works fine with intellij idea. 
Let me check the m2 settings on the language server. Do you know how to look for it?

**Comment by vicky08** [comment]
Meanwhile here are some errors in the lsp-log:
1. Since this is a big project, I see that the file watchers are not started fully:
```
Failed to create a watch for File watching not possible, no file descriptor left: 975: message
```
2. Test runner has an error
```
Contains: Failed to get bundleInfo for bundle from ~/.emacs.d/.cache/lsp/eclipse.jdt.ls/bundles/com.microsoft.java.test.runner.jar
```

**Comment by yyoncho** [comment]
> Contains: Failed to get bundleInfo for bundle from ~/.emacs.d/.cache/lsp/eclipse.jdt.ls/bundles/com.microsoft.java.test.runner.jar

This was alread reported, I havent investigated it. 

> Failed to create a watch for File watching not possible, no file descriptor left: 975: message

Most likely ulimit is not big enough on your system. Either increase it or disable file watches.

**Comment by yyoncho** [comment]
> I can confirm that the root selection is fine. I also ran lsp-java-workspace-remove-folder and re-selected the project root properly. The whole thing works fine with intellij idea as well

Still, what are the errors in lsp-treemacs-errors-list (you may narrow them to error level via `=`)

**Comment by vicky08** [comment]
> > Contains: Failed to get bundleInfo for bundle from ~/.emacs.d/.cache/lsp/eclipse.jdt.ls/bundles/com.microsoft.java.test.runner.jar
> 
> This was alread reported, I havent investigated it.
> 
> > Failed to create a watch for File watching not possible, no file descriptor left: 975: message
> 
> Most likely ulimit is not big enough on your system. Either increase it or disable file watches.

I have increased the ulimit to the max.. still same. I am on a mac.

What is the consequence of disabling file watching? will this affect anything?

**Comment by yyoncho** [comment]
> What is the consequence of disabling file watching? will this affect anything?

Yes. For example, if you touch something under src/test/resources jdtls won't detect that and it won't built it and you have to manually call `,cc` (or full rebuild via `SPC u , cc`, not sure). For the sake of making things work, turn off the watches for now.

**Comment by vicky08** [comment]
The `lsp-treemacs-errors-list` is an interesting one. I am working on the errors. I will report back here with my findings. Basically, some of the packages are unable to resolve other packages. When I run `lsp-java-update-project-configuration` on the unresolvable pom.xml the number of errors seems to be going down

**Comment by yyoncho** [comment]
IDK why jdtls is not picking them...

but still, we have to figure out why jdtls is not picking the test extension. Maybe we have to upgrade it, I will test on my side with the latest jdtls.

**Comment by yyoncho** [comment]
I confirm the issue - the latest JDTLS does not load the tests bundle, I will fix it.

**Comment by yyoncho** [comment]
test bundle loading should be fixed in latest.
