### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-java#304]
In the newest `lsp-java`, there is a line appearing at the top of the buffer which displays the project structure up to the current file.

Sometimes, this project structure is underlined by small red/organge waves, sometimes not.

What is the meaning of these underlines ?

**Comment by yyoncho** [comment]
It means it has error/warning/info diagnostics under that path.

**Comment by deb75** [comment]
Thanks for your answer.

This is strange however because sometimes it is red underlined up to the file even if `lsp-ui-flycheck-list` does not report any error.

**Comment by yyoncho** [comment]
It shows the errors only for the current fille so it is expected.
