### ISSUE TITLE
Build project

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-java#305]
I rely on `maven` to package and install my projects. It is possible to invoke maven through `projectile` (C-c p c).

I noticed that in doing so, `lsp-java` also tries to compile the project in the same time, probably because `maven`
begins to clean the `target` directory before compiling.

For huge projects, I noticed it can slow down significantly the compilation on the `maven` side. Is there a way
to make `lsp-java` play well when project is built from outside `lsp-java` ?

Regards

**Comment by yyoncho** [comment]
You may turn off autobuild. But then, when you modify files outside of emacs you have to manually trigger a build from lsp-java.

**Comment by deb75** [comment]
Thanks !

I think I can use that : disable autobuild before invoking maven and renabling it afterwards.

Is it possible to disable autobuild on the fly ?  I checked C-c l T, so far there are no commands to toggle autobuild.
