### ISSUE TITLE
Question/Request: Exclude test classes from call hierarchy

### ISSUE THREAD

**Issue by ThatHai** [emacs-lsp/lsp-java#312]
Currently, `lsp-treemacs-call-hierarchy` returns the hierarchy of **all** callers, including calls from test classes. On most projects I work, the vast majority of calls are from test classes, which makes it hard to find "real" information in the call hierarchy.

According to [this post](https://stackoverflow.com/questions/9321408/hide-unit-tests-from-call-hierarchy), it's possible to filter out test code from the call hierarchy in Eclipse.

I wonder if `lsp-java` could pass something to `jdtls` to tell it not to include test code in the call hierarchy?

**Comment by yyoncho** [comment]
> I wonder if `lsp-java` could pass something to `jdtls` to tell it not to include test code in the call hierarchy?

the method is part of lsp spec which means that jdtls cannot(or at least they won't want) to extend the method. What we can do is to create ability to apply client side filter which they you can use to filder whatever information you want.

**Comment by ThatHai** [comment]
> What we can do is to create ability to apply client side filter which they you can use to filder whatever information you want.
Could you elaborate more on this? I'm not an elisp programmer, but if you gave enough details, I may be able to implement it. In particular, I don't know the data structure returned by the lsp call, and where to filter before the result gets displayed.

**Comment by yyoncho** [comment]
@ThatHai I implemented it here - https://github.com/emacs-lsp/lsp-treemacs/commit/50ddaba4cf62009520c43376987e3352a6855fb5

**Comment by yyoncho** [comment]
I will push it to the master after some more testing.

**Comment by yyoncho** [comment]
The fix is in the master.
