### ISSUE TITLE
How to get the signature of a method?

### ISSUE THREAD

**Issue by vanniuner** [emacs-lsp/lsp-java#316]
How to get the signature of a method?
I want to get the return value of the method, and use macro for easier to code.

![截屏2021-02-16 下午1 33 35](https://user-images.githubusercontent.com/7248023/108022501-9f302700-705b-11eb-8f9e-d41bebbe08f0.png)

**Comment by yyoncho** [comment]
There is no well defined protocol to get that date, most of the information comes in human-readable format.

**Comment by vanniuner** [comment]
tsk, Looking forward to similar features.
