### ISSUE TITLE
Why are indent format settings ignored?

### ISSUE THREAD

**Issue by lhindir** [emacs-lsp/lsp-java#318]
In my config, I have
```elisp
(setq lsp-java-format-settings-url "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml"
      lsp-java-format-settings-profile "GoogleStyle")
```

I think this is working, because I've tried with a local file URI with a different lineSplit and that seems to function; however, 
`lsp-format-buffer` still seems to format with an indentation of 2.

When I start the language server, I get:
```
Note: c-basic-offset, tab-width, evil-shift-width adjusted to 2
```

Edit: this is from `dtrt-mode`, but my question in the comment below is still relevant

Why would this be preferred over the XML prefs? The Google style uses indentation.size 4. I searched the repo for c-basic-offset but couldn't find any code forcing this. How can I get lsp-java to obey the formatting rules completely?

Thank you for this excellent package!

**Comment by lhindir** [comment]
Ok, I found some [docs](https://github.com/emacs-lsp/lsp-mode/blob/f306b1a782eb07c773bdc8b5f39cb273f6acda36/docs/page/main-features.md#formatting) in the lsp-mode repo.

Is there a way to configure lsp-mode such that it doesn't use or modify these variables?

**Comment by yyoncho** [comment]
> Is there a way to configure lsp-mode such that it doesn't use or modify these variables (and so the formatter would successfully indent the file)?

Using `(setq-default c-basic-offset 4)` should be good enough. The field is required by the spec so we cannot ignore it. Maybe there is an option to tell that on jdtls level but I am not aware of it.

**Comment by lhindir** [comment]
> The field is required by the spec so we cannot ignore it. Maybe there is an option to tell that on jdtls level but I am not aware of it.

Does this mean jdtls imports all the format settings except the indent ones? Why would it ignore those? It seems to me like users would want the specified format settings XML to override all editor-wide settings, but maybe I'm misunderstanding.

eclipse/eclipse.jdt.ls/pull/640 was all I could find related to this but I couldn't seem to find if the indentation settings were specified to be ignored.

Sorry for my ignorance, but could you clarify the situation a bit more for me?
