### ISSUE TITLE
lsp-java reuses the same connection for different projects and loads inactive projects

### ISSUE THREAD

**Issue by thanhvg** [emacs-lsp/lsp-java#320]
**Describe the bug**
- All java projects are treated as one single project and get loads all when a project is opened. 
- Only one single instance of lsp-java is used for all opened java projects
- Something wrong with how lsp-java interacts with lsp--session

**Note**
OS: Ubuntu 20.04
Java 11
Emacs 27, Spacemacs dev with all packages up to date with lsp and lsp java on

**To Reproduce**
- delete `~/.emacs/.lsp-session-v1` to reset `lsp--session`
- clone https://github.com/spring-guides/tut-react-and-spring-data-rest to ~/git/tut-react-and-spring-data-rest
- clone https://github.com/spring-guides/tut-rest to ~/git/tut-rest
- open each of these projects in Spacemacs, make sure their correct project roots are recognized by lsp and let lsp-java analyze them for some time.
- close Spacemacs and open Spacemacs again
- in Spacemacs open just one file from either of the two projects above: 
`~/git/tut-rest/evolution/src/main/java/payroll/Employee.java` and wait for lsp-java to be ready. which may take some time.
- do `lsp-treemacs-errors-list` notice the other project is loaded also
![image](https://user-images.githubusercontent.com/10945297/111418774-e850b680-86ad-11eb-99c0-82e086f03da1.png)
- notice that the diagnostics on mode line now show warning number which is a total of two projects (30). 
- do `lsp-describe-session`
![image](https://user-images.githubusercontent.com/10945297/111419102-74fb7480-86ae-11eb-85ad-034bd240765a.png)
notice that two projects are loaded by a single one lsp server instance (same ID 140834) and both projects has the same buffer name though only one file of one project is opened in emacs.
- close emacs and delete `~/.emacs/.lsp-session-v1` to reset `lsp--session`
- start emacs and open `~/git/tut-rest/evolution/src/main/java/payroll/Employee.java`. `lsp-java` now is only aware of only one java project and it won't load the other. Something goes wrong with how `lsp-java` interacts with `lsp--session`

**Expected behavior**
lsp-java should only load the active project. Somehow it loads all java projects it is aware of and lumps them all together into a single one.

**PS**
Otherwise everything else is awesome. If you are busy show me some leads to fix.

Thanks

**Comment by yyoncho** [comment]
This is the expected behavior, there is a faq entry https://emacs-lsp.github.io/lsp-mode/page/faq/ how to start multi root server for only one folder initially. 

https://emacs-lsp.github.io/lsp-mode/page/faq/

> How do I force lsp-mode to forget the workspace folders for multi root servers so the workspace folders are added on demand?
> (advice-add 'lsp :before (lambda (&rest _args) (eval '(setf (lsp-session-server-id->folders (lsp-session)) (ht)))))

**Comment by thanhvg** [comment]
Sorry my bad, didn't check the faq thoroughly. But how about closing projects? I have `lsp-keep-workspace-alive` as `nil` but when I close a java project it still keeps watching the project. All the errors and warnings from all projects are still counted as one. The only work around is to open each project in a separate emacs instance. 

Is it possible to make lsp-java to work like a single-root server like python or go? 

Thanks

**Comment by yyoncho** [comment]
> Is it possible to make lsp-java to work like a single-root server like python or go

ATM no.

ATM the only way to achieve what you want is to use M-x lsp-workspace-folders-remove
