### ISSUE TITLE
No definitions found for third party dependencies

### ISSUE THREAD

**Issue by XiangQingW** [emacs-lsp/lsp-java#321]
I'm using the latest melpa packages and latest jdtls, and Xref-find-definitions works well with the Java standard library. However,  Xref-find-definitions doesn't work for third-party dependencies, and it will display the error message: `No definitions found for **`. Thanks.
![截屏2021-04-10 下午1 05 22](https://user-images.githubusercontent.com/7948384/114259151-8f4f1680-99fe-11eb-9506-e2fb957ae6b9.png)

**Comment by yyoncho** [comment]
Try M-x lsp-find-definitions. Also, is the rest of functionality working fine, like `M-x lsp-describe-thing` .

**Comment by XiangQingW** [comment]
lsp-find-definitions also doesn't work, and it'll show the error message `Not found for **`. 
lsp-describe-thing-at-point works fine with the Java standard library, but emacs will show an empty `lsp-help` buffer when lsp-describe-thing-at-point is used for functions of third-party dependencies.

![Lark20210410-161827](https://user-images.githubusercontent.com/7948384/114263501-6b003380-9a18-11eb-84b6-968898e80c65.png)

**Comment by XiangQingW** [comment]
lsp-find-definitions also doesn't work, and it'll show the error message Not found for **.
lsp-describe-thing-at-point works fine with some annotation.
![Lark20210410-162802](https://user-images.githubusercontent.com/7948384/114263699-be26b600-9a19-11eb-9f64-ffc4f57166ec.png)

**Comment by yyoncho** [comment]
AFAICS your project has errors, what are they? Also, check if you have picked the proper project root, do M-x lsp-describe-session and check if the project root has pom/Gradle file.

**Comment by XiangQingW** [comment]
I fix the errors, and then move the demo project from `~/bob/spring-in-action-5-samples/ch02/tacos` to `~/bob/tacos`,  so that the project root is `~/bob/tacos`. The lsp-java works as expected. Thank you very much.
