### ISSUE TITLE
lsp-java seems to have a hard requirement on dap-mode

### ISSUE THREAD

**Issue by Lenbok** [emacs-lsp/lsp-java#325]
**Describe the bug**
I wanted to disable dap-mode, as it globally messes with fringe bindings, due to https://github.com/emacs-lsp/dap-mode/issues/423

I thought it would be sufficient to put `:disabled` into my `(use-package dap-mode)` declaration. However, emacs kept loading dap-mode. It looks like it's getting pulled in by lsp-java. I am using `straight.el` as my package manager.

**To Reproduce**
`(use-package lsp-java)`
Notice that dap-mode is installed and sets up it's bindings.

**Expected behavior**
`(use-package lsp-java)` should not pull in dap-mode as a dependency unless explicitly instructed to.

**Comment by yyoncho** [comment]
you can set lsp-enable-dap-auto-configure to nil. Or you can remove the binding dap-mode as well.

**Comment by Lenbok** [comment]
Thank you for the pointer to `lsp-enable-dap-auto-configure`. Can you please elaborate on what you mean by "remove the binding dap-mode as well"?

**Comment by yyoncho** [comment]
You can remove the bindings that dap-mode is setting like this:
```
(define-key dap-mode-map [left-margin mouse-1] nil)
(define-key dap-mode-map [left-fringe mouse-1] nil)
```

**Comment by yyoncho** [comment]
Generally, just do M-x describe-key, perform the action and you will see the keymap containing the action you want to unbind...

**Comment by Lenbok** [comment]
Thank you. Is it also possible to retain the bindings if the major mode is
derived from prog mode?

**Comment by yyoncho** [comment]
bind it in prog-mode-map
