### ISSUE TITLE
Question: how to disable autocompletion in certain cases? 

### ISSUE THREAD

**Issue by wenhoujx** [emacs-lsp/lsp-java#334]
hello, i wonder if there is an easy way to disable lsp autocompletion in certain cases.

e.g. all java variables starts with lower case, and i prefer use `dabbrev` to complete a previously defined variable if looking-back is a lowercased word, instead of letting jdt server tell me the candidates. 

can someone points me to the right place to implement this feature if possible? thanks

feel free to close if  this is hard. thanks

**Comment by yyoncho** [comment]
Generally, you can put company-dabbrev before company-capf and use company-other-backend when you want lsp-mode completion

**Comment by wenhoujx** [comment]
oh, thanks.
