### ISSUE TITLE
I want to manually configure jdtls

### ISSUE THREAD

**Issue by huangfeiyu** [emacs-lsp/lsp-java#336]
Hi, thank you for your work. I really appreciate!
I have difficult to install jdtls automatically, it seems that network connection to raw.githubusercontent.com:443 can not be established. I tried to use proxy in several ways, none of them worked.
So I hope there is a guide which let me know how to get jdtls as well as the required plugins installed manually.
Thanks again!

**Comment by yyoncho** [comment]
You can find what we are running here: https://github.com/emacs-lsp/lsp-java/blob/master/install/pom.xml

**Comment by huangfeiyu** [comment]
@yyoncho thank you, i ran maven build using the pom.xml, language server works, however debug doesn't. I guess it was because i didn't set the parameters correctly for the following part.
<configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>com.microsoft.java</groupId>
                  <artifactId>com.microsoft.java.debug.plugin</artifactId>
                  <version>0.30.0</version>
                  <outputDirectory>${java.debug.root}</outputDirectory>
                  <destFileName>java.debug.plugin.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>org.junit.platform</groupId>
                  <artifactId>junit-platform-console-standalone</artifactId>
                  <version>1.6.2</version>
                  <outputDirectory>${junit.runner.root}</outputDirectory>
                  <destFileName>${junit.runner.fileName}</destFileName>
                </artifactItem>
              </artifactItems>
            </configuration>
May you give me suggestions? it will be help if you can give a maven build command.

**Comment by yyoncho** [comment]
`/usr/bin/mvn -Djdt.js.server.root\=/home/yyoncho/.emacs.d/.cache/lsp/eclipse.jdt.ls/ -Djunit.runner.root\=/home/yyoncho/.emacs.d/eclipse.jdt.ls/test-runner/ -Djunit.runner.fileName\=junit-platform-console-standalone.jar -Djava.debug.root\=/home/yyoncho/.emacs.d/.cache/lsp/eclipse.jdt.ls/bundles clean package -Djdt.download.url\=https\://download.eclipse.org/jdtls/milestones/1.0.0/jdt-language-server-1.0.0-202104151857.tar.gz`

**Comment by huangfeiyu** [comment]
@yyoncho Now, everything works. Thank you, you saved my day! Would you mind I add manually install lsp server instruction to readme.md?

**Comment by huangfeiyu** [comment]
I wrote an article https://github.com/huangfeiyu/articles/blob/master/emacs/lsp-java/manually_install_jdtls.md, I hope it can help other people who experiences the same issue.

**Comment by yyoncho** [comment]
Looks good, but this bypasses only the first step. In the near future, I am planning to create a zip archieve with all the stuff that we need and put it in github. That way one can simply extract and download the zip.

**Comment by huangfeiyu** [comment]
@yyoncho That sounds great!
