### ISSUE TITLE
Support for `java.import.gradle.wrapper.checksums`?

### ISSUE THREAD

**Issue by c-zx** [emacs-lsp/lsp-java#341]
> LSP :: Security Warning! The gradle wrapper 'gradle-wrapper.jar' could be malicious. If you trust it, please add `{"sha256": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","allowed": true}` to the `java.import.gradle.wrapper.checksums` preference.

Where do I config `java.import.gradle.wrapper.checksums`?

Or does lsp-java need extra works to support `java.import.gradle.wrapper.checksums`, then config it in emacs?

**Comment by yyoncho** [comment]
use lsp-java-imports-gradle-wrapper-checksums

**Comment by c-zx** [comment]
Thanks! That'll work.
