### ISSUE TITLE
lsp-treemacs-call-hierarchy doesn't go to the line cal the method

### ISSUE THREAD

**Issue by huangfeiyu** [emacs-lsp/lsp-java#342]
When press <enter> on the item in the window of callers created by `lsp-treemacs-call-hierarchy`, the cursor doesn't go to the line the method is called,  instead the cursor go to the name of the caller. I think it is better to place the cursor to the line where the method is called.

Sorry, I am not sure if I should report this to lsp-treemacs or here.

**Comment by yyoncho** [comment]
maybe this - https://github.com/eclipse/eclipse.jdt.ls/pull/1824

**Comment by huangfeiyu** [comment]
@yyoncho great! Thank you!
