### ISSUE TITLE
Question about the snippet of `class` keyword.

### ISSUE THREAD

**Issue by alaneuler** [emacs-lsp/lsp-java#347]
After creating a new java class file, the `class` keyword expands with following content:
```
package me.alaneuler.playground;

/**
 * TypeReferenceMain
 */
public class TypeReferenceMain {
    
	${0}
}
```

I have two questions here:
1. what's the `${0}`, it seems its a placeholder not replaced correctly?
2. How do I modify the javadoc above `public class ...` to content (it's just the class name by default) I desire?

**Comment by yyoncho** [comment]
most likely you haven't enabled yasnippet mode.

**Comment by alaneuler** [comment]
> most likely you haven't enabled yasnippet mode.

you are right! but the `${0}` becomes `0` after i enabled yasnippet mode. 

and ... do you know how to edit the `class` snippet?

**Comment by yyoncho** [comment]
> and ... do you know how to edit the `class` snippet?

this way: https://github.com/eclipse/eclipse.jdt.ls/issues/872
