### ISSUE TITLE
how code complete to groupId、artifactId、version in maven pom.xml

### ISSUE THREAD

**Issue by zcjava** [emacs-lsp/lsp-java#348]
i use lsp-java wriite maven java project. how i use lsp-java company-capf implementation like idea func :

![image](https://user-images.githubusercontent.com/1551382/132095679-839e8c60-713e-42e3-b1f5-69b28286b293.png)

**Comment by yyoncho** [comment]
there is xml extension, we have to integrate it. ATM it is not possible

**Comment by zcjava** [comment]
make sure lsp-mode suport it? i integrate it , it will work?

**Comment by yyoncho** [comment]
yes

**Comment by yyoncho** [comment]
@zcjava check vscode what is doing. I believe they have plugin for xml-language-server - https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven

**Comment by zcjava** [comment]
> @zcjava check vscode what is doing. I believe they have plugin for xml-language-server - https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven
i see it .not about emacs integrate it, can u mark video for it . i cannot do it .but i very need it
