### ISSUE TITLE
Project Directory not recognized / found

### ISSUE THREAD

**Issue by CadeMichael** [emacs-lsp/lsp-java#351]
I tried using lsp-java with a basic maven project and whenever I open a java file in the project it asks if the lsp should parse the directory the project dir is in (~/Desktop in my case) and doesn't seem to realize that it is in a java project. Is this standard or is something not working / is configured by me as it should be?

config 
lsp-java, taken from the README
```elisp
(use-package lsp-java :ensure t :config (add-hook 'java-mode-hook 'lsp-deferred))
(use-package dap-mode :ensure t :after lsp-mode :config (dap-auto-configure-mode))
(use-package dap-java :ensure nil)
```

lsp 
```elisp
  (use-package lsp-mode
    :ensure t
    :hook
    (lsp-mode . lsp-enable-which-key-integration)
    (go-mode . lsp-deferred)
    (js-mode . lsp-deferred)
    (haskell-mode . lsp-deferred)
    (lua-mode . lsp-deferred)
    :commands (lsp lsp-deferred)
    :config
    (define-key lsp-mode-map (kbd "C-l C-l") lsp-command-map))

(use-package projectile :ensure t :bind
    (("C-c p f" . projectile-find-file)))
  (projectile-mode +1)
  ;; Recommended keymap prefix on Windows/Linux
  (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
```

thanks,
Cade

**Comment by yyoncho** [comment]
We use projectile to guess the project root and we persist it. Use `I` to correct if projectile has guessed wrong. Use lsp-workspace-folder-add/remove to correct workspace root if you have already confirmed it.

**Comment by CadeMichael** [comment]
Thank you
