### ISSUE TITLE
validation and code complete not work with .properties and .yml file

### ISSUE THREAD

**Issue by lazyskulptor** [emacs-lsp/lsp-java#356]
**Describe the bug**
Auto completion and validation doesn't work. 
If type some properties validation doesn't work correctly.

**To Reproduce**
It just always doesn't work for me. If there are things that I need to check, please let me know.

**Expected behavior**
I want it to show lsp-ui completion substitutes.

**Screenshots**

<img width="719" alt="Screen Shot 2021-10-17 at 7 44 18 PM" src="https://user-images.githubusercontent.com/11717059/137623854-7d1745f1-b3d3-4fe4-8b10-8daefac89c7f.png">

**Logs**
lsp-log prints nothing

Message prints
> lsp--send-request-async: The connected server(s) does not support method textDocument/implementation.
> To find out what capabilities support your server use ‘M-x lsp-describe-session’
> and expand the capabilities section
>

**Comment by credmp** [comment]
From the modeline I would guess you have not yet started the LSP server? For the conf file I have to start it manually. If anyone has a trick to start it for the conf file immediately I am all ears :D

**Comment by yyoncho** [comment]
check what major mode you are using and then `add-hook`. `M-: major-mode RET`

**Comment by credmp** [comment]
@yyoncho I solved it by adding a `.dir-locals.el` to my project:

```
((conf-javaprop-mode-hook
  (eval add-hook 'conf-javaprop-mode-hook #'lsp)))
```

This means that only properties files in this project will be opened with lsp enabled.

**Comment by lazyskulptor** [comment]
> From the modeline I would guess you have not yet started the LSP server? For the conf file I have to start it manually. If anyone has a trick to start it for the conf file immediately I am all ears :D

When I edit other java files in same project all java files work and are connected well with lsp-server. But in conf-javaprop-mode, it doesn't connect to lsp-server. 

> check what major mode you are using and then `add-hook`. `M-: major-mode RET`

major mode is conf-javaprop-mode

**Comment by lazyskulptor** [comment]
There was conflicts with company-backends. 
I removed what I changed and It works well now. 
thank you.
