### ISSUE TITLE
Wrong source folder

### ISSUE THREAD

**Issue by iocanel** [emacs-lsp/lsp-java#36]
In some cases when I open a maven project, which by default has its sources under `src/main/java` lsp-java still things that the source folder is `src`.

This is quite annoying as it suggests prefixing all interal package with main.java.

There is no known way on how to configure the source folder (though for maven I think it makes sense to have it autoconfigured).

**Comment by yyoncho** [comment]
Is your maven project listed in `lsp-java--workspace-folders`?
Can you provide sample project structure?

> This is quite annoying as it suggests prefixing all interal package with main.java.
Can you elaborate a bit more? Are you talking about flycheck error?

**Comment by iocanel** [comment]
Thanks once again for the super fast response.

Let me add the project to the `lsp-java--workspace-folders` and see if that changes things.

**Comment by iocanel** [comment]
I added a hook on java-mode to add the `(projectile-project-root)` to  `lsp-java--workspace-folders` and it seems to work better now.

**Comment by yyoncho** [comment]
You have to make sure that `lsp-java--workspace-folders` are initialized before the first call to `lsp-java-enable` or you have to restart(`lsp-workspace-restart`) the `jdt.ls` server everytime the list of the folders is updated. Note that if a file is not under any of the `lsp-java--workspace-folders` most of the jdt features won't work. I am working on methods which will make the project management easier. Closing based on the previous comment.

**Comment by iocanel** [comment]
Thanks for the info, that will definitely help.
