### ISSUE TITLE
Code completion not working in Spring Boot application.properties

### ISSUE THREAD

**Issue by yejianfengblue** [emacs-lsp/lsp-java#366]
**Describe the bug**
According to [lsp-java readme](https://github.com/emacs-lsp/lsp-java#functionality-for-properties-and-yml), when I type `ser`, code completion should show `server.port` and other properties. However I don't see this completion popup. The test project is just download from https://start.spring.io/ with all default value. The project root is imported when emacs askes.

Below is added to `.emacs.d/init.el`
```lisp
(require 'lsp-java-boot)
;; to enable the lenses
(add-hook 'lsp-mode-hook #'lsp-lens-mode)
(add-hook 'java-mode-hook #'lsp-java-boot-lens-mode)
```

**To Reproduce**
Emacs version 27.2. 
```lisp
(condition-case nil
    (require 'use-package)
  (file-error
   (require 'package)
   (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
   (package-initialize)
   (package-refresh-contents)
   (package-install 'use-package)
   (setq use-package-always-ensure t)
   (require 'use-package)))

(use-package projectile)
(use-package flycheck)
(use-package yasnippet :config (yas-global-mode))
(use-package lsp-mode :hook ((lsp-mode . lsp-enable-which-key-integration))
  :config (setq lsp-completion-enable-additional-text-edit nil))
(use-package hydra)
(use-package company)
(use-package lsp-ui)
(use-package which-key :config (which-key-mode))
(use-package lsp-java :config (add-hook 'java-mode-hook 'lsp))
(use-package dap-mode :after lsp-mode :config (dap-auto-configure-mode))
(use-package dap-java :ensure nil)
(use-package helm-lsp)
(use-package helm
  :config (helm-mode))
(use-package lsp-treemacs)

;; render ansi color in dap test output buffer
(add-hook 'compilation-filter-hook
          (lambda () (ansi-color-apply-on-region (point-min) (point-max))))

;; insert space instead of tab
(setq-default indent-tabs-mode nil)
;; java language server version
(setq lsp-java-jdt-download-url "https://mirrors.tuna.tsinghua.edu.cn/eclipse/jdtls/milestones/1.5.0/jdt-language-server-1.5.0-202110191539.tar.gz")
;; java format settings 
(setq lsp-java-format-settings-url "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml" )

(require 'lsp-java-boot)
;; to enable the lenses
(add-hook 'lsp-mode-hook #'lsp-lens-mode)
(add-hook 'java-mode-hook #'lsp-java-boot-lens-mode)


(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(inhibit-startup-screen t)
 '(package-selected-packages
   '(helm-lsp lsp-java which-key lsp-ui company hydra lsp-mode yasnippet flycheck projectile use-package)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

**Expected behavior**
Completion popup is shown.
![properties-completion](https://github.com/emacs-lsp/lsp-java/blob/master/images/validation-completion.png)

**Screenshots**
No completion pupop
![lsp-java-lsp-app-prop-no-completion](https://user-images.githubusercontent.com/28599139/141679921-31f59a80-b825-4a99-8298-2b9f4b802b8c.png)
lsp describe session
![lsp-java-lsp-desc-session](https://user-images.githubusercontent.com/28599139/141679981-5d9f253a-e944-4123-aa8c-ecc24df45d1e.png)

**Logs**
How can I provide more info or log?

**Comment by yyoncho** [comment]
can you do M-x lsp in the properties file?

**Comment by yejianfengblue** [comment]
After M-x lsp, the code completion works. 

How to auto enable lsp for the application.properties and application.yml buffers? I try `(add-hook 'conf-mode-hook #'lsp-mode)` but not work.

Same as https://github.com/emacs-lsp/lsp-java/issues/155, the `*Warning*` buffer is flood with `Warning (lsp-mode): Unknown request method: sts/javaSuperTypes`, which is annoying. Is it possible to suppress it?

![lsp-java-app-prop-complete-sts-javatype](https://user-images.githubusercontent.com/28599139/141681474-b6157d3d-531a-41e9-bbfd-acee10f1bdb7.png)

**Comment by yyoncho** [comment]
should be ok after https://github.com/emacs-lsp/lsp-java/commit/3246272b43659ce3020e6f47cd3eea17432b389a

**Comment by yejianfengblue** [comment]
I manully change ~/.emacs.d/elpa/lsp-java-20211017.1826/lsp-java-boot.el according to the commit, but still many sts/javaType. Maybe wait you to publish to elpa and update package to take effect?

**Comment by yyoncho** [comment]
can you try adding the same thing to :request-handlers?

**Comment by yejianfengblue** [comment]
Still error
```lisp
(lsp-register-client
 (make-lsp-client :new-connection
                  (lsp-tcp-server #'lsp-java-boot--ls-command)
                  :activation-fn (lambda (_filename mode)
                                   (and lsp-java-boot-enabled
                                        (memq mode '(java-mode conf-javaprop-mode yaml-mode))
                                        (lsp-java-boot--server-jar)))
                  :request-handlers  (ht ("sts/addClasspathListener" #'lsp-java-boot--sts-add-classpath-listener)
                                         ("sts/javaSuperTypes" #'ignore) 
                                         ("sts/javadocHoverLink" #'lsp-java-boot--sts-javadoc-hover-link))
                  :notification-handlers  (ht ("sts/highlight" #'lsp-java-boot--sts-hightlight)
                                              ("sts/progress" #'ignore)
                                              ("sts/javaSuperTypes" #'ignore))
                  :multi-root t
                  :add-on? t
                  :server-id 'boot-ls
                  :completion-in-comments? t))
```

**Comment by yejianfengblue** [comment]
Reply to my early question: How to auto enable lsp for the application.properties and application.yml buffers?
```lisp
(add-hook 'conf-javaprop-mode-hook #'lsp)
```

**Comment by yyoncho** [comment]
you have to restart the server after you eval this form

**Comment by yejianfengblue** [comment]
I restart emacs and reopen the .java file and then the application.properties file. Then M-x lsp, type `server`

**Comment by yyoncho** [comment]
You should make sure that you are using the correct client when doing that. One way to do this is to eval the form pasted above before starting the server. Also, you may try adding the same code in `lsp-java.el`. I am not sure where this notification is coming from.

**Comment by yejianfengblue** [comment]
Is it convenient to share you emacs config file or directory in github? I can't find a mature emacs config for Java IDE in github or google.

**Comment by yyoncho** [comment]
I am using spacemacs withtout boot-ls

**Comment by yejianfengblue** [comment]
Close this issue because the original code completion problem is resolved by manually `M-x lsp` or auto enable lsp on properties file which is `conf-javaprop-mode` by adding a hook
```lisp
(add-hook 'conf-javaprop-mode-hook #'lsp)
```

Follow the sts/javaType warning message with https://github.com/emacs-lsp/lsp-java/issues/155
