### ISSUE TITLE
How to Navigate dependency classes?

### ISSUE THREAD

**Issue by Ice-Cube69** [emacs-lsp/lsp-java#369]
I would like to go to a dependency class, but I can't unless i am referencing it by using goto definition on it's class name in imports. Can you add a feature so that one can just search for classes and go to that class?

**Comment by yyoncho** [comment]
Use helm-lsp-workspace-symbols/lsp-ivy equivalent/councel-lsp equivalent/or xref-find-apropos.

**Comment by Ice-Cube69** [comment]
Nevermind I was able to find the function to look for symbols, thanks
