### ISSUE TITLE
Too many debug messages

### ISSUE THREAD

**Issue by david** [emacs-lsp/lsp-java#37]
Debug messages often obscure important information (like, for example, when I'm performing a search, I often can't see what I'm typing because `<date> >> document/hover` is being displayed instead). Would it be possible to show these messages only when a given configuration variable is set?

**Comment by yyoncho** [comment]
You could set `lsp-inhibit-message` to true.

**Comment by david** [comment]
Indeed, that works fine. Apologies for not having noticed it, and thanks for your work and patience.

**Comment by yyoncho** [comment]
No problem, I am using these issues to construct FAQ section.
