### ISSUE TITLE
dap-java-run-test-method doesn't fall back like it says

### ISSUE THREAD

**Issue by Lenbok** [emacs-lsp/lsp-java#371]
**Describe the bug**
The docs for `dap-java-run-test-method` say "Run JUnit test.
If there is no method under cursor it will fallback to test class."

However, when I run it when not on a method, all that happens is I get "No method at point" in the mode line. (I can run `dap-java-run-test-class` separately fine, it's just this dwim mode of can run `dap-java-run-test-method` that is borked)

**Comment by yyoncho** [comment]
The doc is wrong indeed.
