### ISSUE TITLE
An error when lsp-java start

### ISSUE THREAD

**Issue by vanniuner** [emacs-lsp/lsp-java#374]
File mode specification error: (doom-hook-error java-mode-hook lsp (file-missing Doing vfork No such file or directory))
env:
mac m1 pro , emacs-plus ,

**Comment by yyoncho** [comment]
Report that in doom repo

**Comment by vanniuner** [comment]
oaky

**Comment by ZelphirKaltstahl** [comment]
FYI: Doesn't seem to be a DoomEmacs only issue. Also seems to happen to vanilla Emacs and other programming language LSP packages. Using eglot and Python, I see this error as well (without the Doom part of course).
