### ISSUE TITLE
lsp-java-autobuild-enabled do not work?

### ISSUE THREAD

**Issue by vanniuner** [emacs-lsp/lsp-java#375]
**Describe the bug**
It seems that the config lsp-java-autobuild-enabled do not working.

**Note**
My expectation is when I modify a java file the maven target folder will change. I can use `ll` to show the last update time to confirm whether it changes or not, under the condition that lsp-java-autobuild-enabled is t.
However, In my PC the result is unstabale. At present it do not work again.

**Expected behavior**
My expectation is when I modify a java file the maven target folder will change. I can use `ll` to show the last update time to confirm whether it changes or not, under the condition that lsp-java-autobuild-enabled is t.

**Logs**
Cancelling textDocument/codeLens(112) in hook after-change-functions
2021年12月25日 下午10:15:28 >> document/didChange
2021年12月25日 下午10:15:28 >> document/didChange
2021年12月25日 下午10:15:28 >> document/didChange
2021年12月25日 下午10:15:28 >> document/didChange
2021年12月25日 下午10:15:28 >> document/didChange
2021年12月25日 下午10:15:29 >> document/didChange
2021年12月25日 下午10:15:29 >> document/didChange
2021年12月25日 下午10:15:29 >> document/didChange
2021年12月25日 下午10:15:29 >> document/didChange
2021年12月25日 下午10:15:29 >> document/didChange
2021年12月25日 下午10:15:29 >> document/documentHighlight
2021年12月25日 下午10:15:29 >> document/hover
2021年12月25日 下午10:15:29 >> document/documentHighlight
2021年12月25日 下午10:15:29 >> document/codeLens
Cancelling textDocument/codeLens(116) in hook after-change-functions
2021年12月25日 下午10:15:29 >> document/didChange
2021年12月25日 下午10:15:29 >> document/didChange
2021年12月25日 下午10:15:29 >> document/didChange
2021年12月25日 下午10:15:29 >> document/didChange
2021年12月25日 下午10:15:29 Reconciled 1. Took 5 ms
2021年12月25日 下午10:15:30 begin problem for /CommentsController.java
2021年12月25日 下午10:15:30 17 problems reported for /CommentsController.java
2021年12月25日 下午10:15:30 Validated 1. Took 78 ms

**Comment by yyoncho** [comment]
> My expectation is when I modify a java file the maven target folder will change. I can use `ll` to show the last update time to confirm whether it changes or not, under the condition that lsp-java-autobuild-enabled is t.

The expectations should be that if you run the application via `M-x dap-java-debug` the application is updated.

**Comment by vanniuner** [comment]
that's a gooooood way!
