### ISSUE TITLE
lsp-java is incompatible

### ISSUE THREAD

**Issue by jackcviers** [emacs-lsp/lsp-java#376]
**Describe the bug**

```
Package lsp-java is incompatible.

     Status: Incompatible because it depends on uninstallable packages.
    Archive: melpa
    Version: 20211124.605
     Commit: ce03cb6574566e334c3ce5735458cc3ec1989486
    Summary: Java support for lsp-mode
   Requires: emacs-25.1, lsp-mode-6.0, markdown-mode-2.3, dash-2.18.0, f-0.20.0, ht-2.0,
               request-0.3.0 (not available), treemacs-2.5, dap-mode-0.5
   Homepage: https://github.com/emacs-lsp/lsp-java
   Keywords: languague tools 

Java specific adapter for LSP mode
```

[back]

**Note**
Before logging the bug please make sure that the issue is reproducible with latest melpa packages and it is reproducible with the clean config(the config from the getting started page.

**To Reproduce**

Upgrading packages with lsp-java installed reports that lsp-java is no longer necessary and can be removed with `M-x package-autoremove`. This deletes the package from the user's package directory. `list-packages` then shows `lsp-java` as incompat.

This then breaks my startup, as I have use-package statements that ensure the package is installed. It is not possible mark the package in the `*Packages*` buffer to install, and the package `*Help*` buffer likewise does not show an install button to install the package.

#### Platform

macOS Monterey Version 12.0 Apple M1 Pro

#### Emacs Version

GNU Emacs 27.2 (build 1, arm-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559)) of 2021-11-18

**Expected behavior**
`lsp-java` should not be incompatible with emacs > 25.1, and should be available for installation in the `*Packages*` buffer after `list-packages` is called, and the `Install` button should be available from the package `*Help*` buffer when navigating to the `lsp-java` entry in the *Packages* buffer and hitting `<Enter>`.

**Screenshots**
See the attached package `*Help*` buffer above.

**Logs**
NA - installation issue.

**Comment by yyoncho** [comment]
can you investigate why `request-0.3.0 (not available)` is not installable on your side?

**Comment by jackcviers** [comment]
I'll take a look.

Jack Viers - 515.313.7838 ***@***.***

**Comment by jackcviers** [comment]
As of 28-11-2021T11:40.000-05:00 lsp-java returned from list-packages shows as available:

```
Package lsp-java is available.

     Status: Available from melpa -- Install
    Archive: melpa
    Version: 20211124.605
     Commit: ce03cb6574566e334c3ce5735458cc3ec1989486
    Summary: Java support for lsp-mode
   Requires: emacs-25.1, lsp-mode-6.0, markdown-mode-2.3, dash-2.18.0, f-0.20.0, ht-2.0,
               request-0.3.0, treemacs-2.5, dap-mode-0.5
   Homepage: https://github.com/emacs-lsp/lsp-java
   Keywords: languague tools 
Other versions: 3.1 (melpa-stable).

Java specific adapter for LSP mode

[back]
---
  lsp-java           20211124.605  available  melpa      Java support for lsp-mode
  lsp-jedi           1.0.0         available  melpa-stable Lsp client plugin for Python Jedi Language Server

```
As does request-0.3.0:
```
Package request is available.

     Status: Available from melpa-stable -- Install
    Archive: melpa-stable
    Version: 0.3.2
     Commit: 22efefeaa394f6deef957818f5c5332061c88d1c
    Summary: Compatible layer for URL request in Emacs
   Requires: emacs-24.4
   Homepage: https://github.com/tkf/emacs-request
 Maintainer: Takafumi Arakaki <aka.tkf at gmail.com>
     Author: Takafumi Arakaki <aka.tkf at gmail.com>
Other versions: 20211107.1907 (melpa).

Request.el is a HTTP request library with multiple backends.  It
supports url.el which is shipped with Emacs and curl command line
program.  User can use curl when s/he has it, as curl is more reliable
than url.el.  Library author can use request.el to avoid imposing
external dependencies such as curl to users while giving richer
experience for users who have curl.

Following functions are adapted from GNU Emacs source code.
Free Software Foundation holds the copyright of them.
* `request--process-live-p'
* `request--url-default-expander'

[back]
---
request            0.3.2         available  melpa-stable Compatible layer for URL request in Emacs
  request            20211107.1907 available  melpa      Compatible layer for URL request
```

Yesterday, `melpa-stable` was returning `Status Code 429` for me all day, but melpa was returning just fine.

So everything seems to be fine today. Maybe there was some publishing weirdness going on with dependencies yesterday?
