### ISSUE TITLE
Code completion case sensitive now

### ISSUE THREAD

**Issue by huangfeiyu** [emacs-lsp/lsp-java#378]
After upgrade, code completion (narrow down the candidates by type more characters) is case sensitive, it isn't before my upgrade. I prefer the old way (case insensitive). How could I configure it to case insensitive? Thanks!

**Comment by yyoncho** [comment]
The server does not provide case-insensitive results. When we get all completions we do client side case-insensitive matching. What you are seeing is the best we can do. I have filed server feature request to provide flex matching and case insenstive results.

**Comment by huangfeiyu** [comment]
Thanks a lot for your explanation @yyoncho
