### ISSUE TITLE
wrong-type-argument lsp--workspace nil

### ISSUE THREAD

**Issue by sid-code** [emacs-lsp/lsp-java#38]
This is the error I get when I run `lsp-java-enable` in a Java buffer with `lsp-mode` on.

Here is my configuration:

```elisp
(use-package lsp-mode
  :ensure t
  :defer t
  :init
  (add-hook 'prog-mode-hook 'lsp-mode))

(use-package lsp-java
  :ensure t
  :defer t
  :init
  (require 'lsp-java)
  (setq lsp-java--workspace-folders (list "/path/to/java/project"))
  (add-hook 'java-mode-hook #'lsp-java-enable))

```

I have the latest versions of all of `lsp-mode`, `lsp-java`, and the language server.

**Comment by sid-code** [comment]
Stack trace from `java-mode`'s `run-mode-hooks`
```
Debugger entered--Lisp error: (wrong-type-argument lsp--workspace nil)
  signal(wrong-type-argument (lsp--workspace nil))
  lsp--set-configuration(((java (jdt (ls (vmargs . "-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication"))) (errors (incompleteClasspath (severity . warning))) (configuration (updateBuildConfiguration . automatic) (maven)) (trace (server . off)) (import (gradle (enabled . t)) (maven (enabled . t)) (exclusions "**/node_modules/**" "**/.metadata/**" "**/archetype-resources/**" "**/META-INF/maven/**")) (referencesCodeLens (enabled . t)) (progressReports (enabled . t)) (signatureHelp (enabled . t)) (implementationsCodeLens (enabled . t)) (format (enabled . t) (settings (profile) (url)) (comments (enabled . :json-false))) (saveActions (organizeImports . t)) (contentProvider) (autobuild (enabled . t)) (completion (favoriteStaticMembers "org.junit.Assert.*" "org.junit.Assume.*" "org.junit.jupiter.api.Assertions.*" "org.junit.jupiter.api.Assumptions.*" "org.junit.jupiter.api.DynamicContainer.*" "org.junit.jupiter.api.DynamicTest.*") (importOrder "java" "javax" "com" "org")))))
  lsp-java-update-user-settings()
  lsp-java--after-start()
  apply(lsp-java--after-start nil)
  #f(advice-wrapper :after #f(compiled-function () (interactive nil) #<bytecode 0xdf16e9>) lsp-java--after-start)()
  apply(#f(advice-wrapper :after #f(compiled-function () (interactive nil) #<bytecode 0xdf16e9>) lsp-java--after-start) nil)
  lsp-java-enable()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook c-mode-common-hook java-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook c-mode-common-hook java-mode-hook))
  run-mode-hooks(java-mode-hook)
```

**Comment by yyoncho** [comment]
This error is usually caused by a failure in JDT process. There are several bugs on `lsp-mode` side for better handling of process crash. Can you do the following:

1. Check the content of `*lsp-java stderr*
2. Make sure the jdt process is running
3. To further diagnose the issue you could do `M-x`-`eval-expression` and then type `(lsp-java--ls-command)` which will generate the parameters that are used for starting LSP.

**Comment by yyoncho** [comment]
Can you also remove :   `(add-hook 'prog-mode-hook 'lsp-mode)` from the following snippet too:

`(use-package lsp-mode
  :ensure t
  :defer t
  :init
  (add-hook 'prog-mode-hook 'lsp-mode))`

**Comment by sid-code** [comment]
I removed all hooks, restarted emacs, and tried to open a java file, did `M-x lsp-mode` and `M-x lsp-java-enable`, which resulted in the same error.

`*lsp-java-stderr*`:
```
Process lsp-java stderr finished
```

**Comment by sid-code** [comment]
I ran the command given by `(lsp-java--ls-command)` and it exits with error code 13. This is probably what I need to figure out.

**Comment by sid-code** [comment]
I ran the command given by `(lsp-java--ls-command)` and it exits with error code 13. Deleting my workspace folder fixed this, but the error I opened this issue with still persists.

**Comment by yyoncho** [comment]
Is the JDT server process running in process explorer?

**Comment by sid-code** [comment]
It does not run.

After doing this a couple of times, I've realized that this error shows up even before I run `lsp-java-enable`:

From `*Messages*`:
```
Lsp mode enabled in current buffer
Error during redisplay: (eval (lsp-mode-line)) signaled (wrong-type-argument lsp--workspace nil) [2 times]
```

**Comment by yyoncho** [comment]
Can you make sure you are not enabling `lsp-mode` before `lsp-enable-java` call?

**Comment by sid-code** [comment]
Ha, it seems like that was it. I was under the impression that lsp-mode needs to be on before lsp-java-enable can be called, guess that was completely wrong.
