### ISSUE TITLE
Is there a builtin way to see source code of dependencies?

### ISSUE THREAD

**Issue by jacktwilliams** [emacs-lsp/lsp-java#393]
`lsp-jt-report-open` gives me a stack trace like this, which is unclickable.
```
Stack trace: 
java.lang.UnsupportedOperationException: RIGHT JOIN not supported
	at org.hibernate.query.criteria.internal.path.AbstractFromImpl.join(AbstractFromImpl.java:397)
```

Is there any built-in way for me to open that class's source code file?

**Comment by yyoncho** [comment]
M-x helm-lsp-workspace-symbols(or ivy/xref/counsel equivalent) and go to that class. I have feature request in jdtls to provide a function parsing these, but it is still open.

**Comment by jacktwilliams** [comment]
Ok this is what I was looking for. I did try some of the workspace symbol functions before, but I got it figured out now. Thanks a bunch!
