### ISSUE TITLE
jdtls quits instantly after increasing heap space argument. 

### ISSUE THREAD

**Issue by Dadams2** [emacs-lsp/lsp-java#398]
**Describe the bug**
jdtls won't start after customising jvm args. Project starts building fine with default args but is too large so ooms. 
Seems similar to #293 but I am certain the java path is correct

**To Reproduce**
Run `java-lsp-build-project` on a sufficiently large project that it would oom without changing default settings, 
and where changed default settings are:
```
(setq lsp-java-vmargs '("-XX:+UseParallelGC" "-XX:GCTimeRatio=4" "-XX:AdaptiveSizePolicyWeight=90" "-Dsun.zip.disableMemoryMapping=true" "-Xmx4G" "-Xms256"))
```
(just increasing max heap space)

**Expected behavior**
project would build fine

**Logs**
Can't get anytning more than this on the client side.
```Process jdtls stderr finished```
Where should I be looking/what commands to run to get further debug?

**Comment by ArneBab** [comment]
As a blind shot: Xmx4g needs a lowercase g, and Xms needs a suffix to not take 256 bytes for starting (which must fail).

**Comment by Dadams2** [comment]
changing to "-Xms1G" fixed my issue. Thank you!
