### ISSUE TITLE
How to goto the error line quickly?

### ISSUE THREAD

**Issue by huangfeiyu** [emacs-lsp/lsp-java#407]
I have the following status bar
![image](https://user-images.githubusercontent.com/12697122/191879874-e7ffb504-d9ef-4e11-a1e3-492971bdda5a.png)
It says there are 51 apparent issues, my question is  that is there a way to navigate to the 51 errors quickly without the need to go through each of 10598 items another. Thanks!

**Comment by yyoncho** [comment]
you may use helm-lsp-diagnostics or ivy/consult equivalents

**Comment by huangfeiyu** [comment]
excellent! Thank you every much!
