### ISSUE TITLE
`dap-java`: Attaching works, breakpoint is hit, but no active session exists

### ISSUE THREAD

**Issue by Walheimat** [emacs-lsp/lsp-java#408]
**Describe the bug**

This is a multi-module maven project.

Using the template to attach seemingly works ... up to a point. When a breakpoint is hit, the configured DAP windows pop up, but there's no paused thread and no active session. I tried to check if the issue is the selected thread, but that doesn't seem to be it.

I tried various different version of the jdtls to see if that could be the issue, always deleting the workspace folder, but the issue remains the same (although later version just don't even start).

**To Reproduce**

Not sure how to give an example here as I'm a greenhorn when it comes to Java projects. Sorry!

In this project, I basically run the following command:

```sh
java -server -Xmx2048m -XX:MaxPermSize=1G -Djava.awt.headless=true -agentlib:jdwp=transport=dt_socket,address=34502,server=y,suspend=n -jar <jarfile>
```

Attaching in VSCode with default attach launch.json does pause the thread (which from checking the source code of `dap-java` is identical to the dap template) ... I just would like to not have to use VSCode.

**Expected behavior**

Hitting the breakpoint yields an active session.

**Logs**

There's no error, so no error logs. The buffer is empty.

When I turn on `dap-print-io`,  these are the last messages send and received:

```
Received:
{
    "event": "thread",
    "body": {
        "reason": "started",
        "threadId": 28306,
        "type": "thread"
    },
    "seq": 34,
    "type": "event"
}
Sending:
{
    "command": "threads",
    "type": "request",
    "seq": 19
}
Received:
{
    "success": true,
    "request_seq": 19,
    "command": "threads",
    "body": {
        "threads": [
           ...
        ]
    },
    "seq": 35,
    "type": "response"
}
```
... and then it stops until I "continue". It reliably "stops", but there's no session.

**Comment by yyoncho** [comment]
It is a regression, tracked in lsp-treemacs repo. The workaround is to select the thread from the dap-ui-sessions.

**Comment by Walheimat** [comment]
I see, thanks.

Now the problem will be of finding the right one, since there's what feels like a hundred threads.

**Comment by Walheimat** [comment]
So yeah, looks like a duplicate of this: https://github.com/emacs-lsp/lsp-treemacs/issues/144

Will close this and watch the other thread.

**Comment by yyoncho** [comment]
I will try to fix it right now.

**Comment by yyoncho** [comment]
@Walheimat should be good now after upgrading dap-mode.

**Comment by Walheimat** [comment]
Will do as soon as MELPA is back up, has been dead for a while now.

**Comment by Walheimat** [comment]
Works like a charm. Thank you so much for the fix.
