### ISSUE TITLE
The import org.junit cannot be resolved

### ISSUE THREAD

**Issue by MadcowOG** [emacs-lsp/lsp-java#409]
I apologize if this is not the appropriate place for this but I haven't been able to get help for this anywhere else so far.
I have a simple java tester and need to use junit. But I don't know how to get jdtls to recognize junit. This is the directory structure for my project.
```
build.xml    
Ch15Test.java
junit.jar    
README.md
```
I have a junit jar file within the project directory is it possible to just get jdtls to just use this? How should I even start with this?
Any help is appreciated (I am using Doom Emacs).

**Comment by yyoncho** [comment]
you have to create a .classpath file and most likely .project files as well. These should follow the eclipse structure for these.

**Comment by MadcowOG** [comment]
The documentation on this type of situation seems to be very sparse. The best resources I found were, [the eclipse help reference](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fproject_description_file.html&cp=2_1_5_11) for .project, and [eclim classpath editing page](http://eclim.org/vim/java/classpath.html) for .classpath.
However I believe Doom emacs handles projects differently (at least for java), by default. Rather than creating configs within the project directory it creates a directory within `EMACS_DIR/.local/etc/java-workspace/{project_dir_name}-{numbers and letters}` which holds .classpath, .project and .settings. The .classpath and .project then reference the directory which holds your actual project. So Doom Emacs initializes within `EMACS_DIR/.local/etc/java-workspace/{project_dir_name}-{numbers and letters}`.
Usually .project looks like this:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>project</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.jdt.core.javanature</nature>
	</natures>
	<linkedResources>
		<link>
			<name>_</name>
			<type>2</type>
            <location>project_path</location>
		</link>
    </linkedResources>
	<filteredResources>
		<filter>
			<id>1666205885624</id>
			<name></name>
			<type>30</type>
			<matcher>
				<id>org.eclipse.core.resources.regexFilterMatcher</id>
				<arguments>node_modules|.metadata|archetype-resources|META-INF/maven|__CREATED_BY_JAVA_LANGUAGE_SERVER__</arguments>
			</matcher>
		</filter>
    </filteredResources>
</projectDescription>

```
And .classpath looks like this:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry kind="src" path="_"/>
    <classpathentry kind="output" path="bin"/>
</classpath>
```

But if I want to import that jar file within the project dir? I need to add this line to .classpath:
``` xml
<classpathentry kind="lib" path="_/junit.jar" sourcepath="_/junit.jar"/>
```

I must use the linkedResource pointing to the project path, and cannot create a new linkedResource, or reference the jar file with an absolute path.
This is fine I guess but there is no ouput from the server if I do this. It just seems to fail to recognize all of the classpath outright.
If this happens I will get `file is not part of project. Only syntax errors are reported.` (this is not exact but similar). Which seems counter-intuitive. I'm thinking maybe the server should output to stderr and say something like `Unable to parse .classpath` or something to let the user know what's happening (I understand this probably isn't something for lsp-java to solve but upstream at jdtls, something I should report up?).

I though this might be useful for another Doom Emacs user running into the same problem I was.

Thank you @yyoncho.

**Comment by MadcowOG** [comment]
I will close this issue. But if someone else has more information then feel free to add to this.
