### ISSUE TITLE
var cannot be resolved to a type

### ISSUE THREAD

**Issue by anupam312nwd** [emacs-lsp/lsp-java#410]
Hi, I am not sure if this is an issue due to `lsp-java`.
When I declare a variable using `var <var-name> = ...`, I get `var cannot be resolved to a type` error in emacs. 
I am using `doom-emacs` with module settings `(java +lsp)`. Here is a link to the config https://github.com/doomemacs/doomemacs/tree/master/modules/lang/java.
This error is not showing in `VS code` or `IntelliJ IDEA` for the same code and project.

I know that `var` is introduced after version 10 of Java. I am currently using version 19 and it shows in `java --version` and `javac --version` output.

Thanks!

**Comment by yyoncho** [comment]
Most likely jdtls does not recognize the proper java version. That can happen for example if your pom.xml does not have the proper java.version

**Comment by anupam312nwd** [comment]
Thanks. I installed `jdtls` using `brew` on my mac, and reinstall `jdtls` using `lsp-install-server` and the issue resolved.
