### ISSUE TITLE
Matlab-mode autocompletion/java error

### ISSUE THREAD

**Issue by averter** [emacs-lsp/lsp-java#427]
**Describe the bug**
Autocompletion in emacs matlab-shell does not work. 

**Note**
Before logging the bug please make sure that the issue is reproducible with latest melpa packages and it is reproducible with the clean config(the config from the getting started page.

**To Reproduce**

1. open a matlab-shell terminal inside emacs using "M-x matlab-shell"
2. type "ma" and hit TAB
3. A "Cannot complete at point" error message appears.

The following bug trace is available
```` lisp
Debugger entered--Lisp error: (error #("Internal error, ’emacsdocomplete('ma')’ returned u..." 34 36 (fontified t)))
  signal(error (#("Internal error, ’emacsdocomplete('ma')’ returned u..." 34 36 (fontified t))))
  error("Internal error, '%s' returned unexpected output, %..." #("emacsdocomplete('ma')" 17 19 (fontified t)) "put =\n\n  java.lang.String[]:\n\n    'maboxplot'\n    ...")
  matlab-shell-completion-list(#("ma" 0 2 (fontified t)))
  matlab-shell-get-completion-info()
  company-matlab-shell-grab-completion-substr()
  company-matlab-shell(prefix)
  apply(company-matlab-shell prefix)
  company-call-backend-raw(prefix)
  apply(company-call-backend-raw prefix)
  company--force-sync(company-call-backend-raw (prefix) company-matlab-shell)
  company-call-backend(prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-manual-begin()
  company-begin-backend(company-matlab-shell)
  company-matlab-shell(interactive)
  funcall-interactively(company-matlab-shell interactive)
  call-interactively(company-matlab-shell)
  matlab-shell-tab()
  funcall-interactively(matlab-shell-tab)
  call-interactively(matlab-shell-tab nil nil)
  command-execute(matlab-shell-tab)
`````
**Expected behavior**
List of possible completions in an interactive window next to typed text.

**Logs**
See above. Also, I am using Matlab R2020b, emacs 27.1, matlab-mode-20230120.1938 and Linux mint 21.1

**Comment by yyoncho** [comment]
it looks like it is not for that repo?

**Comment by averter** [comment]
Apologies if that's the case. There are so many repos and most of them not maintained anymore that it is difficult to narrow down where the problem comes from... Any pointers are very welcome.

**Comment by yyoncho** [comment]
It looks like it is developed here: https://sourceforge.net/p/matlab-emacs/src/ci/master/tree/ but I am not sure where to report the issue. I will ask in some general forum like r/emacs in reddit for guidance.
