### ISSUE TITLE
jdtls version 1.20.0 or above, jdtls has exited

### ISSUE THREAD

**Issue by vanniuner** [emacs-lsp/lsp-java#428]
**Describe the bug**
When using jdtls version 1.20.0 or above，there have an exception cause LSP not working.
```
LSP :: jdtls has exited (exited abnormally with code 23)
```

I use `lsp-java-jdt-download-url` change the default jdt download url.
Reference: https://download.eclipse.org/jdtls/milestones/1.20.0/

**Note**
Case an another bug ,I need upgrade jdtls to last version. 
But When upgrade jdtls version to 1.20.0 or above，there have a exception cause LSP not working.

**To Reproduce**
(setq lsp-java-jdt-download-url      "http://1.117.167.195/download/jdt-language-server-1.22.0-202304122049.tar.gz")
and remove .emacs.d/.local/etc/lsp/
and then reinstall jdt 

**Expected behavior**
When upgrade jdtls version to 1.20.0 or above, LSP startup with no error.

**Screenshots**
![CleanShot 2023-04-13 at 11 53 41](https://user-images.githubusercontent.com/7248023/231646268-0b32fa53-ac4e-4655-a09c-a82b8b26c18c.png)

**Logs**
```
LSP :: jdtls has exited (exited abnormally with code 13)
```

**Comment by yyoncho** [comment]
Newest jdtls require newer java: https://github.com/emacs-lsp/lsp-java/pull/405#issuecomment-1228398077

**Comment by yyoncho** [comment]
Also make sure to delete lsp-java-workspace-dir.

**Comment by vanniuner** [comment]
I am sure jdk version is correct.
```
set -x JAVA_HOME            /Users/van/soft/zulu17.40.19-ca-fx-jdk17.0.6-macosx_aarch64/zulu-17.jdk/Contents/Home
```
