### ISSUE TITLE
customize build directory

### ISSUE THREAD

**Issue by Chream** [emacs-lsp/lsp-java#44]
Hi, I am using lsp-mode with a spring webapp. To use the auto redeploy feature of spring devtools it needs to see changes to the classpath. Our app places all classes in build/classes/java/main/... . The language server puts the classes in bin/main/... . Anyway to specify the path to the classes?

**Comment by yyoncho** [comment]
@gorkem @fbricon is there an option to customize build directory?

**Comment by yyoncho** [comment]
As far as I can see the output folder is hardcoded here - https://github.com/eclipse/eclipse.jdt.ls/blob/064a6a57ff1eb751bf3cc6279909a97e126f501a/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java#L370 and there is no option to update it so there is nothing we can do on emacs side. The code seems to be a bit odd, I guess it is legacy from the single root workspaces. JDT team guys could provide more info.

**Comment by fbricon** [comment]
@yyoncho that's for the default java project, in jdt.ls' workspace directory, which should not be user visible. This project is used when opening standalone Java files.
 
User projects' output directory is defined by the pom.xml for Maven projects (usually target/) and Buildship (the Gradle integration for Eclipse project), which, AFAIR, always uses bin/ for the user project outputs (but I may be wrong). @donat might be able to give more info on the Buildship part.

**Comment by Chream** [comment]
Sorry for the delayed response, and thank you for the help guys. I will post an issue/PR with jdt. Should I close this or leave it open for visibility?

**Comment by yyoncho** [comment]
You can close it. I will update the readme based on the JDT issue outcome.
