### ISSUE TITLE
project / workspace folders

### ISSUE THREAD

**Issue by st1971** [emacs-lsp/lsp-java#45]
is there any way to specify a workspace / project folder after startup?

great work BTW really enjoying using it

**Comment by yyoncho** [comment]
Once you have set the new values of workspace dir and workspace folders you have two options:
1. Close all java buffers. This will kill lsp server and the next time you open java file a new lsp server with the new settings will be started.
2. Call `lsp-workspace-restart`. I think that I had issues with it in the past but I didn't have time to investigate it. 

I am using 1), it is inconvenient but until #39 is fixed we will have to live with it.

**Comment by st1971** [comment]
Thank you, will work for me, better than restarting emacs which is what i've been doing so far

**Comment by yyoncho** [comment]
Marking as closed, please reopen the suggested solution does not work.
