### ISSUE TITLE
First element of company menu for import

### ISSUE THREAD

**Issue by blutics** [emacs-lsp/lsp-java#46]
When I choose the first option of the company-recommanding lists without any other typing,
all the words from import are gone and the last class name only leaves.

ex) [import java.io.]
company list
-->Console
ObjectStreamClass
PushbackInputStream
.....
after hit the enter
[Console;]

**Comment by blutics** [comment]
But if at least one character is typed after dot, it works fine

**Comment by yyoncho** [comment]
Fixed by @tigersoldier , please upgrade to latest company-lsp.
