### ISSUE TITLE
support for netbeans lsp server

### ISSUE THREAD

**Issue by saladmaker** [emacs-lsp/lsp-java#462]
hi,
eclipse **jdtls** is too slow and  sometimes causes **emacs** to hang indefinitely even for relatively small/meduim projects.
is it possible to swap **eclipse jdtls** with **netbeans** java lsp?
also is it possible to use netbeans lsp with l**sp-mode** if **lsp-java** happens to be tied to **eclipse jdtls**?!
Thanks,

**Comment by yyoncho** [comment]
https://github.com/timfel/lsp-netbeans try that one
