### ISSUE TITLE
Building/Running

### ISSUE THREAD

**Issue by blutics** [emacs-lsp/lsp-java#47]
I set the workspace with this statement,
    (setq lsp-java--workspace-folders (list "~/workspace/"))
,but still the lsp-java-build-project doesn't work.
Nothing comes up, no error message either
Is there any other config I should do??
And is there a way of running the code within this mode??

**Comment by blutics** [comment]
When I run lsp-java-build-project command, nothing comes up

**Comment by yyoncho** [comment]
I suppose you are running with `lsp-inhibit-message` equals to t? This will prevent build messages to display in the message area but you can check them in \*messages\*. Anyway, `lsp-java-build-project` is more like trigger recalculate errors. If you want to run/debug/test the project you can use `dap-mode` - https://github.com/yyoncho/dap-mode .
