### ISSUE TITLE
Null annotation types config?

### ISSUE THREAD

**Issue by sincebyte** [emacs-lsp/lsp-java#473]
**Describe the bug**
every time on lsp start up ,the message appeared. 
LSP :: Null annotation types have been detected in the project. Do you wish to enable null analysis for this project?
Did there have some config to enable or disable it?

**Comment by ark3** [comment]
There is `lsp-java-compile-null-analysis-mode`, which [defaults to `"interactive"`](https://github.com/emacs-lsp/lsp-java/blob/master/lsp-java.el#L1728) but probably wants to be `"automatic"`.

**Comment by sincebyte** [comment]
> There is `lsp-java-compile-null-analysis-mode`, which [defaults to `"interactive"`](https://github.com/emacs-lsp/lsp-java/blob/master/lsp-java.el#L1728) but probably wants to be `"automatic"`.
thanks, it works
(setq  lsp-java-compile-null-analysis-mode        "automatic")
