### ISSUE TITLE
Expose che-ls-jdt methods

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-java#52]
Here it is the list of methods that are available in backend but not exposed in `lsp-java`.

This task is tracking the front end work required to expose the method if feasible.

- [x] che.jdt.ls.extension.classpathTree
- [ ] che.jdt.ls.extension.configuration.getJavaCoreOptions
- [ ] che.jdt.ls.extension.configuration.getPreferences
- [ ] che.jdt.ls.extension.configuration.updateJavaCoreOptions
- [ ] che.jdt.ls.extension.configuration.updatePreferences
- [x] che.jdt.ls.extension.debug.findResourcesByFqn
- [x] che.jdt.ls.extension.debug.identifyFqnInResource
- [x] che.jdt.ls.extension.debug.identifyFqnInResource
- [x] che.jdt.ls.extension.detectTest
- [ ] che.jdt.ls.extension.effectivePom
- [x] che.jdt.ls.extension.externalLibraries
- [x] che.jdt.ls.extension.externalLibrariesChildren
- [x] che.jdt.ls.extension.findImplementers
- [x] che.jdt.ls.extension.findTestByCursor
- [x] che.jdt.ls.extension.findTestFromEntry
- [ ] che.jdt.ls.extension.findTestFromFolder
- [ ] che.jdt.ls.extension.findTestFromProject
- [x] che.jdt.ls.extension.findTestInFile
- [x] che.jdt.ls.extension.import.organizeImports
- [x] che.jdt.ls.extension.libraryChildren
- [x] che.jdt.ls.extension.libraryContentByPath
- [x] che.jdt.ls.extension.libraryContentURL
- [x] che.jdt.ls.extension.libraryEntry
- [x] che.jdt.ls.extension.mavenProjects
- [ ] che.jdt.ls.extension.outputDir
- [ ] che.jdt.ls.extension.plain.createProject
- [ ] che.jdt.ls.extension.plain.getProjectSourceLocations
- [x] che.jdt.ls.extension.plain.sourceFolders
- [ ] che.jdt.ls.extension.plain.updateClasspath
- [ ] che.jdt.ls.extension.pom.diagnostics
- [ ] che.jdt.ls.extension.reImportMavenProject
- [ ] che.jdt.ls.extension.refactoring.move.command
- [ ] che.jdt.ls.extension.refactoring.move.get.destinations.command
- [ ] che.jdt.ls.extension.refactoring.move.validate
- [ ] che.jdt.ls.extension.refactoring.move.verify.destination
- [ ] che.jdt.ls.extension.refactoring.rename
- [ ] che.jdt.ls.extension.refactoring.rename.get.linked.elements
- [ ] che.jdt.ls.extension.refactoring.rename.get.type
- [ ] che.jdt.ls.extension.refactoring.rename.validate.new.name
- [x] che.jdt.ls.extension.resolveClasspath
- [ ] che.jdt.ls.extension.updateWorkspace
- [x] che.jdt.ls.extension.usages
- [ ] org.eclipse.che.jdt.ls.extension.filestructure

**Comment by jsalzbergedu** [comment]
The biggest ones that I'm missing (i think) are  che.jdt.ls.extension.plain.createProject, and any features dealing with package/file management (is creating packages done through calls to che, or are they simple directories in disguise?) Anyway, it would be very nice to be able to create new projects/packages/classes from lsp-java as one does in eclipse. How hard is it to implement those methods?

**Comment by yyoncho** [comment]
@jsalzbergedu 

1. Project creation will create simple project(not maven) which is useful for like school/demo projects which do depend only on JDK. Is this what you are looking for? 
2. There is https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven which I havent checked yet it does support project creation by maven archetype.
3. Currently, you could create class namespace by opening empty file, e. g. `/src/main/java/com/yourcompany/Class1.java` and then type `class` which will ask you to expand the `class` snippet from the JDT server. This is how it is intended to work in vscode. I am not using it, I have the following configuration: https://github.com/yyoncho/config/blob/master/my-snippets.el and the snippet itself: https://github.com/yyoncho/config/blob/master/templates/default-java.el which will insert the package+class once I open new java file. You could use it for whatever templates you want.

**Comment by jsalzbergedu** [comment]
For project creation, yes, it would be very nice if you could create it via the lsp server. Certain universities might require a simple eclipse project but not a maven one ;)

I see, so it is manual for package creation. Well, maybe if I get time I could look into doing that automatically from the elisp code then? I'd imagine it could also be made to have really good synergy with the treemacs plugin.

Thank you!

**Comment by yyoncho** [comment]
We are not going to use eclipse che for the future.
