### ISSUE TITLE
Running 

### ISSUE THREAD

**Issue by wandersoncferreira** [emacs-lsp/lsp-java#53]
Sorry, I am very new to Java and I finished all the setup. Everything is working, how do I run my code from the buffer? :✖️ 

My buffer content:

```elisp
public class Testando {
    public static void main(String[] args) {
        System.out.println("Hello, world!");
    }
}
```

File Testando.java

Thx

**Comment by yyoncho** [comment]
Running/debugging is covered by https://github.com/yyoncho/dap-mode/ . You should make sure that you have correctly configured maven/gradle project not only standalone java file.
