### ISSUE TITLE
Add lsp-java to melpa stable

### ISSUE THREAD

**Issue by SerialVelocity** [emacs-lsp/lsp-java#55]
According to your README, lsp-java is in melpa stable. Doing a quick search (http://stable.melpa.org/#/?q=lsp-java) of melpa stable shows that it isn't present. Could you please tag a release and get it into melpa stable?

**Comment by yyoncho** [comment]
I did https://github.com/emacs-lsp/lsp-java/releases/tag/1.0 - do you know whether this sufficient for melpa stable?

**Comment by SerialVelocity** [comment]
I think that's enough. We'll see soon :) Thanks!

**Comment by SerialVelocity** [comment]
Ah, unfortunately it doesn't work because the latest tagged version of `lsp-mode` is from a long time ago (getting `File mode specification error: (void-function lsp-provide-default-marked-string-renderer)`). Also, lsp-ui is missing.

Thanks for trying though!
