### ISSUE TITLE
Tab characters in generated code

### ISSUE THREAD

**Issue by david** [emacs-lsp/lsp-java#61]
When I trigger a code action like "Create field", I find that, when the field is created, it's indented with tab characters instead of using spaces (my configuration). Is there a setting I can change?

Thanks.

**Comment by yyoncho** [comment]
I believe that this depends on the current formatter, I tried it on my setup and it uses spaces. You may take a look at https://github.com/emacs-lsp/lsp-java/blob/master/features/Formatter.feature & https://github.com/emacs-lsp/lsp-java/blob/master/features/step-definitions/lsp-java-steps.el#L100 how to configure properly the formatter.

**Comment by yyoncho** [comment]
Please reopen if the guide provided in the previous comment does not work.
