### ISSUE TITLE
Can it be made possible to refuse edits?

### ISSUE THREAD

**Issue by jsalzbergedu** [emacs-lsp/lsp-java#62]
Sorry if this part is off topic but I just want to say that I am very impressed with the recent work on lsp-java. It went from being a sort of companion to eclipse for me to being usable on its own. Seems much more professional now. Kudos.

I don't know whether this is an lsp-java thing or just an lsp-mode thing, but sometimes edits are made
(e.g. an import like `org.junit.Assert.*` is changed to `org.junit.assertTrue`) that I would rather not be made. Would it be possible to somehow refuse those edits?

Thank you!

**Comment by yyoncho** [comment]
There is no such setting from in `lsp-java` or in eclipse.jdt.ls.  You may use `lsp-java-save-action-organize-imports` which will disable the organize imports on save (but you are going to lose also imports sorting). 

I suspect that this might be possible if you alter the project settings (stored in .settings folder in the project root) but I don't have enough knoledge for the JDT server to provide a guide for that.

Also, there are `che.jdt.ls.extension.configuration.updateJavaCoreOptions` and `che.jdt.ls.extension.configuration.updatePreferences` which might have the setting about * imports. 

I asked the question on the eclipse.jdt.ls channel, hopefully someone from the server side could provide the answer.

**Comment by yyoncho** [comment]
Thanks, @fbricon ! 

@jsalzbergedu I will close this bug since there is nothing I can do on `Emacs` side. Once the feature is available in jdt.ls I will implement in lsp-java.
