### ISSUE TITLE
Variable lsp-java-organize-imports does nothing

### ISSUE THREAD

**Issue by ianprime0509** [emacs-lsp/lsp-java#63]
First of all, thank you for your work on this project! Earlier today I was trying to figure out why my imports were still being organized on save despite having set `lsp-java-organize-imports`, and I later noticed that the correct variable is `lsp-java-save-action-organize-imports`. Upon further inspection, though, I noticed that `lsp-java-organize-imports` doesn't seem to be used anywhere; is there something I'm missing or could this variable be removed (to avoid confusion)?

**Comment by yyoncho** [comment]
Thanks for the report - it is typo.
