### ISSUE TITLE
`lsp-java-enable` fails (FreeBSD 11.2, Emacs 26.1)

### ISSUE THREAD

**Issue by Follpvosten** [emacs-lsp/lsp-java#65]
I have probably missed something in the README; when I try to run `M-x lsp-java-enable`, it downloads and compiles the server correctly, but then fails with the following message:

    lsp-java--locate-server-config: Wrong type argument: stringp, nil

I have no idea where this is coming from; my system is a fresh FreeBSD 11.2 Jail using the `latest` package repository, with `openjdk8` and `emacs-nox` installed.

I have copied most of the example init file in the README, while making some adjustments so it fits with my own configuration (e.g. I use global-flycheck-mode and global-company-mode, so I don't need the hooks to enable company/flycheck). Here is my init file: https://gitlab.com/Follpvosten/emacs-configs/blob/add-java/init-java.el

Did I miss some required configuration option, or set something to an unexpected value, and that's why it doesn't work? Or might this be an actual bug? I'm lost here.

**Comment by yyoncho** [comment]
(Reposting since the comment was lost by github)

I suspect that freebsd is missing from the switch clause: Can you do `toggle-debug-on-error` before calling `lsp-java-enable` and post the callstack? Can you also do: `M-x` `eval-expression` and enter `system-type` and post the output here.

**Comment by Follpvosten** [comment]
Callstack:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil "/home/emacs/eclipsejdtls")
  lsp-java--locate-server-config()
  lsp-java--ls-command()
  #f(compiled-function () (interactive nil) #<bytecode 0x20153b66d>)()
  apply(#f(compiled-function () (interactive nil) #<bytecode 0x20153b66d>) nil)
  #f(advice-wrapper :after #f(compiled-function () (interactive nil) #<bytecode 0x20153b66d>) lsp-java--after-start)()
  apply(#f(advice-wrapper :after #f(compiled-function () (interactive nil) #<bytecode 0x20153b66d>) lsp-java--after-start) nil)
  lsp-java-enable()
  funcall-interactively(lsp-java-enable)
  call-interactively(lsp-java-enable record nil)
  command-execute(lsp-java-enable record)
  execute-extended-command(nil "lsp-java-enable" "lsp-ja")
  funcall-interactively(execute-extended-command nil "lsp-java-enable" "lsp-ja")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

`system-type`:

    berkeley-unix

**Comment by yyoncho** [comment]
So it is a bug, can you change `lsp-java--locate-server-config` replace with 

``` emacs-lisp

(defun lsp-java--locate-server-config ()
  "Return the server config based on OS."
  (let ((config (cond
                 ((string-equal system-type "windows-nt") ; Microsoft Windows
                  "config_win")
                 ((string-equal system-type "darwin") ; Mac OS X
                  "config_mac")
                 ((string-equal system-type "gnu/linux") ; linux
                  "config_linux")
                 (t "config_linux"))))
    (let ((inhibit-message t))
      (message (format "using config for %s" config)))
    (expand-file-name config lsp-java-server-install-dir)))
```

This will fallback all unknown configurtion to `linux`.

**Comment by yyoncho** [comment]
Can you do `toggle-debug-on-error` before calling `lsp-java-enable` and
post the callstack? Can you also do: `M-x` `eval-expression` and enter
`system-type` and post the output here.
