### ISSUE TITLE
VScode features ....

### ISSUE THREAD

**Issue by j3kyl** [emacs-lsp/lsp-java#69]
hey @yyoncho Did you watch this presentation on VSCode Java extension that uses eclipse server? 
https://www.youtube.com/watch?v=RJIfsSmU9zk
Might get some cools ideas there ...

VSCode seems greater than I thought...too bad it is too GUIshy!

**Comment by j3kyl** [comment]
Oh, cool. I will re-watch and come up with a wish-list! Soon to contribute...

**Comment by yyoncho** [comment]
@eubarbosa spring boot support is in(require some company-lsp PRs to be in).

**Comment by eubarbosa** [comment]
@yyoncho 

Cool, ty for warning!!
