### ISSUE TITLE
Unicode characters in comments replaced by UFFFD (�)

### ISSUE THREAD

**Issue by siddharthist** [emacs-lsp/lsp-java#75]
When saving a Java file, I've had unicode characters in comments get replaced by an "unknown character" kind of thing. What's going on here?

**Comment by yyoncho** [comment]
I tried it with Bulgarian unicode symbols, it works on my machine. Do you have custom configuration for `coding-system-for-write`/`coding-system-for-read`? 

I suspect that specifying coding system at 
https://github.com/emacs-lsp/lsp-mode/blob/f54f564a498ac4f1b98e1dba3e3d621f624f9c02/lsp-mode.el#L47 might fix the issue. 

Can you set `lsp-print-io` and post the content of the *Message* buffer after reproducing the issue.

**Comment by siddharthist** [comment]
I think it was a weird interaction going on with organizing imports (some of my imports were jumped across a comment block containing unicode subscripts). Let me see if I can get it to happen again.

**Comment by yyoncho** [comment]
I believe that this was fixed by https://github.com/emacs-lsp/lsp-mode/commit/39e6c4694739574ea52cb318abc83b2e1953e6e2 please reopen if the issue reproduces again.
