### ISSUE TITLE
Formatter settings being ignored?

### ISSUE THREAD

**Issue by evan3334** [emacs-lsp/lsp-java#76]
I have set the `lsp-java-format-settings-url` and `lsp-java-format-settings-profile` variables to a valid path to a format settings .xml file generated with Eclipse, and the profile name in that file, respectively, as done in [this file](https://github.com/emacs-lsp/lsp-java/blob/master/features/step-definitions/lsp-java-steps.el#L100) (referenced in Issue #61). I have verified with `M-x describe-variable` that these variables were set correctly.

However, it appears like nothing has happened. Most notably, I have specified indents in that file to be 4 spaces, and running `lsp-format-buffer` still formats with 2 spaces. None of my other formatting changes apply either.

Am I doing something wrong here? Or is this a bug?

**Comment by yyoncho** [comment]
I guess it is a missing documentation piece - in addition to the formatter settings `lsp-mode` sends the currently set `tab-width` which is overriding the formatter value. I haven't investigated whether `lsp-mode` is doing the correct thing.

**Comment by bradyt** [comment]
I don't think java-mode even uses tab-width, does it? So maybe c-basic-offset would make a little more sense? Then again, it's kind of nice to have one variable to mess with for cc-mode indentation, and a separate variable to be sending to lsp-mode.
