### ISSUE TITLE
Company provides too long completions.

### ISSUE THREAD

**Issue by lshoravi** [emacs-lsp/lsp-java#77]
This:
![image](https://user-images.githubusercontent.com/42211142/48943082-43c96a00-ef22-11e8-8317-10e1ce5056a5.png)

Completes into this, and puts the cursor there:
![image](https://user-images.githubusercontent.com/42211142/48943093-5643a380-ef22-11e8-8cf5-70053046bba0.png)

Optimally, I would like it to complete to here:
![image](https://user-images.githubusercontent.com/42211142/48943117-71aeae80-ef22-11e8-839c-6c66f2c4a579.png)

Is there a fix for this?

**Comment by lshoravi** [comment]
Yup, it's on.

![image](https://user-images.githubusercontent.com/42211142/48943564-e7674a00-ef23-11e8-9ae1-dd0e2b654ab8.png)

**Comment by yyoncho** [comment]
Just to confirm - after you select the item from the list and press enter the `: void ` part is still present in the buffer? 
CC @tigersoldier

**Comment by lshoravi** [comment]
Indeed

**Comment by yyoncho** [comment]
Can you try reproducing the issue after forcing an update of the melpa deps(you could do that by deleting ~/.emacs.d/melpa) and loading the config from the start page after starting emacs with the following command: `emacs -q`?

**Comment by lshoravi** [comment]
I'm unable to test this properly, as since I tried reinstalling lsp-java no longer starts properly. It exits with error code 13 and no stderr output.

**Comment by lshoravi** [comment]
It does not reproduce with emacs -q.

The issue is in evil-collection and company-tng, which changes how the completion works. Setting evil-collection-company-use-tng to nil on startup fixes the issue.

**Comment by yyoncho** [comment]
@lshoravi as a side note, what font do you use?

**Comment by lshoravi** [comment]
I use Iosevka

https://github.com/be5invis/Iosevka
