### ISSUE TITLE
How to disable auto generating getter/setter javadoc

### ISSUE THREAD

**Issue by uqix** [emacs-lsp/lsp-java#78]

**Comment by yyoncho** [comment]
AFAIK server does not provide that possibility. @fbricon @gorkem if memory serves me right,  the eclipse provides an option to customize the code generation templates(e. g. try/catch, getters/setters) is there a plan for such feature in JDT LS?

**Comment by uqix** [comment]
@yyoncho you are right, eclipse does provide the option to customize that

**Comment by gorkem** [comment]
Please make sure this is reported on jdt.ls.

**Comment by yyoncho** [comment]
Closing in favour of https://github.com/eclipse/eclipse.jdt.ls/issues/872
