### ISSUE TITLE
Why do I get prompt for every new opened java files in a project?

### ISSUE THREAD

**Issue by amosbird** [emacs-lsp/lsp-java#79]
![image](https://user-images.githubusercontent.com/5085485/48977942-33aab980-f0df-11e8-863d-682faa686433.png)

Is that by design? The project is  https://github.com/Genymobile/scrcpy

**Comment by yyoncho** [comment]
Actually it seems like I was wrong - the VSCode fails to handle that project too. 

@fbrikon @gorkem it seems like Eclipse JDT LS could not handle that project(it is Android) and I am seeing the following exception in the logs VScode logs(and it the Emacs one), can you comment?

> 
> [Trace - 5:28:09 PM] Received notification 'window/logMessage'.
> Params: {
>     "type": 1,
>     "message": "Nov 25, 2018 5:28:09 PM Problem getting outline forControlEventReader.java\nsrc/main/java/com/genymobile/scrcpy [in server] is not on its project's build path\nJava Model Exception: Java Model Status [src/main/java/com/genymobile/scrcpy [in server] is not on its project's build path]\n\tat org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:583)\n\tat org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:256)\n\tat org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:530)\n\tat org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:250)\n\tat org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:530)\n\tat org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1243)\n\tat org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:250)\n\tat org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:596)\n\tat org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:326)\n\tat org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:312)\n\tat org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:267)\n\tat org.eclipse.jdt.ls.core.internal.handlers.DocumentSymbolHandler.getHierarchicalOutline(DocumentSymbolHandler.java:129)\n\tat org.eclipse.jdt.ls.core.internal.handlers.DocumentSymbolHandler.documentSymbol(DocumentSymbolHandler.java:74)\n\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$13(JDTLanguageServer.java:573)\n\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$25(JDTLanguageServer.java:780)\n\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)\n\tat java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)\n\tat java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)\n\tat java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)\n\tat java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)\n\tat java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)\n\tat java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)\n"
> }
>

**Comment by gorkem** [comment]
We have not really worked on supporting Android projects, if I have to make a guess buildship, the bits we are using for gradle integration, is not handling this project correctly. @fbricon

**Comment by madper** [comment]
In fact I met the issue as well on [ThingsBoard](https://github.com/thingsboard/thingsboard) which is not an android project...

**Comment by yyoncho** [comment]
@madper it is the same problem - JDT LS fails to import the project. I will fix lsp-java to stop displaying the popup for import project when the project is already imported. This will partially fix the issue since the root cause is in the server. I will file an issue against JDT LS and you will be CC-ed.

**Comment by madper** [comment]
Thanks a lot!
I just noticed that JDT LS is going to migrate to Buildship 3.0 which may fix the issue.
Let me retest it after that.

**Comment by yyoncho** [comment]
I have fixed the `lsp-java` issue. You will be asked only once but until the server side issue is fixed you won't be able to use the full JDT functionality.
