### ISSUE TITLE
How do workspace and classpath work?

### ISSUE THREAD

**Issue by didibus** [emacs-lsp/lsp-java#84]
I'm confused how to configure the Java classpath and/or lsp-mode workspace/project for Java. Can it use an eclipse project file? Does it need a pom.xml? What if I use a different build tool, can I manually give it a classpath?

**Comment by yyoncho** [comment]
you may use maven/gradle and eclipse project. For more details you may refer to https://github.com/eclipse/eclipse.jdt.ls/ or https://github.com/redhat-developer/vscode-java . The second one is the vscode client with which lsp-java is targeting feature parity.

**Comment by yyoncho** [comment]
> What if I use a different build tool, can I manually give it a classpath?

You may create manually .project file which is effectively manually providing classpath.
