### ISSUE TITLE
void-function lsp-java-enable

### ISSUE THREAD

**Issue by mandarm** [emacs-lsp/lsp-java#86]
**Getting error-message: (void-function lsp-java-enable)**

This happens when opening any .java file.

Running Emacs 25.3.2, with updated packages:

    company-lsp-20181213.2344/                      Dec 15 12:26 
    dap-mode-20181209.949/                          Dec 15 12:18 
    find-file-in-project-20181203.433/              Dec 15 12:18 
    flycheck-20181214.1048/                         Dec 15 12:18 
    lsp-java-20181208.626/                          Dec 15 12:17 
    lsp-mode-20181213.2013/                         Dec 15 12:17 
    lsp-ui-20181209.123/                            Dec 15 12:17

(and many more)

Relevant portion of my init file:

    (require 'lsp-java)
    (add-hook 'java-mode-hook 'lsp)
    (add-hook 'java-mode-hook #'lsp-java-enable)
    (add-hook 'java-mode-hook
              (lambda ()
                (projectile-mode)
                (lsp-mode)
                (lsp-ui-mode)
                ;(lsp-java-enable)
                (company-mode 1)
                (dap-mode t)
                (dap-ui-mode t)
                (flycheck-mode)))

Backtrace on turning on debug-on-error:

    Debugger entered--Lisp error: (void-function lsp-java-enable)
      lsp-java-enable()
      run-hooks(change-major-mode-after-body-hook prog-mode-hook c-mode-common-hook java-mode-hook java-mode-hook)
      apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook c-mode-common-hook java-mode-hook java-mode-hook))
      run-mode-hooks(java-mode-hook)
      java-mode()
      set-auto-mode-0(java-mode nil)
      ...

I also tried with `emacs -Q -l foo.el` where `foo.el` contains the lisp
code from https://github.com/emacs-lsp/lsp-java, and got the same error.

Grateful for any help, thanks!

**Comment by yyoncho** [comment]
Change your config to:
```
(require 'lsp-java)
(dap-mode t)
(dap-ui-mode t)
(setq lsp-prefer-flymake nil)
(add-hook 'java-mode-hook 'lsp)
```
