### ISSUE TITLE
Provide the ability to run main class

### ISSUE THREAD

**Issue by iocanel** [emacs-lsp/lsp-java#98]
Currently its possible to debug and application, but I don't see a way of running the application. It would be nice if running the application and seeing the output in a new window.

**Comment by yyoncho** [comment]
At this point this is missing, the closest thing to what you want to do is:
`dap-debug` and select `compile/attach` option and then eventually do `dap-disconnect` when a breakpoint is hit. But, yeah, the java templates have to be rewritten to allow easy customization. As a side note, the output of the application when you are doing debug is available via `dap-go-to-output-buffer`.

**Comment by yyoncho** [comment]
The run capability is available if you specify `:noDebug t` in the dap template. You could create new templates using `dap-debug-edit-template`.
